### ISSUE TITLE
Port goon's landing lights

### ISSUE THREAD

**Issue by clusterfack** [vgstation-coders/vgstation13#10259]
They look neat as shit, they slowly flash on/off. And since Bus uses **traffic cones** for this purpose you can rather easily replace the traffic cones with these which look far superior.

**Comment by PJB3005** [comment]
I've literally been suggesting we make something like this for more than a year.

**Comment by clusterfack** [comment]
I don't recall ever hearing that

**Comment by ComicIronic** [comment]
He has been suggesting it for ages.
