### ISSUE TITLE
People that eat raw necromorph meat should slowly turn into necromorphs themselves.

### ISSUE THREAD

**Issue by Blute1** [vgstation-coders/vgstation13#10827]
http://deadspace.wikia.com/wiki/Feeder

The Feeder is a Necromorph form encountered on Tau Volantis. They are formed from humans that ingest Necromorph-infected meat. These creatures are seen during the events of Dead Space 3.

**Comment by Skullyton** [comment]
Guess it would make butchering a whole lot more dangerous, just in case somebody eats floorfood.

Is there an on_consumption function or something similar?

**Comment by Allspice** [comment]
If someone knowingly ate necro meat as a nonantag, would that be like knowingly eating advanced mut toxin as a nonantag?

**Comment by Shadowmech88** [comment]
>Is there an on_consumption function or something similar

You can give necromorph meat a special reagent and then give that reagent an on-consumed effect. Look at the reagent used by potent ham as an example.

**Comment by Skullyton** [comment]
Can't help but feel somebody would just grind up the necro meat, and add very miniscule amounts of the reagent to all food so everyone becomes feeders, akin to nanites

**Comment by Spacedong** [comment]
thats why you'd make it so that only above a certain amount are people changed into necromorphs

**Comment by Imagebard** [comment]
As it stands, a feature like this is only going to cause griefing since its basically a free antag if you kill a Necromorph meat.
:-1:

**Comment by Spacedong** [comment]
maybe give them a disease with visible symptoms so people can have a chance to quarantine?
