### ISSUE TITLE
allow a borg losing its powercell to not fuck him up completely

### ISSUE THREAD

**Issue by Blute1** [vgstation-coders/vgstation13#10868]
if your powercell is fucked from an explosion or by some other means as a borg, you can't pull, use emotes, talk in borg chat, interact with anything, all you can do is move around and listen to messages about how "You can almost hear someone talking...." forever. There's no way to tell anybody that you're broken at all. It's kinda fucking retarded broje

**Comment by Ephx1** [comment]
And your suggestion is? Things usually stop working when they have no powercell, especially in the case of borgs where it's usually brutally knocked out.

**Comment by Shadowmech88** [comment]
I believe his gripe is "there's no way to tell anybody you're broken."
So maybe add some obvious sprite change or examine text for borgs that have broken power cells, so people know that the borg is disabled instead of assuming it's just a mute.

**Comment by Ephx1** [comment]
Ehhh, borg sprites usually have a glowy bit on them, that when broken will shut off. A very minute change, so yeah something that's more noticeable would be nice.

**Comment by Allspice** [comment]
Borgs without a cell can move, but a shattered actuator knocks out your legs.

**Comment by Skullyton** [comment]
Let em ping and buzz, maybe?

**Comment by PJB3005** [comment]
Examination also says they're out of power.

**Comment by ComicIronic** [comment]
Feels like a non-issue.

**Comment by NigglyWiggly** [comment]
Add a sparking or something if you want, but I really don't see the issue with this.
If anything, borgs can do TOO much without a cell, but I suppose that's just a backup power thing

**Comment by ConkerDev** [comment]
borgs without power shouldnt be able to move at all
MMI speaking would be fine and make sense, maybe even visibly partially eject the MMI? Auto open the cover?

**Comment by clusterfack** [comment]
I'm fairly sure we have another issue which says to fuck up borgs MORE when they get their powercell removed.

It's all fucking relative really. Does it replace your charge icon with a no battery icon? It probably should if it doesn't already.

**Comment by Killette2** [comment]
What about What @ConkerDev said, but in the addition borgs with no/broken cell have no power, no movement like no actuator, no robotic talk, but in exchange they get local MMI chat. If they have a radio enabled MMI, then they're extra lucky.

**Comment by clusterfack** [comment]
No that's useless, thats WORSE than being blown up.

**Comment by 9600bauds** [comment]
Seems equal to being blown up to me

**Comment by Allspice** [comment]
I'd like it if a blown borg's MMI was immediately ghosted to be later re-entered but that's a slightly different matter.

**Comment by clusterfack** [comment]
AFAIK you can ghost and re-enter MMIs

**Comment by BestName** [comment]
Borgs are able to magically move around without a power source and you want more?
C'mon m8

**Comment by Killette2** [comment]
Nah being DESTROYED and needing a new body built is different than not having a cell. That's like comparing being dead and needing a defibulation+cryogenics(assuming no bloodloss) to being gibbed and needing a head reattachment or brain transplant.

My suggestion is fine, it's like being dead EXCEPT you can talk to local people, or if you're lucky and near a radio you can talk to everyone.

**Comment by Skullyton** [comment]
I've noticed that, after having the actuator shot out, I was able to move and mobs ignore me after having the cell shot out.

**Comment by Killette2** [comment]
Powerless borgs when? They can save the crew from hostile mobs by bumping into them long enough for the crew to escape. It's more protection than a powered borg may be abe to offer.
