### ISSUE TITLE
Make space ambience themes match

### ISSUE THREAD

**Issue by clusterfack** [vgstation-coders/vgstation13#11645]
We have really shitty and clashing space ambience music. Some are much louder than all the others, space.ogg sounds like some shitty mass effect battle music, ambispace.ogg sounds like starcraft music, while spookyspace1&2 are much more muted. Space.ogg is primarily the worst offender for clashing with all the other ambiences.

For reference here are three of the current songs we have for space ambience
https://raw.githubusercontent.com/d3athrow/vgstation13/Bleeding-Edge/sound/music/space.ogg

https://raw.githubusercontent.com/d3athrow/vgstation13/Bleeding-Edge/sound/ambience/spookyspace1.ogg

https://raw.githubusercontent.com/d3athrow/vgstation13/Bleeding-Edge/sound/ambience/spookyspace2.ogg

https://raw.githubusercontent.com/d3athrow/vgstation13/Bleeding-Edge/sound/ambience/ambispace.ogg

We should probably replace some of them to make a more thematically matching soundtracks, and we're clearly open to suggestions here.

**Comment by Exxion** [comment]
Related: #10498
