### ISSUE TITLE
AI has full vision in the Skipjack despite it not containing any cameras

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#12229]
![shitl](https://cloud.githubusercontent.com/assets/12042425/19415056/166227e0-9318-11e6-8bd1-e32109187ae9.png)

**Comment by kol1th** [comment]
MY EYES 🔪 👀

**Comment by Shadowmech88** [comment]
This graphical issue isn't new. I believe it's something related to the individual player's DirectX not being up to date or something like that.

**Comment by JustSumBody** [comment]
To clear this up, the graphical issue isn't the problem. The issue is that the AI has full camera vision over it when there aren't any cameras in it. This was when it was docked at the trader outpost, not sure if that's because of the previous issue with the vox hydro camera or what. I recall seeing it disabled at one point even but he still seemed to be able to see.

**Comment by Shadowmech88** [comment]
Wait, so that AI player is actually playing the game like that?
How terrible.

**Comment by Exxion** [comment]
Yes, it's almost as disgusting as the title is uninformative

**Comment by clusterfack** [comment]
Absolutely disgusting

**Comment by coldcola** [comment]
muh powergame

**Comment by PJB3005** [comment]
Fucking hell man install DirectX with wine tricks already!

**Comment by Probe1** [comment]
holy shit that screen

**Comment by Exxion** [comment]
Alright
As disgusting as the screenshot is, it's about time to talk about/fix the actual issue

**Comment by Probe1** [comment]
Yeah I'm gonna look at it.

**Comment by Intigracy** [comment]
Tfw even admins are powergamers.

**Comment by optimumtact** [comment]
As an aside that graphical glitch usually indicates that byond failed to intiate hardware mode for rendering and so rendering modes like blend and planemasters do not work.

Most commonly seen in VM's or wine users

**Comment by PJB3005** [comment]
Nope, HW mode initialized but shaders are failing to run correctly, which happens when DirectX is broke.

If HW mode is off it'd be even worse.

**Comment by AI-is-rogue** [comment]
You can fix the rainbow issue by downloading directx9 with the directx end user runtime web installer, it's caused by goon lights and the goon wiki had this solution.

**Comment by Exxion** [comment]
Yeah, we all know
@Allspice intentionally leaves it broken to powergame

**Comment by AI-is-rogue** [comment]
whew

**Comment by optimumtact** [comment]
we did it
