### ISSUE TITLE
MoMMI Spaghetti does nothing.

### ISSUE THREAD

**Issue by AutismSpider** [vgstation-coders/vgstation13#12579]
After eating 10 bowls of mommi spaghetti one round and two Roburger as a plasma man i think some thing is wrong with the transformation food items or they just don't work on non human races?

**Comment by Kurfursten** [comment]
Cannot reproduce on human

Suspecting skeletons/noblood races can't get virus1 stuff

**Comment by AutismSpider** [comment]
yeah then its no blood race thing then.

**Comment by Manfreedo** [comment]
Ate a bowl of selfmade mommi Spaghetti last round. Nothing happened.

**Comment by Kurfursten** [comment]
There's a chance it won't catch because viro1 RNG

We should burn it down

**Comment by Manfreedo** [comment]
Ate some again (as normal Human) last round, This time it worked. Might be RNG related as Kurfursten said.

**Comment by Manfreedo** [comment]
It seems to be broken again. Tried eating it 2 times last round with no effect.
