### ISSUE TITLE
Can't cook Poppy Pretzels any more

### ISSUE THREAD

**Issue by AutismSpider** [vgstation-coders/vgstation13#12582]
Who touch the recipes/Microwave can't put in poppy seeds or a poppy in to make this.

God knows what other recipes are fuck up now.

**Comment by Kurfursten** [comment]
Unable to reproduce on live

Successfully cooked poppy pretzel by usual method

**Comment by AutismSpider** [comment]
round start microwave on meta try using normal poppy seed pack form the vend and bit later modified one bit later just give me you don't what you can cook with poppy seed.

**Comment by FudgePucker** [comment]
@AutismSpider
Are you at least proofreading your comments before posting?
Not trying to be a dick. I would be fine if English isn't your primary language and you were putting in some effort, but your comments look like they were put into a blender.

From what I can read of your comment you want to know if Kurf tested round start seeds and modified seeds. Also I think poppy? seeds also need to be tested.

**Comment by Kurfursten** [comment]
What he's actually saying is a more specific report. He claims that roundstart seeds on metastation weren't working in the microwave.

I don't think it's actually metaclub that's the issue (I checked the map just to be sure). Some other people mentioned having occasional issues with the roundstart seeds once or twice, but nothing consistent enough to reproduce. This seems like quite an oddball issue.

In either case, modified poppy seeds definitely don't work.
