### ISSUE TITLE
empty AI core on emergency shuttles

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#12658]
Card an AI, mosey on over to the shuttle, pop it into the shuttle core so it can continue preventing human haaaarms and all that.

**Comment by jknpj** [comment]
> so it can continue preventing human haaaarms

It is literally impossible to prevent harm inside the shuttle, even as borg. Unless you're willing to add shutters and turrets

**Comment by Allspice** [comment]
Open airlocks for escapees and all that.

**Comment by Ephx1** [comment]
The shuttle has no power source, try doing the same with a normal core and you'll just slowly kill the AI.

**Comment by Probe1** [comment]
That's not an insurmountable issue with the magic of shitcoding, shitmapping, and varedits.

**Comment by Allspice** [comment]
I believe that was changed at some point actually Ephx, can now wheel the AI core to the shuttle and it won't die.

**Comment by Ephx1** [comment]
Oh OK. Then I don't really see the point of adding an AI core then, they can only touch a few doors and two sleepers, if you really wanted to do it just take the AI.

**Comment by ComicIronic** [comment]
Can't you just enable the AI's features on the card anyways?

**Comment by Ephx1** [comment]
That too, but I guess he want full reign of the shuttle and most time you're placed in the cockpit.

**Comment by SonixApache** [comment]
Having an inactive core in the cockpit would be fantastic. The card is suffering.

**Comment by Lokiamis** [comment]
Could add it to the TG shuttle pretty easily but it might be more fun to make our own
![untitled2](https://cloud.githubusercontent.com/assets/25004372/23826974/1069d740-067f-11e7-8349-a4f7f47dcba0.png)

The Bay one is nice too, although it only has two doors and security would need to drag prisoners through the clusterfuck
![untitled](https://cloud.githubusercontent.com/assets/25004372/23826948/6efccc5a-067e-11e7-9e84-6c7c91fb9b60.png)
