### ISSUE TITLE
Vampires can thrall implanted individuals.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#12708]
Simultaneously bad and dumb and should be removed.

**Comment by Exxion** [comment]
Hey at least thralls can be deconverted now

**Comment by Probe1** [comment]
Its not great but it does help separate vamp from other modes.  I'm undecided about it.  I don't hate it it love it.

**Comment by Ephx1** [comment]
Well considering the fact it stops both technological mind control and literal-dark god control, it seems a bit weird some faggot who bites people can circumvent it.

**Comment by Exxion** [comment]
Not arguing for or against it here, but it actually does add up from an immulsions standpoint
The loyalty implant exists specifically to make you loyal to NT
Revs are *specifically* anti-NT, so it makes sense that the implant would work against them
The cult isn't *directly* anti-NT, but is still an "opposing" "organization", so it also makes sense that the implants work against them, but are less effective.
Vampires aren't specifically for or against NT. You can be loyal to both NT and to the vampire.

**Comment by Ephx1** [comment]
You know I'm gonna be honest that's just silly, the vampire is easily against NT and can _become_ an opposing organization with enough followers

**Comment by Exxion** [comment]
Yeah, the whole loyalty implant thing works better on a high-RP server
Because then they'd still be a thrall, but couldn't follow certain orders, I guess

**Comment by JustSumBody** [comment]
Wait, I thought there were two levels of thrall or something?
First level couldn't thrall through implants, second level could

**Comment by Sprok0** [comment]
They gain the ability to thrall at 300, and thrall through implants at 500. It isn't really meaningful because if they get to 300 they'll get to max almost every time.

**Comment by Exxion** [comment]
Oh, so there's already a mechanic for this
Still, discussion is good

**Comment by Ephx1** [comment]
I'm a bit more OK with it being an upgrade if true, I'm sure no one noticed because a. it's easy for a vamp to amass loadsa blood and b. thrall got through implants originally
