### ISSUE TITLE
Can be Auto Traitor as a mouse.

### ISSUE THREAD

**Issue by AutismSpider** [vgstation-coders/vgstation13#13192]
How many times have we fix this bug?
![time to stop](https://cloud.githubusercontent.com/assets/10268342/21577270/96771b50-cf1a-11e6-8f9c-141f480b754d.PNG)

**Comment by Ephx1** [comment]
> Auto tatered mice turn into rats that bite for 5 brute

Shame this won't happen because people would abuse it, but I can dream

**Comment by uazuaz** [comment]
well. if only happened to traitor mice is not really an abuse.

**Comment by SGuivenne** [comment]
Also fairly sure this bugs since been resolved or if its not it really should be.

**Comment by Pathid** [comment]
Still happens, AFAIK. No non-antag is immune from autotraitor except MoMMIs.

**Comment by Exxion** [comment]
Does this still happen, now months after the last time it was asked?

**Comment by DamianX** [comment]
Yeah, a borer was a traitor just a few days ago

**Comment by Shadowmech88** [comment]
Is this still a thing after Antag Datums?

**Comment by MadmanMartian** [comment]
Should no longer be an issue
