### ISSUE TITLE
Crew Monitor Console is fucking up again

### ISSUE THREAD

**Issue by aceedex** [vgstation-coders/vgstation13#13216]
it's not showing the station minimap when you click on it, like so
https://puu.sh/t7KAi/cbcd2f5bda.png

It's also doing that thing where if you try to change z leves the input won't register and goes into the chat bar instead, which was fixed some time ago but seems to be happening again

**Comment by Probe1** [comment]
all of the minimap consoles are  😢

**Comment by PJB3005** [comment]
"again"

**Comment by Probe1** [comment]
At this point I'm thinking we poach something from another server that handles it in a way more sane and robust way that doesn't break every 6 months.

**Comment by PJB3005** [comment]
That fix would be reverting it to Nano and moving Nano's JSON to native BYOND.

**Comment by Probe1** [comment]
I know some of these words.

**Comment by BobdaBiscuit** [comment]
Don't you just have to regenerate the minimaps with the verb?

**Comment by Probe1** [comment]
I have no idea what that verb may be.

**Comment by Exxion** [comment]
I'm convinced this is a BYOND bug
Assuming it's still the same issue, it's a problem with caching, but that shouldn't be possible

**Comment by Ephx1** [comment]
#5945
never4get

**Comment by uazuaz** [comment]
changing the z-level could be done the same way as the bhangmeter: click the "change z-level" button and choose from the list of available z-levels.

**Comment by PJB3005** [comment]
Bhangmeter is still Nano.

That's why it actually fucking works.

**Comment by BobdaBiscuit** [comment]
Ya gotta press the "Debug Verbs" in the debug category, then under the mapping category generate nanoUI maps etc.

@Probe1

**Comment by Shadowmech88** [comment]
Tested, works fine for me.
Is this one of those bugs that only shows up sometimes/for some people?

**Comment by Exxion** [comment]
Pretty sure it was, but the image is gone so I'm not sure

**Comment by Shadowmech88** [comment]
I'm just unsure if I should close it just due to being unable to reproduce, because it's currently listed as one of the hard bugs for October.

**Comment by Exxion** [comment]
Not even sure it still happens
If it's the bug I think it is, I'm about 95% sure it was a BYOND bug, which may well have been fixed at some point
