### ISSUE TITLE
Naming manifested ghosts still broken.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#13225]
![ghost](https://cloud.githubusercontent.com/assets/12042425/21588059/af4f78b0-d097-11e6-8544-f61f7c87562a.png)

"faget" written on a paper on the manifest ghost rune. When the ghost was created it had the name in the lower-left and it could not talk.

**Comment by nervere** [comment]
Manifested ghosts still exist in the code but aren't summonable anymore as the rune is completely gone with Cult 4.
If the ghost is ever brought back, it will be with entirely different code, so this issue report is no longer useful.
