### ISSUE TITLE
AI integ restorers show law 0 but cards don't.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#13400]
Also notable is that the integ restorers do not show ion/hacked laws. I think showing law 0 on integ restorers should be REMOVED but others may feel differently.

**Comment by Ephx1** [comment]
Not sure how I feel about this actually. A card is a simple little machine but it feels like a computer that can reconstruct a whole AI _should_ know all of the laws.

**Comment by yclatious** [comment]
Maybe its just me, but I wouldn't call a high tech piece of portable equipment that is able to fully house a AI and allow it to be a fully functioning piece of software, whilst restricted to something a tenth of its usual size, as just a simple little machine.

Its high NT tech, I don't see why a portable AI holder that is already quite advanced can't see its laws.

**Comment by Intigracy** [comment]
Balance reasons.

**Comment by Allspice** [comment]
In my view, there's two perspectives to it. From MUH LORE/RP/whataver, NT tech and policy is notoriously shoddy and half-assed in various respects. Law 0 and ion laws don't show on cards due to underflow errors or some such, come up with your own justification it does not matter much.

For GAMEPLAY, it does little to nerf the balls-to-the-wall blasma murder rampage AIs that people get pissed experiencing, and instead undermines the AIs that attempt to take a more subtle approach to their antagonizing. If you believe that XYZ only has vaporous suspicions that you're doing funny things, then you can let them card you, observe no subversive laws, and persuade them to re-core you. And if they had more concrete evidence and they wipe you on the spot, then your gamble failed; it happens, oh well. But if they can just take you to the integ restorer to confirm that you're a tater shit and get you got thereby, then once someone starts knocking at your upload with a card, your only feasible option is to kill kill kill. Which I think people dislike more than sillycunt subtlety. Perhaps.

**Comment by DamianX** [comment]
I forgot to autoclose this in the PR
CLOSE IT
