### ISSUE TITLE
When someone loses just one foot, medically, they are permanently stunned

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#13657]
#### Description of issue

Played a round today where a doctor just tore off one foot and left them in surgery. Since you cant walk or hold items all they had to do was remove the headset and the person was basically permastunned

#### Difference between expected and actual behavior

Generally, crawling and basic use of your hands. There is no reason that you should be incapable of doing ANYTHING if you are missing a foot

#### Steps to reproduce 

cut off a persons foot
person is permastunned

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by CptWad** [comment]
woops hitting enter when I meant to hit tab

**Comment by Exxion** [comment]
The "can't move at all ever when on the ground" and "can't hold things while lying down unless they are actually GLUED to your hand" memes are getting out of hand  (no pun intended)

I mean
They've always been out of hand
But people complained less for some reason

**Comment by ThePlapatin** [comment]
Very annoying issue, people without a foot could at least walk with a chance to stumble maybe? I also don't believe legless people can use wheelchairs, they just fall out of them. Though perhaps this was fixed as it happened weeks ago.

**Comment by Exxion** [comment]
I believe that happens when you don't have an ass.
Better question, though: Aren't you banned?

**Comment by kilozombie** [comment]
It'd be cool if you could walk without a leg/foot, but at a 20% speed or so. Bumped up to 40% when you're hugging a wall.

**Comment by Skullyton** [comment]
Or using one of the canes that's in box medbay storage

**Comment by IAGFPRMF1** [comment]
Back in the olden days, you were able to crawl around after loosing a leg or foot. A little bit of hyperzine had you roll around at max speed. What ever happened this?

**Comment by Probe1** [comment]
Non antag vox stole the code.

**Comment by DamianX** [comment]
Crawling fixed this
