### ISSUE TITLE
Scientist's Access and how it could be modified

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#13753]
As it stands a Scientist can do the job of a roboticist, but better. The job title itself has much more access than it needs, in my opinion. There are a lot of alternate titles, like Plasma Researcher or Xenobiologist but they all come with the same access as the default title, if I'm not mistaken.

I propose that this be changed. A Scientist should have access to just R&D, a Xenobiologist just to xenobiology, a Plasma Researcher just to Toxins, a Xenoarch to the outpost, that from which I gather just requries basic science access, which every job in the science department should have anyway.

Obviously this would straight away make R&D undoable. No one in their right mind would want to do R&D and deliver toys to people and not have access to anything else. That is why leaving R&D access to all science jobs is also acceptable, sort of how Medical Doctors have chem and genetics access. Although I do prefer the less-access option.

This would leave telescience. I strongly believe that the paramedic should have access to it. Telescience is used nefariously to steal shit from the traders, sec or break people out of jail, all of which I myself as a scientist am guilty of. That is, unless you have someone whos job is actually saving people's lives, then the use of telescience changes drastically. Now of course there are people who use telescience and set it up with a CMC and make a telebay, but its quite rare for it to be permanently manned. 

I would be very happy to hear what everyone has to think about this.

**Comment by jknpj** [comment]
Roboticist - R&D / Robotics
Toxins Research - R&D / Toxins
Xenoarch / Xenobotanist/Anomalist - R&D / Research Outpost
Xenobio - R&D / Xenobio
RD - Everything else

**Comment by DamianX** [comment]
Move toxins to research outpost but keep it a separate access so only Toxins Researcher can get in

**Comment by jknpj** [comment]
I agree with moving toxins to reseach outpost as long the test range comes too. <s>unless you want to make a mass-driver chain and use the vox outpost as test range

**Comment by Diavill** [comment]
I understand that when talking about access that mapping comes hand in hand but I would like to avoid any semblance of mapping changes. I believe that on both Metaclub and Box that the access changes I talked about are fine to make. But of course Deff has to be a pain in the ass by not having a maint tunnel leading into telescience from which a paramedic can enter without bothering science.

**Comment by JustSumBody** [comment]
Ideally science's 50 snowflake job titles are made different jobs entirely with a bit more restricted access, in a matter jknpj suggested.

As it is now, the only difference between robotics and the 42 flavors of science are:
Robos have tech storage
Science has xenobio and toxins

Science as a department is in an absolutely terrible spot in my opinion. On top of having almost literally everything you could ever need in your department(arguably second only to cargo in self sustainability), you have access to almost all of it regardless of job title. There is no good communication or need to communicate even with other scientists, much less the rest of the station. 

Also disagree heavily with giving paramedics telesci access off the bat. Your argument 
``` That is, unless you have someone whos job is actually saving people's lives, then the use of telescience changes drastically.```
 is just plain not true. I dealt with an ahelp earlier when a bird was asking if they could bomb science for telesci stealing their bluespace crystals, when it was the paramedic who had stolen it using telescience anyway(I'm pretty sure that paramed was you too you fucking nig).

**Comment by Diavill** [comment]
> (I'm pretty sure that paramed was you too you fucking nig)
Honk.

Telescience still is most useful when a paramedic is manning it, barring out the one time I stole from a bird I was actually there to teleport countless dead from around the station and 'roid. Consider a paramedic who has his ass GLUED to telescience. Now consider a scientist who is running to and fro from RnD to robotics to the outpost etc., they'll probably forget to even make a CMC in there unless asked. Whereas a paramedic can unwrench the one in their office and boom, you've set up telescience.

**Comment by Rattlederp** [comment]
with prob's deff medbay rework, there's only a single r-wall between telesci and medbay

**Comment by SonixApache** [comment]
scientist is general purpose, can work anywhere in the science wing

**Comment by Diavill** [comment]
But why is then roboticist confined in its access? Why have titles other than scientist but which have the same access? Surely it should make sense that a xenobiologist not have access to toxins.

**Comment by Yelier** [comment]
I like the idea of scientists only getting access to their own profession and R&D. Not sure how to deal with toxins, though. The roid is basically the go-to for testing bombs after you do the first one, but giving them toxins, toxins storage, AND the roid is silly.

**Comment by AI-is-rogue** [comment]
>The roid is basically the go-to for testing bombs

stay away from my digsites reeee
