### ISSUE TITLE
Box sec has no buckshot box

### ISSUE THREAD

**Issue by yclatious** [vgstation-coders/vgstation13#13783]
Probe told me to do this so he wouldn't forget.

#### Description of issue
Box has every kind of shotgun shell box but buckshot in its ammo area.

#### Difference between expected and actual behavior
For sec to also have buckshot and for players to know it exists when currently, nobody but maybe coders and gungonia retards do.

#### Steps to reproduce 
Go to box, see it has no buckshot box and become sad that sec can't buckshot greyshits who try to yaketi sax.

#### Length of time in which bug has been known to occur
Apparently forever since Probe told me the guy who added it never mapped it in.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Riekland** [comment]
Nani? I know I've used buckshot from the armoury in the past week/month, this is some trippy shit. Was there a PR to change the box locations or some shit?

**Comment by Shadowmech88** [comment]
Are you sure it wasn't the result of someone ordering a shotgun ammo crate and putting the buckshot box from it into the armory?

**Comment by yclatious** [comment]
The guy who made them even said he didn't add them to sec roundstart because they were so powerfull at the time, it was most likely someone ordering a shotgun ammo crate and placing the box in sec.

Just double checked the area on my version, no buckshot in sight.

**Comment by Riekland** [comment]
I honestly believe that there's always been a box in the amoury, I even wrote the wiki page and I can vividly remember putting down information about four seperate boxes. Something's fucky here I tells ye.

AHA
http://ss13.moe/wiki/images/f/f9/Armory.png
I TOOK THIS FUCKING PICTURE FROM THE DREAMAKER THINGIE I KNEW IT WAS THERE

**Comment by Shadowmech88** [comment]
That box in front of the armory is a box of shotgun slugs, not buckshot.

**Comment by Riekland** [comment]
Oh wait no that's not my image, this one is http://ss13.moe/wiki/images/e/e4/Warden_Office.PNG

**Comment by yclatious** [comment]
http://imgur.com/WgVvIXZ

**Comment by yclatious** [comment]
Bloody hell, byond screenshots are shit

http://imgur.com/Nj8grc5
