### ISSUE TITLE
Hair Sprites

### ISSUE THREAD

**Issue by Riekland** [vgstation-coders/vgstation13#13867]
The current hair sprites are split between the nice looking ones that the one spriter made like two years ago, and everything else. There's some hair that looks fine with solid colour, like the cut and short hairs that have been around forever, but there's some that desperately need shading.
For example, the "Bobcurl" shown top is just one solid block of colour, where the "Bob" shown bottom has at least the impression of flow.

![ew](https://cloud.githubusercontent.com/assets/9220789/22668329/426248c6-ecb8-11e6-867b-c8faf18ea323.png)

I'm not a good spriter by any stretch so this is a feature request, but I'll keep trying to unfuck the sprites in my spare time.

**Comment by kol1th** [comment]
Send them to me and I may or may not add them
