### ISSUE TITLE
Roombas do lot of damage when in attack mode.

### ISSUE THREAD

**Issue by AutismSpider** [vgstation-coders/vgstation13#14171]
Some times its harmless other times they can put you in crit form one attack.

Some how one gave me 150+ burn damage as plasma man and busted my foot when ask for the attack logs after it did this to me  nothing in attack log.

**Comment by Exxion** [comment]
Absolutely magical

**Comment by AutismSpider** [comment]
![killer clean bots](https://cloud.githubusercontent.com/assets/10268342/23293240/b7bee0e6-fa2a-11e6-8126-b9b7e59e3926.PNG)

pushing a monkey into it one time

**Comment by Skullyton** [comment]
Eh?

They should only be able to do a maximum of 12 brute damage and 6 burn damage at a time.

Unless brute modifiers are being silly

**Comment by Shadowmech88** [comment]
Maybe the roomba is bumping the mob more frequently than intended?

**Comment by AutismSpider** [comment]
@Shadowmech88 must be going crazy if one put me into crit with just burn damage as a plasma man

**Comment by SonixApache** [comment]
the obvious answer is to remove plasmemes

**Comment by Exxion** [comment]
It happens on `Crossed()`, not `Bump()`
I can't see anything in the code to explain this
@AutismSpider Is it possible there were more than one of them on the tile you stepped on when you took lots of damage? I know it's a silly question, but I have to rule it out.

**Comment by AutismSpider** [comment]
nope just one roomba

**Comment by DamianX** [comment]
This was fixed by adding a cooldown to its attacks.
