### ISSUE TITLE
You can use TK to jump through portals at a distance

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#14810]
#### Description of issue
The other day I had TK clicked a (hand tele)portal in another room(via xray) and was teleported into space

#### Difference between expected and actual behavior
thats not how this works

#### Steps to reproduce 
have TK
Make a portal
walk x tiles away
click portal

**Comment by DamianX** [comment]
Also works with the weight lifting machines. As long as you have one in your vision and you have TK you can teleport to it.
