### ISSUE TITLE
FUCKING SUPERMATTER

### ISSUE THREAD

**Issue by Riekland** [vgstation-coders/vgstation13#14858]
WHAT THE FUCK IS THIS
![fuck](https://cloud.githubusercontent.com/assets/9220789/26179321/f2a7802a-3b5a-11e7-8929-9c83d5c68935.png)
IT WAS AGREED AFTER SEVERAL AUTISMAL THREADS THAT THE CASCADE WOULD BE THE PLAIN BLUE SQUARE
THE FUCK IS THIS
FIX IT

**Comment by BobdaBiscuit** [comment]
I have no idea how this won cause it's so fucking ugly.

**Comment by clusterfack** [comment]
There was a poll and the plain blue lost. This was the compromise sprite between the plain blue and yellow sprites.

**Comment by Riekland** [comment]
IT DIDNT WIN
It was fucking conceded that it was shit and the plain blue was better
the only way I can see this as having happened is either some faggot changed it 4noraisin, it was never changed to the blue square like it should have been 4noraisin, or the cunt that made that one new away mission just replaced the supermatter cascade sprite with this for his lakes
if it's the last one fuck you go fix it

**Comment by Riekland** [comment]
FASDIOH[Awffjiasddfjfadf ui[fashudhsahfa\fFHO~AHO~hko#
FUCK YOU CLUSTER
YOU ARE WRONG
WRONG
I HAVE THIS CLEAR IN  MY MIND I WILL BE BACK WITH EVIDENCE FUCK YOU

**Comment by PJB3005** [comment]
Blue corner when.

**Comment by Riekland** [comment]
#13744
here you see no-one wanting it
 #13774
here you see people wanting it and SOMEONE not merging it because they're a stupid fucking faggot cunt that can't get his cock out his ass
fuck you

**Comment by Riekland** [comment]
oh
oh wait
I'm fucking retarded I just saw the poll
ignore me I suck cock
