### ISSUE TITLE
Bagel Cargo (primarily belts)

### ISSUE THREAD

**Issue by Aquaes** [vgstation-coders/vgstation13#14884]
The loading/unloading belts in cargo both load off the shuttle, instead of one loading on, and the other loading off like on every other map. I assume this is unintentional.

While I'm at it, and because I have no idea where else to put them beyond getting them lost in thread, I might as well mention a couple of minor problems with the cargo. The lack of a monitor displaying shuttle status is kind of a pain; the delivery chute leading to the mail section runs around the whole loop of the station before dropoff, making it rather pointless when the mail room door is a whole two tiles away; and shutters on the cargo ship but none stationside is pretty useless. Those are all minor gripes though.

**Comment by CptWad** [comment]
the fuck? Whatever maybe convrdirection is the culprit
