### ISSUE TITLE
Chef RAM-say says nothing

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#14897]
The last few rounds on donut RAMsay has been quiet, quite disappointing really. Not sure if its a spawning issue at round start or if the thing itself is bugged

**Comment by Kurfursten** [comment]
I also witnessed this many hours ago, probably a different round, no explanation

**Comment by jknpj** [comment]
Wait, does bagel has a mapped ramsay? Well, unless emagged they only talk if it sees shit food.
