### ISSUE TITLE
bagel RCD in eva and camera name

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#14907]
![mourge](https://cloud.githubusercontent.com/assets/25067478/26228070/b67f2e18-3c36-11e7-8134-3e3fd6dafc43.png)

Camera name for morgue is misspelled.

![rcd](https://cloud.githubusercontent.com/assets/25067478/26228071/bd8b11d6-3c36-11e7-832b-928f7c121e08.png)

The RCD in bagel EVA doesnt work. Doesnt allow for deconstruction or construction.

**Comment by Kurfursten** [comment]
Needs to be a /obj/item/device/rcd/matter rather than just /obj/item/device/rcd
