### ISSUE TITLE
[Bagel] Missing board and camera typos

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#15105]
Chief Medical Officer and Chief Engineer room cameras are mispelled.

![](http://i.imgur.com/kIEdglr.png)

Robotics console board is missing from tech storage.

**Comment by JustSumBody** [comment]
Are you sure it's actually missing the boards?
I'm pretty sure they're all just stacked on the same spot of the rack unlike the other stations where they're slightly offset, so you wouldn't be able to see them from the cameras.

**Comment by Diavill** [comment]
Nah, checked as an observer, no robotics board to be found.

**Comment by CptWad** [comment]
![image](https://cloud.githubusercontent.com/assets/3959840/26736665/f069e76c-477b-11e7-9978-98cae756ecd8.png)

**Comment by CptWad** [comment]
![image](https://cloud.githubusercontent.com/assets/3959840/26736750/528ff6f2-477c-11e7-8526-0c22935cad2f.png)
there fixed it for muh pr

**Comment by Diavill** [comment]
oh shid I never thought to look on the table, my bad

**Comment by Shadowmech88** [comment]
Fixed by #15352.
