### ISSUE TITLE
Rounds having trouble ending properly

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#15171]
So a few rounds now I have had to use the magic admin buttons to restart rounds, Once after a delay (delay was ended, no restart, various buttons were pressed till I use the secret coder one) and another after a regular round end where I saw that a restart command did nothing so I just jumped to gun
Before this happened occasionally and restart commands would work (not the secret coder one, would not have to be used) but now if admins cant force restart rounds Im gonna make a point of it

Edit: Should mention that I have no idea why this happens

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
Might want to specify what parts of round end DO happen.
 - Does the shuttle arrive at centcomm?
 - Does the round end report show?
 - Does the map vote start and end properly?
 - Does the server do everything *except* restart?

**Comment by SonixApache** [comment]
- yes
- yes, after a while
- yes
- I think the black box data got written and then nothing happened but i'm not 100% on it

**Comment by gbasood** [comment]
hi yes close this
