### ISSUE TITLE
ZAS machine broke

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#15216]
![atmos machine broke](https://user-images.githubusercontent.com/3959840/27104359-d8a881c4-5040-11e7-9217-03d1aea5b5e6.png)
I was walking towards my workstation when I saw this and for whatever reason walked into it
I was knocked over without any prompts (just lmao you are on the floor and cant do anything)
It wasnt until a fire in another area came by to set off the firedoors but the gasses were just uh
there
The tiles above me were completely fine and ok

**Comment by gbasood** [comment]
needs some way to reproduce
possible there's runtime logs to go with this

**Comment by CptWad** [comment]
Its happened _before_ but this was so good of an example I just snagged it

**Comment by Exxion** [comment]
For reasons I don't know *at all*, sometimes edges just... fail to form.
It's pretty rare and completely unpredictable.

**Comment by Exxion** [comment]
#7757 is probably the same issue, but I don't have any way to prove it

**Comment by FudgePucker** [comment]
Atmospherics is magical.
Sometimes shit like this happens for no reason.

**Comment by Intigracy** [comment]
I've experienced this before when trying to flood the station with one room as the starting point, bolting open doors / smashing windows along the way

**Comment by Exxion** [comment]
Has anyone seen this happen since #15313? I have no particular reason to believe that would have fixed it, but lolwhoknows
