### ISSUE TITLE
Hijack objective for cult should sometimes replace summon objective, this time through not-in-game-bug-report

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#15222]
So. Continuing from #15219 

If you require a majority of shuttle occupants composed of at least 9 people on the shuttle for the "hijack" to be considered successful, then it shouldn't really be encouraging a revoluniation, setting aside the main problem with rev (and the supply slip no longer producing Cult Armour). Sure it's good to kill noncultists if you need to steal the shuttle, but it's also good to kill noncultists if you need to summon so you can turn them into constructs and all that noise.

Anyway, this "issue" is mostly inspired by various cult rounds where people outright refuse to come to the summon or help you bring them to it. It's a little enervating to get 9 wankers in a circle when it hurts noticeably to summon them to you, and some of them can outright spite the cult by sprinting away from the circle for some tenuous reason that provides plausible deniability against nigging over their pals. If the cult has seized control, sometimes (a lot of the time) I just want to call it a day instead of having to huddle up.

**Comment by Exxion** [comment]
If someone doesn't come to the summoning and there aren't enough people already there (and they are capable of getting there) just antagban them
If they get there then run away, REALLY antagban them

**Comment by SonixApache** [comment]
Grey McShirt [Common]: "IT'S TDM"

**Comment by Allspice** [comment]
A religion dedicated to Nar-Sie, the GEOMETER OF BLOOD, maybe killing a few people and seizing control of the vacationary shuttle to disseminate through more NanoTrasen stations to spread the Good News

seems pretty culty to me.

**Comment by SonixApache** [comment]
if it's stealth cult they'll try to call the shuttle  and it'll just become heist/rev 3.0
if it's loud cult it becomes asymmetric TDM, even more so than it already is

I feel like summoning the blood god is an appropriate apex to the whole thing.

**Comment by Killette2** [comment]
Why dumb down cult instead of smart up our playerbase?

**Comment by Allspice** [comment]
I do try to smarten up cultists.

Anyway, the Hell Rising event holds no especial significance for me compared to just booking it on the shuttle—And I believe some others feel that way too, considering how it was recentlyish reduced in length by almost half. But if you want to look at it from a gameplay perspective, seizing the shuttle with at least 9 cultists would require some marginal finesse, particularly if the crew's on alert regarding the cult, whereas the cultists can backdoor a win with the summon even if sec is fully geared out and ready to gun down some assholes. Neither is strictly better than another from a "fun" metric I suppose (but a showdown would be more interesting in my eyes than a huddle).

Anyway, I'l stiilllll not seeing how a second ending option would encourage TDM given 1. Unlike cult, rev encourages slightly different strategies considering that 2/3 of the station might as well start the shift revved; and 2. The final objective would remain unknown to the cultists until they complete the preceding objectives.

**Comment by Kurfursten** [comment]
Cult completely revamped, reopen if you still care
