### ISSUE TITLE
Is the scanner not supposed to work all the time?

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#15238]
For the longest time I have been convinced that the scanner was only supposed to pick up on some things but this is ridiculous 
![image](https://user-images.githubusercontent.com/3959840/27254855-480a2f92-5346-11e7-8ccb-5914e3faa477.png)
\>Watch someone **without** insulated gloves hack a door
\>They fuck off and I scan
\>NOTHING
\>Later find door hacked open
\>Scan
\>STILL NOTHING
I am entirely sure people are supposed to leave at least fibers on shit they hack. 
I have also noticed over time that less and less prints are actually found and you usually just find fibers but if there's no evidence being left behind now it's pretty awful

Edit: I should also make clear that most of the time the fibers I do find are my own which is annoying

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by CptWad** [comment]
Some further testing suggests that using tools on doors leaves no evidence (emag, regular hacking) when they REALLY SHOULD at least walking through the door used to mean you would get clothes fibers in it so now theres no detective way of finding out who emagged something or hacked into something
Clicking or walking into a door will put the fibers and fingerprints on there but nothing else

**Comment by SonixApache** [comment]
time to add metal scratching from [tool] and DNA to hair fibers

**Comment by Exxion** [comment]
You fool. You'll just make all the powergamers bald again.

**Comment by SonixApache** [comment]
arm hairs, chest hair, nose hairs, ear hairs, bear hairs, there's hair everywhere
or just skin flakes or sweat, shit like that

**Comment by CptWad** [comment]
"Human Particulates"

**Comment by SonixApache** [comment]
We should probably just start by raising the chance of stuff leaving fibers and whatnot.

**Comment by Blithering** [comment]
Ruin everyone's day, give all multitools serial numbers that register when you pulse a wire, and can be scanned. Then give guns serial numbers that can be filed off with a chisel
