### ISSUE TITLE
Should I maintain mini, bus and/or taxi?

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#15444]
These maps STILL get cleaned on the map cleaner and since nobody maintains them I wonder if any of them are worth it
😕 for taxi
🎉 for mini
😆 for bus
👎 for none

**Comment by ihadtoregisterforthis** [comment]
Bus needs something closer to finishing than maintenance.
Mini never saw the light of day.
Taxi did nothing wrong.

**Comment by Unknown-as-Captain** [comment]
Let dead memes lie.

**Comment by SarahJohnson489** [comment]
They aren't worth maintaining. Taxi, mini, and bus suffer from that for lowpop maps they're poorly equipped and lack space for autism projects which is one of the main benefits of a lowpop map to the point that they'd need a complete overhaul.

Don't delete them though or at least stuff them in a branch for easy recovery, others can revisit them if they want for events and it wont become a lost map like so many older maps.

**Comment by kilozombie** [comment]
Taxi is the base of snowmap for what that's worth. I think if it does come back, it's not going to come back in any capacity that maintaining it will have an effect on.

**Comment by IAGFPRMF** [comment]
I actually miss Taxi.

**Comment by Lokiamis** [comment]
individual map cleaners when

**Comment by SonixApache** [comment]
fuck bus and taxi

telestation when

**Comment by gbasood** [comment]
I think he's complaining about map cleaner running on every map when you only changed one

**Comment by gbasood** [comment]
Man people sure do have short memories as to why we removed taxi from rotation huh

**Comment by RealestEstate** [comment]
where is berlinstation?

**Comment by gbasood** [comment]
when you map it

**Comment by RealestEstate** [comment]
it was already mapped though. it was a grand map at that, too. I didn't see this list of inferior maps.

**Comment by SarahJohnson489** [comment]
He means the map nexis ran for a bunch of event rounds. It was a box that was badly damaged but remained more functional than just hitting the station with a 0,0,225,0. One day it just wasn't there

**Comment by RealestEstate** [comment]
not quite, it was box but with a massive wall dividing west and east. there was a checkpoint like airlock on the southside of the wall that was actually kinda neat despite it being a ironic meme map. it must have been deleted from the code.

**Comment by gbasood** [comment]
https://github.com/vgstation-coders/vgstation13/search?q=berlin&type=Commits&utf8=%E2%9C%93

You could cherry pick it out of the commit before it got removed and rebuild it if you want I guess

**Comment by SarahJohnson489** [comment]
IIRC, the wall was just admins delaying start and dropping that stuff with build mode.

**Comment by CptWad** [comment]
It looks like people want mini and taxi back
since packed will just end up the new mini I can probably just make taxi up to date then purge the other two from the map cleaner

**Comment by gbasood** [comment]
2 years later
close it
