### ISSUE TITLE
Beepsky issue?

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#15478]
Alright so
When you turn off beepskys auto patrol
then you drag him around
he will work ONCE
he will see a wanted person and go for them
Regardless of success (or due to failure) he will then not work again in this way
Dragging him around will have him YELL at wanted persons but will not run for them
Wonky ass bot code but this has existed  for a while

**Comment by FudgePucker** [comment]
Another thing to implement that will never get done?
It will go on the pile next to antag datums

**Comment by Exxion** [comment]
@FudgePucker ?????????

**Comment by FudgePucker** [comment]
Bot datums never got done right?

**Comment by Exxion** [comment]
I don't think bot datums were ever a thing
But this is a bug report
