### ISSUE TITLE
>The Bees are stinging the Bees!

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#15554]
![image](https://user-images.githubusercontent.com/3959840/28742715-460f6132-73ec-11e7-80b0-51d5851373d2.png)

**Comment by Kurfursten** [comment]
Animals never fought a war. Who are the **real** animals?

**Comment by DeityLink** [comment]
Not a bug, intended behaviour

**Comment by Exxion** [comment]
But why

**Comment by DeityLink** [comment]
Angry bees will attack bees from other apiaries.

I'm considering only letting them do that if their toxicity is too high

**Comment by Kurfursten** [comment]
Technically bees aren't "true bugs", but that's a less funny punchline

**Comment by N3X15** [comment]
Yeah, or make the message happen on a cooldown.  Or both.
