### ISSUE TITLE
Cap Grammar Again

### ISSUE THREAD

**Issue by Riekland** [vgstation-coders/vgstation13#15590]
Security caps still have the description "It's baseball hat in a tasteful red colour", except now it uses something other than the Queen's English "It's baseball hat in a tasteful red color"
It SHOULD have an "a" in between "It's" and "baseball" but SOMEONE thought I was complaining about the u's being in there like they should have been and not the missing "a"
Reverting it to "colour" instead of "color" would be magical but I'm assuming the server's supposed to use American """""English"""""
I tried to fix this myself but I need moar tiem to not fuck up horribly with git

**Comment by SonixApache** [comment]
there were not one, but TWO missing 'a's!
