### ISSUE TITLE
AIs on cards start dying from lack of power in areas with drained or nonexistent APCs.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#15595]
This is silly.

**Comment by Blithering** [comment]
sounds fine to me, AIs gotta be powered by something

**Comment by SonixApache** [comment]
how about the card's internal power supply instead of magical area power conversion

**Comment by Blithering** [comment]
Maybe have the power be from an internal source when wireless interaction is disabled, as a sort of low power mode?

**Comment by gbasood** [comment]
I call this a bug and say it should go back to its original behavior of just not consuming power when carded
