### ISSUE TITLE
Game dies if a marauder runs into a borg

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#15604]
right on the tin

**Comment by Aurx** [comment]
Borgs clearly OP please nerf.

**Comment by CptWad** [comment]
![1501564743125](https://user-images.githubusercontent.com/3959840/28810597-6d17b6bc-763f-11e7-8724-263d0587410a.png)

**Comment by MadmanMartian** [comment]
I've been trying to reproduce this; Seems it crashes if the borg has modules active (Like, a taser equipped)

**Comment by DeityLink** [comment]
on it

**Comment by MadmanMartian** [comment]
After it has collided with a borg that has modules active, it's as if the mecha is thrown infinitely.

So, each time the mech collides into the borg, it is thrown again at the borg, which throws the mecha, which hits the borg, etc.
