### ISSUE TITLE
Light tiles when removed and replaced with floor tiles create a "phantom" sprite

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#15781]
Place light tile, remove light tile, place normal floor tile and receive light tile sprite weirdly superimposed on floor tile. 

![light tiles r weird](https://user-images.githubusercontent.com/25067478/29492463-99e7ea80-857c-11e7-9b37-2230f54aeb14.png)

**Comment by Knightkiller11** [comment]
Related to this: #15386 
Though that does lead to the possibility that the Foam Extinguisher Issue and the Light Tile issue are seperate in their cause, assuming that you constructed the tiles in a predefined room

**Comment by Diavill** [comment]
Yep, the room in question is the mechanics office
