### ISSUE TITLE
Slimes are faster than a kenyan with the speedforce

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#15802]
I was killed by one in this last round and I am now making an issue in rage

but no really they have no speed limit and just go as fast as possible
which makes no sense for something with no traction or ability to create enough force to go at that speed
muh realism

**Comment by AI-is-rogue** [comment]
phazon
slimes

**Comment by Commandersand** [comment]
aren't they just as fast as humans?
if it was a phazon slime get rekt

**Comment by DrSnips** [comment]
Phazon lmao. Yeah, phazon allows you to surpass limits.
I could go on about different slime lores to explain it, but I will just say they are like a ball shape and they roll really fast to settle your autism.

**Comment by jknpj** [comment]
Applying phazon to slimes is the new powergaming xenobiology flavor of the month

**Comment by CptWad** [comment]
jesus christ why

**Comment by DrSnips** [comment]
Id blame Chocolatemoose for that, he did it over and over and made it common knowledge by doing it a bunch and now people want their valids too. Most chems work on slimes when injected by other people into them

**Comment by AutismSpider** [comment]
Ask why you can turn a slime into walking smoke bomb of death that shits out acid and lube
