### ISSUE TITLE
Law-update noise doesn't play when laws are uploaded.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#16703]
It apparently works when admins or ion events add laws; I didn't test that, and I didn't test uploading to unslaved borgs. But the noise failed to play when uploading to an AI via freeform on upload, from both the AI and borg's perspective.

**Comment by jknpj** [comment]
I'll look into it

**Comment by DrCelt** [comment]
@jknpj liar

**Comment by jknpj** [comment]
>2 months

Seriously i will do it

**Comment by gbasood** [comment]
**100 bugfixes**
