### ISSUE TITLE
TK lets you crawlaport through walls.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#16767]
1. Get TK (X-ray optional)
2. Rest
3. Click on any tile that's in line vertically or horizontally with your character
4. Woop zoop you're there
5. Terminal levels of fune

**Comment by Kurfursten** [comment]
Potentially able to be combined with wine cellar vault to reach centcomm and, by extension, all the loot

**Comment by jknpj** [comment]
another proof that TK is mistake

**Comment by Killette2** [comment]
you mean crawling

**Comment by Aurx** [comment]
Joke's on you two, both are mistakes
