### ISSUE TITLE
Tag Mode

### ISSUE THREAD

**Issue by N3X15** [vgstation-coders/vgstation13#170]
Implement Tag Mode:
- Everyone starts as a Mime
- One is actually a clown dressed as a mime with changeling powers.
- Clown must absorb as many mimes as possible.
- Whoever kills the clown becomes the clown.

**Comment by clusterfack** [comment]
https://github.com/N3X15/vgstation13/commit/b79cb91f520b25f7560a3e2eef9a5caad60d4a16

**Comment by gbasood** [comment]
so wait is that code in main repo then?

**Comment by clusterfack** [comment]
No its on his fork

**Comment by Exxion** [comment]
Since he's never coming back, let's just steal it

**Comment by PJB3005** [comment]
tbh this issue deserves staying open forever.

**Comment by Exxion** [comment]
God I thought we got rid of that tag

**Comment by IzayaChan** [comment]
bump

**Comment by PJB3005** [comment]
The oldest open issue in the repo...
