### ISSUE TITLE
Rev was a mistake: counts one head as two

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#17030]
shouldnt this shit gamemode start with atleast 3 heads
![image](https://user-images.githubusercontent.com/25067478/34653184-deb4f83a-f3e8-11e7-9fc6-d2b0daa47b12.png)

**Comment by ShiftyRail** [comment]
It is _probably_ related to #16884.

**Comment by ShiftyRail** [comment]
```dm
	for(var/mob/living/carbon/human/player in mob_list)
```
This is terrible, because it checks for things who aren't players, like Monkeyman or NPCS.

**Comment by SGuivenne** [comment]
Wait, does that mean we can get a monkey rev head?

**Comment by ShiftyRail** [comment]
@SGuivenne Thankfully no, because after that he checks for `mind`, which only players can have.
