### ISSUE TITLE
You can soulstone the cultist sacrifice target and brick the cult jecties.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#17173]
I could have sworn that I reported this and the fix was merged some time ago, but I can't find either.
Ideally the soulstoning just fails with a message if it's the sac target some thing some thing antag datums

**Comment by gbasood** [comment]
It took me a min to realize 'jecties' meant objectives

**Comment by DamianX** [comment]
This is the check that's supposed to prevent that https://github.com/vgstation-coders/vgstation13/blob/b13976ddab36a75c99fa89c5bbf6c74bd6b74c2a/code/game/gamemodes/wizard/soulstone.dm#L333

**Comment by gbasood** [comment]
Isn't the sacrifice target supposed to be a literal mob, not a mind?

**Comment by Allspice** [comment]
#16147 related to that, sood.

**Comment by Pathid** [comment]
It's the mind. Say, if the sac target gets borged then they continue to be the target as the borg.

**Comment by gbasood** [comment]
That's a bit silly, honestly

**Comment by DeityLink** [comment]
nah. The mind is the closest thing to a soul in SS13. NarSie wants the soul, not just the flesh.

**Comment by gbasood** [comment]
The problem seems to be that if you soulstone or borg a guy, you can't get the sacrifice objective without re-bodying them.

**Comment by DeityLink** [comment]
you can't properly re-body a soulstoned player, which is why the code is supposed to prevent it. The extra-step of re-bodying a borg was intended as an extra challenge.

**Comment by Pathid** [comment]
Rebodying borgs shouldn't actually be necessary. The sacrifice rune is supposed to work on borgs, also MMIs and intelicards. (I haven't actually tested this, for all I know there's bugs.) Things it's not compatible with are soulstones, shades and constructs.

**Comment by DeityLink** [comment]
Outdated and not applicable to Cult 3.0, since the cult can freely reroll a new target.
