### ISSUE TITLE
Nuke can be melted by Xenomorph acid saliva

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#17438]
#### Description of issue
During a full-on station infestation, CentComm called in a Deathsquad. Said deathsquad managed to plant one nuke...which got melted because a Sentinel licked it. Admins had to spawn another one...which also got melted! A third nuke was spawned in and melted when the timer hit -1 seconds.

#### Difference between expected and actual behavior
I don't think Nukes (AKA the FINAL SOLUTION to round-ending/extending forever antags) should be meltable.

#### Steps to reproduce 
1 - Activate a nuke
2 - Have a Xeno Sentinel use it's corrosive acid on it.
3 - Wait a bit and the nuke will have melted like any other object with sentinel acid on it.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Cockswain** [comment]
Working as unintended.

**Comment by Aurx** [comment]
I don't see how this is an issue.  Kill the bloody xenos instead of letting them vomit on your bomb.  

That said, the fact that it only requires they be next to a thing for a fraction of a second to hork all over it might merit changing.

**Comment by Accipitermaris** [comment]
I remember an Admin, which Admin I do not remember which, once said this:

>Aciding the nuke as a xeno is pretty lame because the nuke is the only "normal" mechanism to end the round when the xenos have assumed control.

I agree with that sentiment, as we don't really have a great means of ending the round without it, so making it acid immune makes sense. Using the last round this happened as an example, the xenos snowballed so hard that we just force ended the round, so there was no map vote or round end screen.

**Comment by Irradiation** [comment]
@Aurx Considering that Xenos can't be stunned and move at warpspeed, along with instantly knocking down anybody with their tackle, only reliable way to prevent a xeno from instantly licking the nuke would be Mech bodyblocking or something similar.

**Comment by Pathid** [comment]
Have a do_after for acid. And maybe have xenos not smash table barricades instantly and stuff.

**Comment by Blithering** [comment]
Blobs can also slap active nukes out of existence, and I'm fairly sure someone enough of a madman could use a TTV to bomb the bomb during ops

**Comment by Pathid** [comment]
Nope. Nukes are immune to both of those. Blob just covers the nuke up.

**Comment by Accipitermaris** [comment]
@Blithering also blob and ops have a roundend screen for when they win/lose though (blob is win/lose/nuke, ops is win/shuttle call)

**Comment by SarahJohnson489** [comment]
Like Aurx and Irradiation said, a little channel for it would be nice. Funnily enough, we've had a fair bit of op/deathsquad situations where it's the squids trying to hold the vault long enough to break the code and set it off and it inevitably gets spit on by one of the slippery sneks just pushing and bumping up to it for a split second then skedaddling off to laugh in :a at us/them. Some day shocked grilles will get more use while the ayys don't know how to counter.

**Comment by Blithering** [comment]
Blob the mode has a round end screen yes, blob the random event keeps going until the entire zlevel is green mass.

**Comment by Accipitermaris** [comment]
true
cant say ive ever seen a blobovermindstended though, id hazard a guess and say that the xenostended "dilemma" is much more common

**Comment by Pathid** [comment]
Since #17414 got merged, xenos should be capable of making the shuttle come themselves, provided somebody didn't make a comms board on the derelict or something. (And provided the admins don't recall it, like what happened in the round referred to in the OP)

**Comment by SarahJohnson489** [comment]
Yeah Accipiter, the event blob doesn't proc quarantine and the first thing done 90% of the time people see overmind is AI call the shuttle.
