### ISSUE TITLE
Ghosts' Re-Enter body is a verb instead of a spell.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#17439]
It's a bit minor, but it seems like a good fit for a spell. Additionally, it'd make astral journey and scrying slightly more convenient to use, since you can just click on a big friendly spell button instead of fiddling with tab menus or manually typing re-en[space] in the lower bar.

**Comment by DamianX** [comment]
Does anyone want to make an icon for this?

**Comment by Kurfursten** [comment]
I should point out that you can click your body as a ghost to re-enter it

**Comment by Killette2** [comment]
But I like typing reenter in the command

**Comment by west3436** [comment]
This is a spell now.
