### ISSUE TITLE
AI can get cuck-cubed into the lobby splash art. IN SPESS.

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#17617]
#### Description of issue
When the round starts, the AI MIGHT spawn on top of the cuck cube. If it tries to move its camera, it will notice that it's now in space, with the Lobby Splash Screen covering the "cuck cube" area. If you decide to move your camera to get back into the middle of the splash screen, you'll be in the "cuck cube" zone.
See pictures for details. You can escape this after a few seconds

 by simply use your (Teleport to core) button on the AI UI at the bottom left. I haven't tried normal "Track player/track camera" to escape it.

#### Difference between expected and actual behavior
Why am I being cuck cubed in spess?

#### Steps to reproduce 
1 - Start as AI
2 - Get lucky?
3 - Notice that you start in your core
4 - Move your camera a bit
5 - You are now on top of the Lobby Splash Screen
6 - If you stand in the middle of it, you are now in the cuck cube.
7 - To fix it, press your (Teleport to core) button at the bottom left of the AI UI.

#### Length of time in which bug has been known to occur
A week or so.

#### Server revision
Game: 2012f79eb32fbaa464aee2929345d2e244ac3180 
Patches: f7b1883a4643b40f0e4c1aa07538e4260810a476 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

![cuckcube ai 1 1](https://user-images.githubusercontent.com/15248411/36647219-527af886-1a50-11e8-8d9e-876516e1bd91.PNG)
![cuckcube ai 1 2](https://user-images.githubusercontent.com/15248411/36647220-52886d40-1a50-11e8-85f1-0e94d9a9edad.PNG)
![capture2](https://user-images.githubusercontent.com/15248411/36647225-59b8a850-1a50-11e8-9ef2-bae999681fad.PNG)
![capture](https://user-images.githubusercontent.com/15248411/36647226-59c515b8-1a50-11e8-8afb-d20575d2c045.PNG)

**Comment by DamianX** [comment]
Could reproduce:
The AI is not, in fact, cubed. The camera is.

**Comment by Irradiation** [comment]
Yeah, my mistake. My CAMERA was cubed and as you can see from the 3rd pic picture, the area north of the cube-zone didn't have static and I was actually able to fly south while having only static to the left & right of my screen. It's like the cuck cube "camera" vision extended forever north & south, but west & east had camera static like they normally do in space.

**Comment by jknpj** [comment]
I know what is making this happen

**Comment by SonixApache** [comment]
Still an issue!
