### ISSUE TITLE
There's no blood bank fridges inside the Bagel & Metaclub medbays

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#17753]
#### Description of issue
Instead of being like the cool kids (Boxstation and DEFF of all maps), Bagel & Metaclub prefer to stack all the available bloodbags...on a table. If the other maps can have blood bank fridges, why can't those have one too? Just replace the bloodbag table with a blood bank and I don't think anyone will complain.

#### Difference between expected and actual behavior
I'm not a big fan of looking for a tiny pixel to alt-click the table tile to find the bloodbag I want...or right-click the bloodbag stack and wait a while for the list of items to appear.

#### Length of time in which bug has been known to occur

Probably forever.

#### Server revision

Game: 05f9b7c6e1c2b4a446f409f94b7b12a7c482b942 
Patches: f7b1883a4643b40f0e4c1aa07538e4260810a476 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
Next time be sure to write 

Fixes https://github.com/vgstation-coders/vgstation13/issues/17753 (or whatever the issues link is)

So it auto closes the issue on merge.

**Comment by Probe1** [comment]
https://github.com/vgstation-coders/vgstation13/pull/17832
