### ISSUE TITLE
Shard delaminations can give you Mysterious Packages with no icon

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#17777]
#### Description of issue
After a shard delamination, I noticed that I now had in my hands a Mysterious Package with an odd icon. I couldn't open it, but I could drop it.

#### Difference between expected and actual behavior
Is this caused by hullucinations happening across the station or is it just a bug?

#### Steps to reproduce 
1 - Be on Boxstation
(Optional?) - Be a Changeling
2 - Have someone delaminate the supermatter shard.
3 - Enjoy your package.

#### Specific information for locating

![capture](https://user-images.githubusercontent.com/15248411/37183128-93453a92-2302-11e8-9f0f-bbb889cc731d.PNG)

#### Length of time in which bug has been known to occur

Who knows

#### Server revision

Game: 1f76a015992ad17d7641e9c88b92262b9170a5cd 
Patches: f7b1883a4643b40f0e4c1aa07538e4260810a476 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [] Issue could be reproduced at least once
- [] Issue could be reproduced by different players
- [] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Aurx** [comment]
Sounds like a hallucination, yeah.

**Comment by Dacendeth** [comment]
Shard explosion made me hallucinate before, likely just that.

**Comment by DamianX** [comment]
Actually, the issue is that the icon doesn't exist anymore so you got that replacement icon.
