### ISSUE TITLE
Infinite arms in 3 easy steps

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#17897]
1. Find the arm belt in the mines
2.  Wear it
3. Quickswap on your mining belt
4. Repeat

![arms](https://i.imgur.com/6FhqXZJ.png)

**Comment by MadmanMartian** [comment]
Quickswaps not calling unequipped then

**Comment by Aurx** [comment]
Didn't we have this exact same issue a while back?

**Comment by Kurfursten** [comment]
We definitely did have this exact issue from the same exact quickswap thing previously

Did the last fix just not work?

**Comment by Kurfursten** [comment]
#16443

 #16482

**Comment by MiniMeatwad** [comment]
still not fixed

**Comment by Probe1** [comment]
/obj/item/red_ribbon_arm
	name = "\improper Red Ribbon Arm"
	desc = "It almost seems as though it's alive."
	icon_state = "red_ribbon_arm"
	w_class = W_CLASS_MEDIUM
	slot_flags = SLOT_BELT

/obj/item/red_ribbon_arm/equipped(mob/living/carbon/human/H, equipped_slot)
	..()
	if(istype(H) && H.get_item_by_slot(slot_belt) == src && equipped_slot != null)
		H.set_hand_amount(H.held_items.len + 1)

/obj/item/red_ribbon_arm/unequipped(mob/living/carbon/human/user, var/from_slot = null)
	..()
	if(from_slot == slot_belt && istype(user))
		user.set_hand_amount(user.held_items.len - 1)

**Comment by Probe1** [comment]
@Shadowmech88
