### ISSUE TITLE
Should Inaprovaline have a lower metabolism rate?

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#18045]
**Refer to #18016 for the original PR and discussion about Inaprovaline.**
_For context, here are some relevant metabolism rates for the chems you'll find in O2 kits and chemistry to stabilize people._
Dexalin metabolism: 0.2 units per tick = 1 unit every 10 seconds.
Dexalin Plus (Dex+) metabolism: 0.2 units per tick = 1 unit every 10 seconds. (Chemistry only)
Inaprovaline metabolism: 0.5 units per tick = 2.5 unit every 10 seconds.
Doctor's Delight (DD) metabolism: 0.4 units per tick = 2 unit every 10 seconds.

Most of you might have opened an O2 First Aid Kit at some point and have noticed that it only contains a 15 units Inaprovaline syringe, along with 4 30 units Dexalin pills and one 5 units DD autoinjector. Currently, Inaprovaline is meant to stabilize a patient who's in critical condition by negating the oxygen loss taken by the critical state. 

Now if you look at the metabolism rates I've mentioned earlier, you'll find that this 15 units syringe of Inaprovaline won't last as long as any of those Dexalin pills. In terms of numbers, the syringe will last 60 seconds while a Dexalin pill will last up to 6 minutes. Generally speaking, the healing chemicals that people commonly use (Dex+,  Antitox, Kelotane/Dermaline & Bicaridine) all have the same metabolism rate of 0.2, presumably for the sake of standardization.

That being said, Inaprovaline isn't as bad as it sounds. While it sucks to have to waste a handful of ticks to inject the 15 units into someone (as opposed to feeding a pill), it does have some useful perks. Namely, it'll negate oxygen loss during critical, provide a decent amount of painkillers along with slowing down internal bleeding to half its speed.

With that in mind, when's the last time you, or somebody else, has used the Inaprovaline syringe over the Dexalin pill & the DD autoinjector to deal with a patient in critical condition when Dexalin+ wasn't an option?

**Comment by Jubisloviu** [comment]
honestly just by putting inaprovaline to have the same metabolism as the other basic chems sounds already great, since anti-tox, dexalin and tricord all work the same way

**Comment by Intigracy** [comment]
stolen from kammerjunk

```
Tbh inaprov is really really shit
A metabolism 250% what normal reagents have only compounds that
I know inaprov is good for internal bleeding, but I really doubt that's why most people who use it use it
And for what most people use it {for}, a reagent that stops losebreath at a metabolism {of} 0.5 is awful
```

```
Crazy high metabolism is usually reserved for things like food (0.4 flat for all food reagents) or things that would encourage validgay if you didn't need very much of it (like holywater)

0.2 is what most reagents already have
Such as: dexalinp
As a crazy random example

0.1u metabolism is stoxin, tramadol, stabilizine, creatine, clotting agent, and coffee
The important one here is stabilizine
It does exactly the healing inaprov does in addition to healing oxyloss and stabilising your body temperature
It's made with ethanol, anti-tox, and chlorine

Barring the internal bleeding slowdown (which I don't think was even considered until Yred brought it up), there's nothing extreme about giving inaprov 0.1 or 0.2
```

**Comment by Irradiation** [comment]
Correct me if I'm wrong, but Stabilizine is only obtained through being put in a Xeno nest and is not in the actual Chemistry Recipes DM.

**Comment by Intigracy** [comment]
Yeah.

**Comment by Probe1** [comment]
This is a better job.  Thank you.

**Comment by nuklearcellphoneg** [comment]
> In terms of numbers, the syringe will last 60 seconds while a Dexalin pill will last up to 6 minutes. 

Inaprovaline helps to treat(honestly, stifle) the cause of the oxygen damage- internal bleeding.

Dexalin treats the symptom,  not the cause. They are inherently different.

**Comment by Dacendeth** [comment]
I see no reason why it shouldnt be 0.2.

**Comment by DrCelt** [comment]
So in 2015, Inaprovaline had a metabolism of 0.1 (0.5*0.2) and now it's 0.5?

**Comment by Pathid** [comment]
@DrCelt Seems like it to me. And then the 60u overdose was taken out instead of simply capping the amount that cloning pods give you.

**Comment by DrCelt** [comment]
Bay's metabolism is also 0.1

As all the evidence seems to suggest that the change to 0.5 is unintended, I think there's a very strong argument for reducing it back to 0.1, or at least 0.2 to standardise it.

**Comment by Intigracy** [comment]
haha dylan putting balance changes in an unrelated PR
