### ISSUE TITLE
Buckshot spread depends on your cursor's distance from you.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#18435]
Not sure if it's a feature, but it's a bit weird that you can have halfway-clustered pellets if you aim at the edge of the screen, but (particularly with point-blank) your pellets will suddenly start going perpendicular to your intended target.

**Comment by Shadowmech88** [comment]
It's not a *feature*, per se, but it's also not unintentional. At the time, the intent was for buckshot pellets to randomly target a 9x9 square around where you were actually trying to target, this results in a narrower cone when the square is farther away.
If someone wants to change it to some kind of angle-based spread calculation instead, feel free.

**Comment by SonixApache** [comment]
highly advanced variable chokes

**Comment by Exxion** [comment]
What happens if a projectile is told to target the same tile it originates from, anyway?

**Comment by Pathid** [comment]
Doing that normally makes all the pellets go into you/the guy on your tile you're point-blank firing at because otherwise the gun won't let you do a ranged attack with no range . Mostly into you so this is a bad idea.

**Comment by Exxion** [comment]
I meant if you shot at an adjacent tile with buckshot, but at your own tile is even more horrifying
360 degree spread
