### ISSUE TITLE
Only one buckshot pellet: gets the point-blank damage bonus; and hits a resting target you click directly.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#18554]
Buckshot pellets are newly instantiated instead of copied from the original pellet.

**Comment by Allspice** [comment]
https://imgur.com/a/32vp3Vo
Nine 10-damage pellets, point-blank supposed to add 30% extra damage.
Testing done with pump-shotgun+buckshot with the standardized-variance patch, since it's the only way I could guarantee all pellets to hit at point-blank and because the relevant code causing this issue is identical. Another couple notable things: The new pellets are only targetting the chest, instead of the head which was targetted for all tests; and combat shotguns don't increase the damage by 50% like they do with slugs.

**Comment by SonixApache** [comment]
>combat shotguns don't increase the damage by 50% like they do with slugs.

Where are you getting this?

**Comment by Allspice** [comment]
Ah, my bad, I thought lethals only did 40 for normal shotguns; they actually do 60 for combat and normal.
