### ISSUE TITLE
Planting a kudzu plant permanently slows the expansion rate of any other kudzu seed planted in the future.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#18690]
Third planted kudzu seed, 130 potency, 2 maturation, carnivorous. 5 full minutes of growing. Plantcuttered once right after planting for a seed. Pretty lackluster.
![Third planted kudzu, 5 minutes' growth](https://i.imgur.com/LYU8w6b.png)

However: This one had identical stats and treatment, but was the first planted kudzu during this round (and had 11 minutes to grow):
![First planted kudzu, 11ish minutes' growth](https://i.imgur.com/qxMYDir.png)

It had longer to grow (since I tested like a retard) but it covers considerably more area than it should with only twice the growing duration. Furthermore, the second picture's kudzu was really lively soon after being planted, whereas the first's kudzu just sorta puttered along for the five minutes.

**Comment by strawberrytan** [comment]
Might be worth testing some more, it's a little RNG but something to consider is that a larger kudzu nest will grow faster than a smaller one because there are more edge tiles for the bigger mass of kudzu to expand to per tick

**Comment by RealestEstate** [comment]
@Hugh , this was that bug I think you were talking about that fricks kudzu.

**Comment by Allspice** [comment]
Test two: First picture planted first, second planted second, third third. All planted, clipped, and given 5 minutes to grow; 130 potency 2 maturation carnivore 1.

![Kudzu 1](https://i.imgur.com/owspyQH.png)

![Kudzu 2](https://i.imgur.com/L8t6O3g.png)

![Kudzu 3](https://i.imgur.com/mpjsi0v.png)

sad trombone noises

**Comment by Unknown-as-Captain** [comment]
Does this also happen if you plant some kudzu, wipe it completely, and plant another?
Could it be related to how many kudzu tiles exist in world?

**Comment by vampirebat74** [comment]
reeeeeeeeeeeeeeeeemove the kudzu tile limit

**Comment by Allspice** [comment]
![kudzu test](https://i.imgur.com/ArVIFyZ.png)

plantbgone spray just nullspaces plantsegments, so they still contribute to hindering kudzu spread.
Furthermore, the number popping up in chat is the current length of plant_queue, which is printed every time /datum/controller/plants/process() is called. The number of plants being processed by plant_queue per is hardcapped to 500. At the start, it'd print every 2-3 seconds, which is consistent with 
`#define PLANT_TICK_TIME 30  // Number of ticks between the plant processor cycling.`
But it started bogging down after the segment count began to increase, slowing down to one print per 12ish second once it got to around 200 segments or so.

I suspect the problem is at https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/hydroponics/seed_controller.dm#L95
sleep(1) for every plant segment processed, and to finish up the process it calls sleep(max(1,(plant_tick_time-processed)))
so, 200 segments being processed would sleep the process for 200*1 + max(1, (30-200)) == 201 of whatever time unit, I'm guessing deciseconds.

**Comment by DamianX** [comment]
Some time ago I rewrote that thing into a proper subsystem but then I didn't want to test it so I just left it there.  ¯\_(ツ)_/¯
It's here if someone wants to salvage it: https://github.com/DamianX/vgstation13/commit/4218f8e5e1ab700b60a2c9cd79ea8ccd461b0168
