### ISSUE TITLE
Cyborg's text indicate that they remove their own cell when somebody else does it.

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#18767]
#### Description of issue
![borg remove own cell](https://user-images.githubusercontent.com/15248411/42417281-39f3dba4-8254-11e8-940e-4058720a5ee3.PNG)

#### Difference between expected and actual behavior
Good to know that a scientist/roboticist fixing me and swapping my cell gave me messages that I removed my own cell.

#### Steps to reproduce 
1 - Decide that you are now a standard borg.
2 - Exercise your god-given right to cell upgrades.
3 - Hey this is fun, look at the picture.

#### Length of time in which bug has been known to occur

Who knows?

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
I'm pretty sure this wasn't the case back when #15117 was added, so I doubt it's my fault.

**Comment by DamianX** [comment]
probably one of @jknpj 's unatomic things

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/pull/18425/files#diff-6661eddb64fb7535b456c302507901dbR992

**Comment by jknpj** [comment]
just change that to to_chat i suppose

**Comment by Pathid** [comment]
@jknpj What was the problem with user.visible_message()?

**Comment by jknpj** [comment]
:man_shrugging: i guess i just inverted the order of those messages by doing that. Oops
