### ISSUE TITLE
CMC Feature Loss Request

### ISSUE THREAD

**Issue by Riekland** [vgstation-coders/vgstation13#18946]
The dynamic map CMC doesn't work

It takes ten seconds to load and often you have to close and reopen it before you get something other than a white screen

The icons are in no way synced properly, they can appear in totally different rooms to where their co-ords tell you they are because of the xbox hueg icons

After maybe four or five uses it just stops taking inputs entirely, giving you white screens, literally nothing happening when you press buttons, not opening, shagging your game and making you reconnect

I can't think of a non-aesthetic upside to the CMC in comparison to the old one other than the switch from typing z level to clicking on a button for it

**Comment by SonixApache** [comment]
I stopped being a CMCjockey because the new one is ass. The old 'map + text' one was a lot nicer.

**Comment by ShiftyRail** [comment]
New holomap CMC has its isssue, but at least, it is responsive.
