### ISSUE TITLE
Surgical switchtool loaded with advanced tools uses default names for them

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#19003]
So the list will say "retractor" and you're supposed to guess that this is in fact the surgical incision manager at a first glance.
Who would do this?

**Comment by Dacendeth** [comment]
I dunno about you but I like it this way because it keeps me from having to memorize different letter shortcuts to quickly switch the switchtool around.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
If we're talking about "saw" vs "plasma saw" then sure, but the best surgery tools actually modify the order of tools on the surgery itself. I start my surgeries with "incision manager" not with "retractor"

Lastly some nerds in science keep putting the surgery tools inside a switchtool and it's not obvious at all that the switchtool has upgrades inside it, you can't tell from the icon, the names, or even the deployed item sprite

**Comment by flagzzzz** [comment]
Something like this?

![option2](https://user-images.githubusercontent.com/18647741/43359686-6acf4d32-9274-11e8-8fcf-77a3f8b23694.JPG)

**Comment by DamianX** [comment]
You could make it "retractor (surgical incision manager)" so that you're both happy.

**Comment by Dacendeth** [comment]
What damian said would be great, get to keep my musclememory shortcuts while gaining the ability to easily identify what parts are upgraded in the switchtool.
