### ISSUE TITLE
Machinery and object layers are both "3" which causes problems with objects being ejected from machinery

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#19064]
Sometimes ejecting an object will put it UNDER the machine it's being ejected from. This can be extremely annoying. Often seen with diskettes and the genetics/cloning consoles, though they are by no means the only case.

**Comment by spoonylove** [comment]
xenobotany machines dropping them is the worst

**Comment by DamianX** [comment]
Would it be okay to have `/obj/machinery/layer = 2.5`?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I don't know. Worth a try?

**Comment by Exxion** [comment]
Yes
Also there's already a report about this but this one is more descriptive
It's 4:30 AM so someone else can find it
Peekaboo crates or something

**Comment by DamianX** [comment]
We fixed those #19059
