### ISSUE TITLE
Every map should have this

### ISSUE THREAD

**Issue by soyconsumer** [vgstation-coders/vgstation13#19204]
![cargo](https://user-images.githubusercontent.com/36347086/43821602-e93943a8-9ae9-11e8-8e2c-cf94ad31b1a0.PNG)

**Comment by brndd** [comment]
Do you mean the pipe into the disposals room?

**Comment by soyconsumer** [comment]
I mean the unloading belt into a chute that leads to the disposals room

**Comment by brndd** [comment]
Ok. I thought about doing that on Roidstation, and guess I'm doing it now.

**Comment by Jeroen52** [comment]
On Box it first goes through the mailroom, if the items going through the mailroom have no tags they'll get sent to disposals.

If they are tagged properly, it'll get sorted and sent to the destination.

**Comment by soyconsumer** [comment]
This isn't really exclusive to Roid
