### ISSUE TITLE
Packed medbay has twice as many firelocks as it should

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#19334]
![dreammaker_2018-08-14_19-28-29](https://user-images.githubusercontent.com/40967382/44122029-6df0bf00-9ff8-11e8-9216-e7c9928e5736.png)
two problems here:
Highlighted in red are the areas where there are NO vents and NO scrubbers meaning the bad air is trapped forever unless manually released
This is a very common problem with packed

And
it's just really fucking annoying trying to navigate through this

**Comment by Accipitermaris** [comment]
thick (packed, if you will) firelocks would fix this

**Comment by Kurfursten** [comment]
Fat firelocks trap air *inside the firelock*

**Comment by Riekland** [comment]
I also complained about this but no-one cared ;^( #18945
