### ISSUE TITLE
that damn pythagoras guy is fucking up diagonal glide_sizes

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#19429]
![](http://mathworld.wolfram.com/images/eps-gif/PythagorassConstant_1000.gif)
glide_size is telling BYOND how many pixels you should visually move each tick
If you're moving diagonally, you need to visually move sqrt(2) as many pixels
So currently if you move diagonally you get jumpy movement since your glide_size is less than it should be

I only see 2 solutions to this:
1) since glide_size is a BYOND thing, maybe there's a BYOND thing to handle this?
2) every single fucking time your glide_size is updated, check if you're moving diagonally and if so multiply it by sqrt(2)

**Comment by Exxion** [comment]
![image](https://user-images.githubusercontent.com/9827785/44443556-4bd1e080-a5a6-11e8-878f-048325091631.png)
![image](https://user-images.githubusercontent.com/9827785/44443574-6441fb00-a5a6-11e8-8464-0cbfb8c2a651.png)

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Holy shit it works perfectly AND looks so fucking smooth
