### ISSUE TITLE
(Datums Changeling) Digital Camouflage does not have a chem-point upkeep.

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#19566]
It claims it uses chemical points to stay active, but it only halts your chemical point regeneration (I did not have rapid chem regeneration when I tested this).

Otherwise works at blocking camera tracking or adding the "repulsively uncanny" description to your mob.

**Comment by MadmanMartian** [comment]
It just consumes at the same rate points are regenerated
