### ISSUE TITLE
(Datums Changeling) Mimic Voice does not work.

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#19565]
Mimic voice claims it continuously uses chemical points to stay active, however:
-It only halts chemical point regeneration (I didn't have rapid regeneration when testing this).
-It does not consume chemical points to keep active.
-It does NOT actually mimic the voice of whoever's name you inputted. You'll still talk with your own voice in normal chat and comms will relay your normal voice.

**Comment by MadmanMartian** [comment]
feexed

**Comment by MadmanMartian** [comment]
- Consumes chems at same rate they're generated
- Consumes chems at same rate they're generated
- Odd.
