### ISSUE TITLE
Ion and other non-numbered AI laws sometimes start with * , and can't be stated.

### ISSUE THREAD

**Issue by RaccoonBro** [vgstation-coders/vgstation13#19604]
If the AI gets an Ion storm law, or some sort of other law that has random characters instead of a number, there's a chance it'll start with an asterisk and the game will assume it's an emote.

![rune](https://user-images.githubusercontent.com/31599083/45128121-4fd73400-b14a-11e8-98ce-4dacba49081b.png)
For example, this law is stated as "*%$@. Law", but the game assumes it's an emote named %$@. and doesn't speak the law.

**Comment by MadmanMartian** [comment]
@ShiftyRail

**Comment by ShiftyRail** [comment]
Ha, that's a good one
