### ISSUE TITLE
Accounts database being down means you can't use your PDA virtual wallet

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#19616]
Tried to buy raisins
Can't because accounts database is down
But wait... I have enough money in my PDA's virtual wallet?
Print money from my PDA using my virtual wallet
Touch the vending machine with the money
It just works

So why did I need the accounts database???

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
My understanding is that the virtual wallet is entirely inside your PDA, given that you can withdraw to your virtual wallet at an ATM, add money to it via your PDA, etc.

**Comment by Blithering** [comment]
I assume the accounts database being down prevents all wireless transactions, necessitating the use of caveman methods like cold hard cash

**Comment by SGuivenne** [comment]
Capitalism is the bug, only through true communist society can we be bug free.

**Comment by MadmanMartian** [comment]
Likely not a bug. You can't use wireless transaction because the vending machine can't access the account it would put the funds in, but using physicaly currency places the money within its internal coin holder?

**Comment by Exxion** [comment]
Yes but how can your PDA access the account to withdraw the money?

**Comment by MadmanMartian** [comment]
How the hell can a PDA print credits?

**Comment by Exxion** [comment]
It has a printer, pf course

**Comment by MadmanMartian** [comment]
How is it not a feature that people have hacked their PDA to make counterfeit credits?

**Comment by Exxion** [comment]
Cryptography

**Comment by MadmanMartian** [comment]
And so we find that credits are in fact cryptocurrency

**Comment by Exxion** [comment]
It sounds funny, but it's the only way the mechanics can be rationalized
It wouldn't work exactly like current cryptocurrencies, since those are decentralized, but the underlying math works either way

**Comment by Blithering** [comment]
blank credit chips that the clown can draw numbers on in crayon when
