### ISSUE TITLE
SME still generates power despite not even being emittered at

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#19766]
![this is fucked](https://user-images.githubusercontent.com/3959840/45931112-d8611d00-bf1d-11e8-993b-61f420037738.png)
Something I noticed last night:
Map was Deff
SME was the only operating engine
In total some GW's of power was being made despite this
I am guessing the shard got moved by zas
probably somewhere is a lack of sanity or borked radiation collectors

**Comment by Kurfursten** [comment]
ZAS movement can cause some strangeness, HOWEVER that shard is still in view range of that rad collector and shards do not need to be actively emittered to produce power once they have been "disturbed" initially. This looks like not a bug to me.
