### ISSUE TITLE
Bagel is ded

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#19795]
rest in peace
What caused the disconnect with datums?

**Comment by DeityLink** [comment]
Some rebase reverted my replacing of all /structure/cult with /structure/cult_legacy .
So the map is flipping its shit over "wtf is a pylon?" "wtf is that table in the Librarian's office?"
It's really easy to fix actually

**Comment by DeityLink** [comment]
A ctrl+h is literally all you need to fix this issue.
