### ISSUE TITLE
Datums Vampire have 0 starting blood, which cucks them out of Glare & Hypnotise

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#19819]
Apparently you need 1 blood to cast Glare, but you ain't got no blood, so no casting that. I hope you like I-CAN'T-BELIEVE-IT'S-NOT-CHLORAL (blocked by chest armor) or tase-n-succ to be able to cast glare.

**Comment by Irradiation** [comment]
@ShiftyRail

**Comment by MadmanMartian** [comment]
Was this an antag change while datums were in development?

**Comment by Irradiation** [comment]
Have a shrug in non-text format to indicate my ignorance regarding the explanation 
![anime smug shrug](https://user-images.githubusercontent.com/15248411/46119436-da0a3980-c1d8-11e8-9427-622427883df9.jpg)

**Comment by MadmanMartian** [comment]
![in_case_of_smug](https://user-images.githubusercontent.com/30557196/46119466-f1f6b300-c202-11e8-9547-b21fc8ebe227.png)

**Comment by Caboozles** [comment]
Wasn't vamp given 10 blood to compensate for no chloral literal ages ago? I know datums have been in development for ages as well, but that seems a little surreal.
