### ISSUE TITLE
Datums Vampire scoreboards don't space out/add a return line between the vampire and its thralls.

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#19816]
See picture
![capture](https://user-images.githubusercontent.com/15248411/46119071-674c8e80-c1d7-11e8-80b4-0748094bff7d.PNG)

**Comment by MadmanMartian** [comment]
somebody forgot a <br>

**Comment by MadmanMartian** [comment]
@ShiftyRail
