### ISSUE TITLE
Clown revhead whatever

### ISSUE THREAD

**Issue by soyconsumer** [vgstation-coders/vgstation13#19847]
I was the roundstart clown and spawned with a flash in my pocket. 
I didn't get any bold text like "You are the revhead", only "The flash in your left pocket will help you to persuade the crew to join your cause." 
I didn't have a blue R above my head and there were no Heads of Staff.
I tried to flash people but thanks to me being clumsy the flash slipped out of my hand 90% of the time. When I flashed someone they didn't get rev'd.
My notes:
![rev](https://user-images.githubusercontent.com/36347086/46217559-9cc1bb00-c342-11e8-9bf7-fff6ccd2262f.PNG)

**Comment by Durgen** [comment]
maybe revhead flashes could be snowflaked to be useable with clumsy

**Comment by RealestEstate** [comment]
are revhead flashes intrinsically different than plain flashes? I thought just having the head rev role is what made you able to convert, regardless of whether or not you use the original starting flash. I could be wrong.

**Comment by jknpj** [comment]
The gamemode wasn't dynamic
