### ISSUE TITLE
jars are pain, I hate

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#19949]
Jars are absolute pain to fill
If you try to pour a beaker inside the beaker goes in
If you try to inject stuff inside the syringe goes in
They don't fit in the chemdispenser
It's like I'm living in a bad infomercial and someone is trying to sell me Jar Tongs

**Comment by Gringonius** [comment]
What's even their purpose?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
You can fill them with 250u chloral and throw it at a xeno

**Comment by SarahJohnson489** [comment]
Supposedly for storing and healing up organs. https://github.com/vgstation-coders/vgstation13/pull/17197
I guess that's nice if the apocalypse happens and we ever get a more PvE survival map together that isn't a fully supplied station and you don't have a cloner, organ printers, fridge/freezer, animal cube source in your pants so you'd actually care about salvaging.
