### ISSUE TITLE
Marauder Helmet Cameras and Syndicate Consoles in general.

### ISSUE THREAD

**Issue by Ragnasal** [vgstation-coders/vgstation13#1996]
Leaving a few bugs or incomplete features.

-Marauder helmets have a camera that can be activated by help intenting your chest with it
-Marauder Helmet cameras currently have no camera system to link up to. It's in the code under SYNDICATE, but no camera systems are able to access it.
Proposed Fix: A new camera console within the skipjack and the Syndicate shuttle with exclusive access to the SYNDICATE camera system.

-Health monitor console on skipjack and syndicate ship does not currently function using the new interface. I have yet to check and see if it lists Syndicate crew members via List setting.

I think that's it for now. Also, Vox crossbows need to be looked at. Locking them into place when drawing back the drawstring is currently impossible. The rod slips out of the bow and it resets.

**Comment by SECBATON-GRIFFON** [comment]
can't find this camera thing on marauders, i think you mean the nukie helmets and bots? practically sounds like a feature request at this point then, since the code for CAMERANET_NUKE exists but nothing checks it
