### ISSUE TITLE
Atmos sprites are fucked

### ISSUE THREAD

**Issue by soyconsumer** [vgstation-coders/vgstation13#20049]
Revision: 3b835ffc88a6bea22274f4498ddcfaed5c89f312 

JUST FUCK MY SHIT UP FAM
![canister](https://user-images.githubusercontent.com/36347086/46671834-217bc700-cbd6-11e8-98b7-df232c6948cf.PNG)

![just](https://user-images.githubusercontent.com/36347086/46671891-4a9c5780-cbd6-11e8-96d8-9a5393a39169.PNG)

**Comment by jknpj** [comment]
byond version?

**Comment by soyconsumer** [comment]
512.1448

**Comment by Exxion** [comment]
What fucking sprites *are* those? I can't figure out where they came from.

**Comment by jknpj** [comment]
Try with 1426 and post results

**Comment by soyconsumer** [comment]
![byond](https://user-images.githubusercontent.com/36347086/46686808-8eed1f00-cbf9-11e8-9920-10f4ad7ba374.PNG)
![pipe](https://user-images.githubusercontent.com/36347086/46686810-91e80f80-cbf9-11e8-9711-c4c5d4b5ad96.PNG)
nope

**Comment by SGuivenne** [comment]
Can verify seeing the sprites on version 512.1450

**Comment by Exxion** [comment]
Yeah there's no reason this would be version-related

**Comment by Exxion** [comment]
@soyconsumer Was the round you reported this the first round in which this happened?

**Comment by Exxion** [comment]
Those are the fucking heat exchanger connection sprites
That's not even the same file
?????

**Comment by soyconsumer** [comment]
I don't know, it was the first round I noticed

**Comment by Exxion** [comment]
OK I see why this is happening
What I *can't* see is why it didn't happen before

**Comment by SGuivenne** [comment]
Welcome to byond

**Comment by Exxion** [comment]
OK apparently Pomf updated the server a couple hours before this was reported
That's probably the culprit
It's an easy fix anyway
