### ISSUE TITLE
Shuttle Seat Sprites

### ISSUE THREAD

**Issue by Riekland** [vgstation-coders/vgstation13#20046]
![rh84hq6h](https://user-images.githubusercontent.com/9220789/46667804-abba3000-cbc2-11e8-9598-293915d893d1.png)

They still look ugly
`1-the three sections are all the same colour which makes them look totally flat, as though you're looking at the seat from dead on instead of 45 degrees above it like the other chairs. The top and bottom parts should be shaded to show that it's not flat
2-the armrest in the foreground is way too small compared to the other one consider how big the seats are, and they're brighter than any other part of the sprite in any direction which makes them really stand out badly
3-the U shape of the metal frame is shaded in a way that shows it wrapping around the whole of the chair at the front, with no variation in depth visible - there's shading, but it's nowhere near hard enough to make you think it's anything other than light hitting it. It looks like it's totally covering the armrests on both sides
4-except here it's not covering them and has a sharp drop in height which isn't readily visible on the down facing sprite`
Additionally the "legs" are just a jumble of pixels with no real form to them, and the big command chair's back armrest is xbox hueg for no reason

**Comment by DeityLink** [comment]
Those are sensible remarks, I'll do a pass on them in November.

**Comment by DeityLink** [comment]
Well if anyone else wants to do a pass on them they are welcome. I'm sure they can be improved but I don't have time to do it, and it doesn't seem like anyone else has enough of a problem with them to do it.
