### ISSUE TITLE
Atmos sprites are totally fixed bro!!

### ISSUE THREAD

**Issue by soyconsumer** [vgstation-coders/vgstation13#20075]
![gunked](https://user-images.githubusercontent.com/36347086/46724436-4d508880-cc7a-11e8-8ec7-4dbb335b74c6.PNG)
^
passive vent

**Comment by Exxion** [comment]
Guess that BYOND bug went deeper than I thought
Looks like the fix fixed this part too, though
This'll be fixed when Pomf updates to >=512.1453
