### ISSUE TITLE
Massive amounts of lag can be caused by very large amounts of pipes

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#20097]
Basically I had a player mention how he can griff ghosts through placing a fuckload of pipes
this is due to the fact that the RPD has nothing that stops it from doing so
I guess prevent Rpd use on a tile when more than 25 pipes are on that tile (least the unsecured ones)
edit: Steps to reproduce
1. Get rpd
2. spamclick the floor with pipes
3. do this on a few tiles for some hundred or so pipes each time
4. any ghost flying over has a 50/50 chance of instantly crashing or lagging for a solid few seconds

**Comment by DamianX** [comment]
but then I could just ![image](https://user-images.githubusercontent.com/6307265/46787463-f315fd00-cd37-11e8-9782-ab5747e595f3.png)

**Comment by ddolll** [comment]
The multiple tiles didn't really make a big difference, the lag seemed to be additive with those.
Getting a big stack on one tile made a much larger difference, having ~2.5k pipes on one tile crashed people when they walked past in the hallway on a previous round.
And yes, conveyor belts seem like the way to go to make this anyway because when the slowdown gets large enough it stops you from placing new pipes quickly.

**Comment by CptWad** [comment]
oh hell fair point
is it the pipes themselves or just a massive tile full of objects in general?

**Comment by Kammerjunk** [comment]
Probably latter, given Oliver's and Killette's botany shenanigans

**Comment by CptWad** [comment]
brain blast
how about a clutter structure
when 50 items all end up on the same tile they form a "clutter" which places all the items inside the structure out of view 
each stack of 50 things upgrades the clutter to a new level with a level 5 (250 items) clutter being just a solid wall of trash
to clear it out you need an empty hand. You tear out the top of the heap, putting one item in your hand and dropping the 49 others on the clutter tile. Clutter cannot be cleared if theres any items on top of it so you actually have to clean it out

**Comment by Killette2** [comment]
I like it

**Comment by ddolll** [comment]
Botany legitimately makes stacks much larger than 50 though, how would clutter interact with plant bags

**Comment by coldcola** [comment]
please test this on the _test_ server

**Comment by MadmanMartian** [comment]
Hyper nuclear option: Make the RPD take matter cartridges

**Comment by soyconsumer** [comment]
Remove the RPD

**Comment by DamianX** [comment]
something something autism projects

**Comment by SonixApache** [comment]
@CptWad matter loafs

**Comment by Exxion** [comment]
This is totally an administrative issue. Just ban people who intentionally lag/crash people.

**Comment by Shadowmech88** [comment]
That's what I said about no-fruit, but we still had to take features out of that.

**Comment by Exxion** [comment]
And it was stupid back then, too

**Comment by CptWad** [comment]
cool but my clutter idea is definitely worth coding

**Comment by Shadowmech88** [comment]
I agree, I think the clutter interaction of piles of items could be neat on its own merits.

**Comment by Exxion** [comment]
If people want it that's fine
But it shouldn't be passed off as a bugfix

**Comment by SGuivenne** [comment]
This, crashing the server may be a rite of passage. However, it is also not something that people should actively try to do, and you need to be a special kind of retarded to believe that spamming pipes wont do that.  

However, this does bring up a problem with things like fish and eggs and such.  It is incredibly easy to get spam loads of that many just by doing autistic shit like running a fish engine.

**Comment by Exxion** [comment]
This crashes clients, not the server

**Comment by Shadowmech88** [comment]
@CptWad make a feature request for your clutter idea.

**Comment by CptWad** [comment]
#20115
