### ISSUE TITLE
Clutter stacks: the best idea

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#20115]
came up in a previous issue
Basically
\>new /structure/ type known as clutter piles
\>When25 items are on the same tile, they automatically  form a clutter
\>Clutter piles are just massive piles of trash that reduce visual taxation by placing it in a single object
\>if another 25 items end up on the tile above the clutter it will level up creating larger piles of crap
\>At 225 total items or level 5 it becomes a solid structure that cannot be moved or walked over
\>to clear clutter piles you click the pile with an open hand taking out an item and placing it in your hand, subracting the level by one and dropping the 24 other items on the tile

**Comment by SonixApache** [comment]
l o a f s

**Comment by CptWad** [comment]
Its not a _turf_ but more like a girder

**Comment by Exxion** [comment]
If someone does want to code this, here's a list of pitfalls to look out for:
* Mob holders
* Projectiles (which are items for some reason)
* Any items which do something when stepped on
* Any items that emit light
* Any items that do anything special when just sitting in the world (facehuggers come to mind) (yes they're items not mobs)
* Any items that can't be picked up (as far as I know, limited to spacepod frame parts and package wrapped crates/lockers, and maybe mech/borg torsos)

Probably not comprehensive, but everything I could think of

**Comment by Ephx1** [comment]
Assemble the banana peel cube

**Comment by SGuivenne** [comment]
How do fish piles and botany potato piles factor in?
