### ISSUE TITLE
any text input that uses stripped_input() allows for characters that runtime with goonchat

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20208]
reproduced with the "·" character but there are probably more
for example: call the shuttle with the justification "ass·blast" and the shuttle notification message will fail to display, showing only "Priority Announcement" and then nothing else

it's time for "BYOND bug or ancient bug that nobody found before?"

**Comment by Exxion** [comment]
Well not *that* ancient considering it's no older than Goonchat
And yes, it's a bug, not a BYOND bug. BYOND isn't involved, except in the obvious way

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I would loose this personally

**Comment by Exxion** [comment]
I'm tired but I think you just want to replace this with `return utf8_sanitize(name, user, max_length)`: https://github.com/vgstation-coders/vgstation13/blob/7d46622d5eef725d331c60a14346fbf9b220ffdd/code/__HELPERS/text.dm#L143

I think that'll also be stricter in general, but who'd even notice?
