### ISSUE TITLE
roidstation and bagelstation z-level2 cause the server to crash when trying to generate a map render

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20256]
Not an issue with other maps

Thankfully it's the only zlevel not displayed in the web renders so it's not necessary but it means you can't use the "All zlevels" setting

**Comment by CptWad** [comment]
is this JUST roid and bagel or all maps?
what could possibly be the culprit?

**Comment by CptWad** [comment]
Either: nullturfs under the escape pods
or perhaps the cultist statue in the wizards den?
these are the only unique things
