### ISSUE TITLE
roidstation (and only roidstation) requires an object tree update before being able to be opened in dreammaker

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20257]
You MUST tick roidstation.dm and then update/recompile before you can open open RoidStation.dmm
This is because of maps/roidstation/areas.dm
Why are those areas separate, anyways?

Strangely this is not the case for deff, which, despite having unique deff-only areas, still works off the bat when opened

**Comment by GeneralVeers25** [comment]
It's probably because I'm a fuckup retard and didn't know what I was doing when I wrote the .dm for Roidstation. The areas that are seperate - and I think the only one that really matters is the Roidstation Morgue - is because I radshielded it but did not want to radshield all morgues on all maps.
