### ISSUE TITLE
Maybe revert "new" roundend sounds

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20251]
Discussion rather than a demand
By "new" roundend sounds I mean all the ones that are not "banging donk" or "apc destroyed"
We've had these for 2 years and a half so that's plenty of time to get used to them, and still I find that the reception to them is not very positive
https://www.strawpoll.me/16659929/r
![firefox_2018-10-16_23-28-55](https://user-images.githubusercontent.com/40967382/47058402-46a2a380-d19b-11e8-8eb3-b2abb0ce8f0d.png)

so maybe we can have a formal discussion or a server poll on them

Additionally the bulk of them were merged in less than 16 hours #9964 which I'm still salty about

**Comment by Intigracy** [comment]
I agree 100%, it's something that's been unique to ss13 that is now washed out by videogame references

**Comment by Irradiation** [comment]
They're alright for diversity, but the classic roundend sounds are definitely more memorable & fun.

**Comment by kilozombie** [comment]
The new ones fucking annihilate my ears

**Comment by ShiftyRail** [comment]
>unironically linking a strawpoll

I like both.

**Comment by Kyunny** [comment]
Does banging donk and apc destroyed not play anymore?
I knew something felt off at roundend.

**Comment by Shadowmech88** [comment]
What if we kept both, but buffed the chances of the originals to play compared to the others?

**Comment by Exxion** [comment]
We *could* do that, but why?

**Comment by Shadowmech88** [comment]
For people who prefer the originals, but would still enjoy hearing the new ones occasionally.

**Comment by Pathid** [comment]
Personally I'd get rid of calamitytrigger.ogg, duckgame.ogg, rayman.ogg, and tfvictory.ogg
Those are the annoying ones. The other new ones are fine.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Also just in case people are getting ideas, character preferences about these are probably not possible since the only way to make a sound keep playing after server shutdown is to send it to the entire server at once.

**Comment by Fruktlimpa** [comment]
Diversity makes them all the more enjoyable when they show up, could probably trim them a bit but having nothing but one or two is going to get old fast.
I really haven't seen anyone before this issue saying they dislike them to such a degree they'd only want the old ones.
Also fuck strawpoll with a sample size of fuck all. Not to mention the question is loaded, there is no option to say you don't mind either way or like both.
If I was forced to pick I'd also say I like the old ones more but I don't mind the new ones either but I can't answer that in the poll.

**Comment by creeperparty568** [comment]
I support the idea of having both with the classics buffed so that we get more variety in our round end sounds and also memery
