### ISSUE TITLE
website renders are outdated get your fresh renders here

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20260]
I Rendered The Maps So You Don't Have To

https://mega.nz/#!9JgHRACS!tRsgUwmLyj9c2lIsBQQaXUs86JdyKpt_-OEQfLbotGY

Yep this is not actually a code issue I'm just making one for visibility

**Comment by SonixApache** [comment]
funny enough, i was going to report this as soon as all the map changes were finished

**Comment by GeneralVeers25** [comment]
and here I had run a map render for Roid only to find out (belatedly) that it wouldn't have included the Atmos changes. So thank you for doing it so I didn't have to. Did you update the website as well?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yes I can't update the website that's the point of making an issue

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Nobody updated them and these are already outdated (though no more outdated than the ones in the website)
