### ISSUE TITLE
pre-spawned bombs cause mustard gas

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20287]
Offending item: /obj/effect/spawner/newbomb
These are the bombs that newcops start with, as well as the syndie bundles, mapped in in some places, etc
They spawn with a pre-filled and pre-heated blasma tank
![dreamseeker_2018-10-18_00-29-41](https://user-images.githubusercontent.com/40967382/47129742-f562e480-d26c-11e8-9724-77c51f827f6d.png)
However this tank is too spicy and exceeds 3000kPa, which causes it to leak a bit as seen above, and that blasma goes straight into the room
this is why test_box arrivals starts flooded

**Comment by Shadowmech88** [comment]
Does this mean the plasma leaks into the nuke ops shuttle as well?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Quite possibly yes but it might not be enough to cause noticeable trouble
I only noticed this because test_box has 6 prespawned bombs in one small room

**Comment by SGuivenne** [comment]
We had this happen during a syndicate death squad where a shuttle started plasmaflooded with 4 bombs in it.
