### ISSUE TITLE
Social experiment: Disable box for a week

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#20312]
<box>
<discussion>
<honk>
You can thank jerkmilder for this.

Disable box for a week to see what happens.

**Comment by Killette2** [comment]
Seething
And I vote roid, leave box alone

**Comment by DamianX** [comment]
Sounds like an admin thing rather than a code thing
or even just a pomf thing

**Comment by Kyunny** [comment]
*stops playing for a week*

**Comment by jknpj** [comment]
>bagel man wants box gone

:thinking:

**Comment by CptWad** [comment]
\>bagel
Roid station would become the defacto box for the week
I miss random weighted votes. Meta got a lot more playtime then
