### ISSUE TITLE
Cult 3.0 megathread

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#20673]
[gamemode]
Well, we got our two rounds of Cult 3.0, so here's a list of what I found/observed/people said/fuck you Duny, etc:

-THERE'S NO GODDAMN WIKI PAGE FOR FUCK SAKE. While I'm fine with having people experiment and learn the gamemode, **nobody (Read: security) had any idea of what to do with bloodstones or what bloodstones actually did.** Admins couldn't even tell ahelping players because the admins didn't even know how shit worked. **This wouldn't be so bad on its own, but making it so only CULTISTS know the win condition is pretty retarded.** Bonus points for that officer that didn't know that deconversions were gone, so he didn't do the safe thing, which is to say, collect valids before things went ploin-shaped.

-When bloodstones get spawned, the crew doesn't get a warning apart from explosion noises and maybe seeing the bloodstones appear if they were nearby. **Could use a text warning, kind of like how everybody knows when a Horrorling shows up.**

-When bloodstones get spawned, **there's no timer or real indication on how long until the summoning happens.** Just an extremely vague amount of blood slowly filling up bloodstones.

-Bloodstones having 1200 fucking HP makes it a FUN time to deal with without guns, as it also spawns Bats, Faithless and occasionally Creatures (Creatures presumably only spawn at the main bloodstone) that will JUST you if you dare engage the bloodstone in melee. Hope you brought 4 entire eguns with you and your buddies, fucko.

-Cultist HUDs and icons seem to block out the HUNGER HUD icon, so cultists couldn't tell that they were famished.

-Epilogue (NarNar gets summoned) also summons **FEATURES** and lags the server to hell and back. It doesn't seem to call the shuttle (I presume this is a WIP).

-Implanted people that get converted don't lose the green implant icon when observed with a SecHUD (to be tested, only one case of this being seen so far).

-Being able to convert implanted people in general is pretty gay, but is passable. The time to convert implanted people is pretty fucking short. It took you longer to deimplant via surgery in cult 2.0 than just plop a guy on the rape-rune and leave them to simmer for a bit while they're permastunned. Up the time to convert please.

-SPS not beeping for conversion happening is...something I guess.

-Until the code for it gets finished, chaplains have been relegated to being nigh-useless. Chaplains no longer are paladins or what-have-you, now they're...holy water whores? 

-I can't commentate on if the Null Rod does anything anymore, but I vaguely heard Deity say in the discord that he was nerfing/buffing its effects regarding runes.

-Since deconversions are gone, the only way to identify a cultist is either by catching him with cult gear or making a rune. Or doing the sort of gay metacheck kind of thing and splashing/force-feeding him with holy water.

-Stun talismans that can be acivated to inflict the AOE effect is pretty gay. At least flashbangs can be resisted, but a cultist popping a stun talisman in his hand can easily get up and chain-stun everybody for longer than a banger-happy secboi ever will.

-I said this was dumb during the coding/design phase and I'll say it again. Pulling ghosts to become cult swords (and soul gems maybe?) with only a 1 minute cooldown with no real cost was a terrible idea balance-wise.

-Upgraded juggernauts are cool and shit, but I have no idea how long is their mech-dash ability cooldown. 

-Sacrifice targets being ANYONE (and not preferably security & Heads like it used to) more or less trivializes the sacrifice objective.

I hereby end my rant/list of stuff/whatever. Post your own hot opinions and cold facts in here.

**Comment by nuklearcellphoneg** [comment]
I was told to post in here.

**Comment by RealestEstate** [comment]
as was I

**Comment by RealestEstate** [comment]
personally not a fan of converting through implants at all, not only does it trivialize converting command and security, but it also bypasses SPS indirectly as a result. I think cult already has a large supply of tools to build up its asshole army to justify not being able to convert through implants (sharding, soul blade, etc), while sec has no way of deconverting besides borging. I think being forced to shard implantees is a small price to pay since sec is forced to borg cultists as it currently stands.

**Comment by Caboozles** [comment]
Borging doesn't work anymore. You can fall dead then shade yourself to cuck Security out of it.

**Comment by Irradiation** [comment]
Oh yeah, and ventcrawling shades sure is a fun thing. Can't keep a fucking cultist dead, even with decapitation anymore.

**Comment by RealestEstate** [comment]
oh yeah you're right I didn't think about that.

**Comment by SGuivenne** [comment]
oh god what the fuck who thought allowing dead cultists to random grief was a good idea.  It absolutely isn't.  

This encourages security to just code red, call in a death squad, and then gun down the entire crew.  Its the only viable playstyle for the current meta.

**Comment by bungofungo** [comment]
autosharding people on conversion if they have their cult preferences set to never kinda sucks

**Comment by Intigracy** [comment]
```
-THERE'S NO GODDAMN WIKI PAGE FOR FUCK SAKE. While I'm fine with having people experiment and learn the gamemode, nobody (Read: security) had any idea of what to do with bloodstones or what bloodstones actually did. Admins couldn't even tell ahelping players because the admins didn't even know how shit worked. This wouldn't be so bad on its own, but making it so only CULTISTS know the win condition is pretty retarded. Bonus points for that officer that didn't know that deconversions were gone, so he didn't do the safe thing, which is to say, collect valids before things went ploin-shaped.
```
It was intentionally merged without the wiki update according to the changelog.

```
-Epilogue (NarNar gets summoned) also summons FEATURES and lags the server to hell and back. It doesn't seem to call the shuttle (I presume this is a WIP).
```
There's code intentionally not calling the shuttle for nu-cult.

```
-Until the code for it gets finished, chaplains have been relegated to being nigh-useless. Chaplains no longer are paladins or what-have-you, now they're...holy water whores?

-I can't commentate on if the Null Rod does anything anymore, but I vaguely heard Deity say in the discord that he was nerfing/buffing its effects regarding runes.
```
There's not a single reference to chaplain in the PR (or null rod) outside of chaplain being restricted from being cultist.


Can't comment on the rest because they're opinions.

**Comment by jknpj** [comment]
The ruleset isn't appearing on discord's round end info

**Comment by ShiftyRail** [comment]
I really don't believe removing implants being a passive way to slow down the cult was a good idea and it seems I'm not alone here.
The only option remaining is being proactive (ie Hitlering everyone) and feeding them holy water and then seeing if their health drops, then beheading and proceeding to the next target.

In Cult 2.0, a converted sec officer was basically a guaranteed win, but it required effort. Now, it seems that we'll be seeing this kind of thing much more often.

**Comment by iFlashYou** [comment]
1) Write the wiki deity

2) Get the crew a warning in form of some big red text

3) Timer would not work

4) Deity probably did not want that a lone assitant with a toolbox can take it down but it should be reduced to 1000hp

5) HUDs randomly break or overlap with the hunger one, even had now that sometimes cult icons dont show up on some constructs

6) Fix this Deity

7) They lose the implant but maybe there is a problem with the sechuds

8) It's not really short, you have to stand there for a extended period of time. With cult 2 you needed to remove the implant via surgey and it took time but if you had all upgraded tools then you could do it in under 30sec., if you were fast enough. So maybe increase the time a bit to convert a implanted person but greatly decrease it when cult gets in the later acts.

9) SPS if for ded and stripped. Dont add more handholding to it, esspecially something that makes no sense.

10) no comment

11) ^

12) Whats the problem here?

13) Oof, did not know that. Stun Talismans are fine as one use stuns, no need for the AOE

14) Up the cooldown, 1min is to short. But readd the charge system for it back: When someone does not get converted and gets ashed then cult should get 1+ charge that they can use to bypass the cooldown for the next ghost.

15) no comment

16) Agree with that

**Comment by DeityLink** [comment]
I woke up less than an hour ago, give me time to soak him all the info from here, the thread, and the Discord, then I'll get to work on making the necessary changes.

**Comment by SGuivenne** [comment]
Please deal with the sharded when dead thing particularly, as is it just encourages security to start holocoastering cult via the crematorium or gibber and that just round ruins for cult in a way not even borging does.

**Comment by DamianX** [comment]
megathreads are stupid

**Comment by SonixApache** [comment]
just make a new megathread for every iteration

**Comment by Allspice** [comment]
could make the shade thing a tattoo

**Comment by Kurfursten** [comment]
I don't like the loyalty implant conversion thing

For one thing we're back to birdcult and even worse seccult. The nice thing about merchants was that if you had one and he was NOT DEAD you could reasonably assume there was no trader rapecave because most people won't deimplant.

**Comment by DeityLink** [comment]
Well implant still guarantee they're not cultists, what's your point?

**Comment by SonixApache** [comment]
From a security perspective, the implant thing is fine. Good way to test, and quick way to identify hostiles.
Captain suddenly doesn't have an implant? Might be a bad guy.
Officer goes off on his own, SPS goes off, but he's right there, but with no implant? Bad guy.
Greyshirt that you implanted and set to [R]eleased suddenly has no implant? Bad guy.
etc etc.

**Comment by SonixApache** [comment]
In my experience so far, with a laser rifle and laser gun, I've been able to solo the stones without any of the creatures even laying a hand on me. Not sure if that's good balance.

**Comment by DeityLink** [comment]
I might buff the bloodstones if the cult still can't manage to spill enough blood in time once they get better.

**Comment by DeityLink** [comment]
Yeah, that's what it does.

**Comment by Injazz** [comment]
>2562
>walk into cult lair
>the sign of the cross starts playing
![cult](https://user-images.githubusercontent.com/43905364/48467351-6e247480-e80a-11e8-9d72-70004354b64f.png)
https://www.youtube.com/watch?v=aoxwjLdNmXc

**Comment by SonixApache** [comment]
swords are OP pls nerf

**Comment by DeityLink** [comment]
Considering most (if not all) of the points in the Issue's OP have since been adressed, I think you should update it @Irradiation , either that or close this issue and open another one if needed.
