### ISSUE TITLE
cult 3 tome popup

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#20708]
it opens up and obscures your screen and steals screen focus whenever you take it out while it is open
but it only confers the improved rune writes while open

it should probably give you a bigger rune-writing brain even while close (preferred) or only popup when it goes from closed to open

**Comment by DeityLink** [comment]
I'll think about it. That's a sensible suggestion.

**Comment by Pathid** [comment]
@DeityLink Maybe have it pop up when examined while open. Consider it at least.

**Comment by DamianX** [comment]
Having to keep the tome window open and click on a spell, then pick an entry from the input() window is terrible UI/UX in my opinion. I would prefer if you could just click a link on the rune's entry in the tome to start drawing it.
