### ISSUE TITLE
Conceal rune/talisman description

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#20718]
> That's a talisman. It is a tiny item.
> A tattered parchment. You feel a dark energy emanating from it.
> This one was imbued with a Conceal rune. Hide runes, blood stains, corpses, structures, and other compromising items. Covers a smaller range than when used from a rune.

> That's a rune.
> A strange collection of symbols drawn in blood.
> It reads: geeri balaq ego. That's a Conceal rune.
> Hide runes, blood stains, corpses, structures, and other compromising items.

It appears that conceal does not hide blood stains or corpses.

**Comment by DeityLink** [comment]
>When you write the description before coding the feature

I usually do that to keep track of what the thing I code is supposed to do, but in this case, I realized that turning blood and corpses invisible would add too many balance issues so I cut it. Forgot to change the description though, I'll change that on the next patch. This week end probably.
