### ISSUE TITLE
staff of change self-sliming + fist = the most broken shit in the game

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20760]
[oversight] [balance]
As a wizard, you can purchase the spell Fist, buy a staff of change, set it to slime people, harm intent pointblank yourself with the staff of change, and become a slime with the Fist spell
Slimes with the Fist spell glomp people at range
Thus, anyone that comes within view of the slime gets instantly turbofucked before they even realize what happened
And you also get all the perks of being a slime like ventcrawl and being immune to lasers etc
And you can target feet to gib them in a split second just as an extra fuck you to anyone foolish enough to try extinguishering you
And you can probably combo this with other spells

As far as I can recall, this is probably the strongest lifeform possible outside adminbus, and wizards can become it in less than 20 seconds after the round starts

**Comment by Caboozles** [comment]
You also can outrange extinguishers and dance in and out of vision. The only way to really die is to make a critical mistake. Nobody can outplay you. You're faster, can tablecrawl, and if you hit science first there's no way for them to make Temp guns to stop you.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
People also die instantly so probably nobody knows you exist until half the station is already dead

**Comment by Exxion** [comment]
Restrict fist to humans, I guess?
I don't really like that solution but I can't think of a better one

**Comment by SonixApache** [comment]
better solution: slimes can't cast spells

**Comment by Killette2** [comment]
Phew, good thing nobody here is pointing out xeno fist. I would lose the next best thing if that happened

Seriously if you're willing to take that gamble without an apprentice to help then good luck rolling hunter buddy. If you roll larva you lose any spells when you evolve

**Comment by Caboozles** [comment]
Xeno fist at least vaguely has threat attached to it in that you can roll poorly, and get shot by lasers (at a range)

**Comment by AutismSpider** [comment]
@Irradiation just soc into a Grue  for the next best thing they have sharp fist and are hulk strong on top of eating dead bodys to heal up

**Comment by SonixApache** [comment]
Maybe human-only is for the best.

**Comment by Killette2** [comment]
Does borg fist even do anything?

**Comment by Caboozles** [comment]
If you're borged you lose all spells and essentially turn into a simple borg anyway. It used to be borging a wizard would literally end the round.

**Comment by AutismSpider** [comment]
@Killette2 you lose all your spells when soc into cyborg funny thing is they can cast fist if admeme gives it to them same with the ai and mommis

**Comment by Pathid** [comment]
Sounds like you guys haven't tried it recently.
