### ISSUE TITLE
How could we make the Robust Softdrinks vending machine more fun/useful?

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20844]
One thing I love about this game is that almost everything has some super secret, super niche use, and almost all the vendors have some form of junk that you can use effectively or just have fun fucking around with.
The soda vendor seems to be the exception. I just can't find anything to do with it. The only thing it does is give you cans, but Groan's Soda also gives you cans and even cheaper.
I'm not saying REE REMOVE IT, but maybe we can work at least a little fun into it?

Some ideas (looking for more):

 - An expensive large soda bottle that, when emptied, doubles as a large beaker? MetaStation already has this in the form of the soviet soda vendor, which actually sells large beakers for 15$
 - Give more uses to basic soda, even super situational ones? Maybe soda makes gremlins hyperactive? Maybe roaches love a certain type of soda? Maybe it makes gas masks yucky and sticky so the Clown can prank shitters?
 - Contraband/coin sodas that have powergay applications? Maybe a drink that has a bit of hyperzine in it? Maybe it sells bleach?
 - Sodas (but not Groan's) have a 1/10 chance of coming with a SURPRISE COUPON!!! inside? Or a novelty soda that has a glowstick inside?

**Comment by DrSnips** [comment]
Bleach/space cleaner "soda" would be a nice contraband item. While giving everything function is nice does it really need it? Its a fluff machine for fluff drinks.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I mean sure but in this game even fluff items have sekrit uses. The coffee and cigarette vendors have marginally fun shit inside. We have a literal fluff laundry room and everything in it has a use.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Brilliant

**Comment by SGuivenne** [comment]
its 200 degrees celsius on the station, we are all melting alive, thank god for the cool and refreshing taste of Dr Gibb.

**Comment by Kurfursten** [comment]
Sodas don't cool you off but I feel like they should, like drinking ice/coldpeppers

**Comment by strawberrytan** [comment]
primary use in my case is a container for welding fuel and IED production, it also has a nice deus ex reference i hope doesn't get removed
