### ISSUE TITLE
Cauldron reagent filling overlay always becomes pure white color

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20858]
Seems like the more different reagents there are in it, the whiter the filling overlay becomes.
![dreamseeker_2018-11-29_01-17-17](https://user-images.githubusercontent.com/40967382/49198990-8f41a500-f374-11e8-814d-86b672df339a.png)
This is full of decidedly un-white things
![dreamseeker_2018-11-29_01-23-19](https://user-images.githubusercontent.com/40967382/49199200-62da5880-f375-11e8-8610-0b652c671524.png)
The resulting color would be
![dreamseeker_2018-11-29_01-23-37](https://user-images.githubusercontent.com/40967382/49199221-708fde00-f375-11e8-8a20-bbf42c9403b4.png)

**Comment by Exxion** [comment]
As far as I can tell, it uses exactly the same code as beakers, so I have no idea why this would happen
