### ISSUE TITLE
credits issues

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20897]
#20333
 - People with no ID who logged off before roundend are shown as "No ID", should say "as themselves" or use job from crew manifest
 - Sound tends to interrupt after a little while
 - Credits often don't play, neither music nor text, which is very strange 
 - ~~Some people report the sound plays twice~~

**Comment by Intigracy** [comment]
could this be causing lobby music to not play on newround

and yes, the secret repo is updated to include the change that resets the credits

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Is it? I have lobby music off so I couldn't tell

**Comment by Intigracy** [comment]
My case was the former, leaving it open.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yeah it just failed to trigger again, the server might wait until everyone has received the soundfile and times out if someone's internet is slow or something
I'll look into it

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
What do you mean by "the music playing on the escape pod was the same sound file"?
You mean the shuttle jukebox sound got turned into curb your enthusiasm?

**Comment by DamianX** [comment]
I think it's just one of the options on the shuttle jukebox.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Oh
Incredible

Well that one can be removed I guess

**Comment by DamianX** [comment]
The shuttle jukebox's music should just stop playing when the credits start.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Should be simple, I'll look into it tomorrow

The curb your enthusiasm song should be removed from the shuttle playlist anyways I think

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
If credits fail to trigger for you now please tell me the exact time it happened here
