### ISSUE TITLE
Nar-Sie needs to layered higher

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#20900]
![dreamseeker_2018-12-03_16-29-15](https://user-images.githubusercontent.com/40967382/49396845-e222b000-f718-11e8-9f97-063ef8986df7.png)

**Comment by Intigracy** [comment]
it may be that those cult objects/mobs are layered too high

**Comment by jknpj** [comment]
Deity told me that swords(maybe other constructs too) are HUD-level
Nar-sie is bellow light-bulb level

**Comment by Intigracy** [comment]
Just put narsie above everything, including the red tint since he's the cause.

**Comment by Exxion** [comment]
Not above the HUD
And why the fuck are swords HUD-level?
