### ISSUE TITLE
The current state of credits and how to fix them

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#21068]
continuation of #20897

Currently credits are semi-broken in that they fail to trigger seemingly randomly and the song cuts out after a while.
This is almost certainly caused by the song being played via world<<.
My intended fix to this was to embed an invisible HTML music player in the credits file pointing to an .mp3 hosted in Pomf's media server. I since discovered that's _exactly_ what jukeboxes already do...
So all that needs to be done is monkey with the already existing mediamanager code to send the roundend song to clients that way, using the WMP method since it's the most compatible and we don't need to control volume.
Problem with that is that I have no access to Pomf's media server, have no idea how to set up one on my own, and so basically can't do any testing at all with this. Because of that, and because of me being very busy lately, this is kind of a discussion/report so other coders can tune in.

**Comment by ShiftyRail** [comment]
```
Currently credits are semi-broken in that they fail to trigger seemingly randomly
```
From experience they fail to trigger if you don't update your `skin.dmf`. I know I have some custom hotkeys in there (mostly because Azerty) and I couldn't see credits until I redownloaded the dmf, and remapped my hotkeys again.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I don't think it's a clientside thing, I put logging and when it fails to trigger it seems to fail for the whole server

**Comment by Exxion** [comment]
http://ss13.moe:3000/Pomf/vgstation-media

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yeah but actually making it work with your listen server requires you to set up the config file with the media key and all that stuff

**Comment by Exxion** [comment]
Yeah
If it doesn't work it's not exactly gamebreaking, so while testing would be nice, it's not really reasonable to expect

**Comment by Exxion** [comment]
Oh also the credits are already an HTML document, right? Can't you just stick an `<audio>` in there?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yeah that was the plan but like I said that's pretty much what jukeboxes do, just fancier

**Comment by Exxion** [comment]
There's not really any point in reusing jukebox code
Honestly think the simple method is better here
