### ISSUE TITLE
[discussion] Ideas to make latejoining better/more appealing?

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#21263]
I realized latejoining has a lot of room for improvement and that improving it would go a long way towards increasing population and making the game more enjoyable.
I planned to code something to do about this, but it's worth having a brainstorm first.

Basically, it boils down to "give the HoP more powers"
### Let the HoP mark job slots as "high priority"
High priority job slots show in red for the latejoining job choices. That's it really, something simple just to show "if you latejoin now you'll have something to do and maybe even be appreciated". Could even go the extra mile and have high-priority latejoiners receive cash or job-related gear/supplies when they spawn.

### Let the HoP free up job slots
So if your detective goes catatonic you can let someone else replace him. Or if you want there to be 3 clowns.
~~Maybe also close job slots?~~

### Out-Of-Game Bulletins
Hear me out on this one: For years you used to be able to read command reports, announcements, and shuttlecall reasons when you were still picking your job in the lobby. It's "kind of" ick, but I don't see anything wrong with giving would-be latejoiners a little non-specific transparency into what's going on in the round to motivate them to join or let them know what job they'd have fun joining as.
My idea was to let Command send a fax to be reviewed by the admins, for example "Engineering personnel is requested to set up power". If the admins approve it, this message is sent straight to the Discord so the filthy l*rkers are tempted to join. Obviously this is a very powerful tool, that's why an admin needs to approve it first to make sure the bulletin doesn't spell out the gamemode or include ick names or is just the all-access clown shitposting into the comms console.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Until we can get people to latejoin the empty departments that ain't gonna get any better

**Comment by Irradiation** [comment]
That said, I'm fine with everything you propose as a mean to convince people that aren't like me to latejoin and help the round. A thing about closing job slots is that unless it's regulated in some way, the following may happen:

1. It's the big gay because people should be able to pick whatever the hell they want, even if it doesn't help the round.
2. Antags/non-antags can go grifferoo/antagerru and outright block jobs from being joined, which would be more or less meta-antaggery and would roll back to point #1.

**Comment by LumpyGiraffes** [comment]
Giving latejoiners more of a chance to join as something with some guaranteed "movement" in the round might help too. Nobody wants to latejoin extended only for it to continue being extended. More latejoin antags are good for this, alerts for what kinds of jobs the station needs are good, I'm sure there's other options.

**Comment by SonixApache** [comment]
HoP freeing up job slots is a long time standing *good idea* that nobody wants to code.

Returning command reports and shuttle call reasons to the lobby would be good IMO. Always kinda suck joining just after "Singulo literally just ate the arrivals shuttle."

I think being able to see the alive/dead count before joining would be nice.
