### ISSUE TITLE
Deafmute rune mutes silicons permanently.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#21363]
I guess mute var doesn't tick down in their life() maybe.

**Comment by Gringonius** [comment]
Nice.

**Comment by jknpj** [comment]
The fact you can use it on silicons is a mistake by itself. They're damn robots.

**Comment by Killette2** [comment]
I think we should remove silicons. Obviously they were badly coded and the cause for all problems in this game along with crawling.

**Comment by Allspice** [comment]
![Deaf talisman](https://i.imgur.com/q9lPaBB.png)

I geus it's one of those "emergent gameplays" or some such.
