### ISSUE TITLE
Grenades fuse time can't actually be set to 3 seconds

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#21430]
[qol][consistency][bugfix][oversight]
#### Description of issue
#21178 lied to us, instead of allowing for a minimum of 3 seconds of fuse time, putting 3 gives you a "too short timer" message, forcing you to use 4 seconds.

#### Difference between expected and actual behavior
For 3 second timers to actually work.

#### Steps to reproduce
1 - Take screwdriver
2 - Take flashbang/emp grenade/etc
3 - Apply screwdriver to grenade
4 - Attempt to set timer to 3 seconds
5 - Cucked.org

#### Length of time in which bug has been known to occur

Ever since #21178 got merged.

**Comment by ShiftyRail** [comment]
You can actually use 3.001

**Comment by Irradiation** [comment]
That's not 3 seconds like we were promised now is it?
