### ISSUE TITLE
Code severely lacks internal documentation on what the initialize() proc does, where it's called, how to use it, and I suspect the things that use it lack consistency on how they use it

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#21504]
Ran into this with #21503

If you try to look up where this proc is defined, all you get is:
`/atom/proc/initialize()
	return`
No comment, no nada. I'll try looking up where it gets called so I can figure out where it comes from... oh whoops there's 500 matches

All I know is that this is similar to `New()` but not actually `New()`? And a lot of things call it in `New()`, many of them with weird weird methods like `sleep()`ing before calling it or only calling it if `ticker` is defined which sounds a lot like oldcode. NONE of those have comments either.

This definitely needs some documentation and potentially some updating.

**Comment by Intigracy** [comment]
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/controllers/subsystem/objects.dm#L20

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
So for example, the things I found that simply call Initialize() in New() without any checks are doing it wrong and it only doesn't show because they're not mapped in anywhere?

**Comment by Intigracy** [comment]
Yes

**Comment by west3436** [comment]
Questions addressed by Intigracy
