### ISSUE TITLE
Round can sometimes somehow end without calling world/Reboot(), and this is why credits fail to work sometimes

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#21529]
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/world.dm#L229
I put a bit of debugging here that should fire every time Reboot() is called, but in the server logs:
http://game.ss13.moe/logs/2019/02-February/02-Saturday.log
Looks like sometimes the round just ends without reboot() ever happening.
I just can't see why this would happen.
Any ideas?

**Comment by boy2mantwicethefam** [comment]
It could be the server skipping a beat due to usual round-end shenanigans or closing too fast and reboot not happening

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
That's an interesting theory
I'll check if the timestamps line up later
Do you know what proc watchdog uses so I could try putting a debug message there?

**Comment by Exxion** [comment]
To actually restart the server, I believe it just kills the process externally or something. But the proc that's called in place of `Reboot()` when the server's ready for an update is `watchdog.signal_ready()`

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Looks like @Exxion was totally right again
