### ISSUE TITLE
Reminder for GeneralVeers25 that Roid doesn't have a Labor Administration Console

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#21591]
Just a reminder for @GeneralVeers25 which can be conveniently closed when fixed
I was going to do it myself but seeing an issue about roid mapping popped up you may appreciate not having to deal with possible conflicts

**Comment by SonixApache** [comment]
where does this 'labor console' go normally

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
HoP's office
