### ISSUE TITLE
Blood and gib icon "effects" aren't very good and don't make much sense and aren't worth the lag

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#21609]
So the reason why blood and gibs are laggy are because they use obnoxious Blend() and ICON_MULTIPLY effects
And the end result of these effects is...
![mspaint_2019-02-08_17-51-30](https://user-images.githubusercontent.com/40967382/52505532-89fda380-2bca-11e9-9ed5-f1a4b1266621.png)
Yeah it just completely rapes any detail they had and makes everything dark red
Not to mention, if we want everything to be detail-less and dark red, why not just have pre-baked dark red blood icons that don't cause ridiculous lag?

**Comment by Exxion** [comment]
What if I told you they don't actually use `blend_mode` at all and *all* of the blending is done serverside through `Blend()`, where it can't even use the GPU and takes orders of magnitude longer than it does on the client?

Also the whole fucking point of using `Blend()` in the first place was to avoid ruining the detail, but I guess someone fucked that up too

**Comment by Exxion** [comment]
Oh and if you mean clientside lag, I thought that was fixed when they stopped making literal thousands of overlays due to shitcode
Does blood still lag the client? My machine is too beefy to have lagged even before that was fixed so I can't exactly check

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Maybe? I don't know. It's kind of a legend at this point.
It does create a brand new icon for every fucking blood effect though. Do 500 identical-yet-separate icons do anything bad?

**Comment by Exxion** [comment]
Probably uses unnecessary amounts of memory, but memory isn't a huge concern anymore
Also uses unnecessary CPU to generate them because serverside icon operations are disgustingly slow
Sending icons might also possibly maybe be related to the BYOND sprite swapping bug, too, but we really don't know for sure

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
So I guess:
1) Bug a shitmin to create 5000 gibs like the good ol' days
2) See if it crashbangs people
And if it doesn't cause noticeable lag, would it be worth it to remove the Blend() calls anyways?

**Comment by Exxion** [comment]
Yeah, since they fail to accomplish their intended job anyway
