### ISSUE TITLE
Goonchat failing to load

### ISSUE THREAD

**Issue by Riekland** [vgstation-coders/vgstation13#21660]
my chat window now does this

https://my.mixtape.moe/gurwvc.png

the "experiencing lag etc." bit flashes on and off, presumably due to the chat refreshing itself trying to load. This issue appeared semi-randomly: I had adjusted my settings for a new PC and the chat stopped autoscrolling, prompting a relog which made the chat die completely. Of note might be that no icons loaded for me even before it all broke, just giving me little squares, and that I can for some reason see priority announcements and round end "please vote" things but not any other message

https://my.mixtape.moe/sfwumn.png

**Comment by ShiftyRail** [comment]
I've had this happen pretty often locally, although never on live server.

**Comment by Riekland** [comment]
please send help i want to play video games (-д-；)

**Comment by Riekland** [comment]
installing internet explorer fixed the problem
why does it use fucking ie 
this might fix it for #21939 too but idk
