### ISSUE TITLE
Malf AIs should be able to recall

### ISSUE THREAD

**Issue by aceedex** [vgstation-coders/vgstation13#22205]
DYNAMIC REEEEE
since malfs dont lock down the station anymore, often enough you put the station at checkmate but the shuttle timer will more often than not beat out your delta timer.

personally I'd like malf AIs to work like they did before but, being able to recall is a good enough bandaid

**Comment by Kurfursten** [comment]
Any law 0 should probably allow this (e.g.: Directive 7-10)

**Comment by Zth--** [comment]
Duplicated
