### ISSUE TITLE
"Make all items look like guns (Traitor revolver)" button is mega broken.

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#22338]
#### Description of issue
[administration]

It turns just about every item sprite in the game into not having an actual sprite, leading to everything being invisible.

#### Difference between expected and actual behavior
To see revolvers everywhere.

#### Steps to reproduce
1 - Be Badmin
2 - Press the button
3 - Regret everything

**Comment by SonixApache** [comment]
From my single VV observation, it does set the `icon` var, but not the `icon_state`.

**Comment by Exxion** [comment]
IIRC it's supposed to set it to an `icon` whose default is the revolver, so `icon_state` doesn't matter
Perhaps another icon that was lost with antag datums? Not sure how that would have happened though
