### ISSUE TITLE
Removing limbs should pass a % of damage tp the chest

### ISSUE THREAD

**Issue by aceedex** [vgstation-coders/vgstation13#22635]
[featurerequest]
I like the application of severing a limb to remove damage like youre a civil war doctor or something but it discourages aiming for limbs  in combat. It should be that getting a limb shot off passes some damage to the chest , getting it hacked off passes a much lower damage, and getting it surgically removed passes on 0 damage

**Comment by SGuivenne** [comment]
The thing is, that still permanently incapacitates the person in question.  Losing a hand or a foot is a serious combat debuff and also can't just be healed like being shot or lasered.  Its worth it in combat to blow peoples limbs off.

**Comment by Cockswain** [comment]
is this coming from the guy who blew my hand off only for my health to stay at 100%?

**Comment by Kitfox88** [comment]
battletech as FUK

**Comment by strawberrytan** [comment]
it is really fun to blow off a leg or both of someone's arms and keep them as a hostage
