### ISSUE TITLE
Box nu-bridge still has a trash compactor

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#22749]
Seems Lazy

**Comment by SirSkeleto** [comment]
it makes escaping hard

**Comment by jknpj** [comment]
It's safer

**Comment by SonixApache** [comment]
why not both tbh

**Comment by Blithering** [comment]
Thing is, there's still the captain's disposal bin three tiles south, which people can easily reroute all of disposals to.

**Comment by Gringonius** [comment]
Keep👏shit👏from👏other👏maps👏out👏of👏box

**Comment by SonixApache** [comment]
you can literally buy trash compactors from cargo

**Comment by Gringonius** [comment]
And there's nothing wrong with that.

**Comment by Probe1** [comment]
I have no idea what you people want here.

**Comment by Blithering** [comment]
We want disposals bins, and personally I want that weird backwards teal chair to go
