### ISSUE TITLE
Syndicate borgs dont have access to the syndicate radio

### ISSUE THREAD

**Issue by aceedex** [vgstation-coders/vgstation13#22921]
Maybe the borg got ioned or something, but the player said he didnt ever hear syndicate radio

**Comment by agentofzog2** [comment]
I was the borg that round. Unless the syndies did not speak at all after leaving the shuttle I did not have access to the syndie channel.

Only had access to common, which was my default channel when speaking. Pretty sure I didn't see the syndie option when checking the syndieborg's radio settings.

**Comment by agentofzog2** [comment]
Some testing later it seems they do have access to the syndicate channel, which means either I accidentally turned it off when opening the radio panel or the problem only happens when real nuke ops summon a borg.

**Comment by jknpj** [comment]
The key is .t
