### ISSUE TITLE
Roundstart nuke ops have their TC count fucked

### ISSUE THREAD

**Issue by aceedex** [vgstation-coders/vgstation13#22920]
I understand penalties to midround ops as those are the gay. however roundstart ops start with 80 TC rather than 100. 
This means that you need to refund shit to get the syndie module, which is fine despite how underwhelming it is, but that also means the mauler is in fact 100% never buyable

**Comment by MadmanMartian** [comment]
I believe that was intended #21828

**Comment by strawberrytan** [comment]
Don't roundstart ops start with bombs on the ship, whereas midround ops do not?

**Comment by jknpj** [comment]
Yes, roundstart ops can buy the mech if they refund all their bombs.

**Comment by aceedex** [comment]
right but, theres 80 TC starting. theres 3 bombs worth 15 refunds each. thats a total of 125 TC, mauler costs 140

**Comment by jknpj** [comment]
Did someone remove one of the bombs? :thinking:

**Comment by aceedex** [comment]
🤷‍♂  its 3 bomb spawners in me local serb

**Comment by jknpj** [comment]
Should just make the mauler cost 125 if this is the case
