### ISSUE TITLE
Wiz spell usage stats for your reading pleasure

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#22949]
In #22832 I posted a list some people found interesting so I did the same for wizards
Upgraded spells are just counted as the base one
There are some false positives slipped in
These are all post blink "nerf"

> Predicted potion bundle: seen in 1 out of 538 wizards
Bundle of glow orbs: seen in 1 out of 538 wizards
Polymorph: seen in 1 out of 538 wizards
Potion bundle: seen in 1 out of 538 wizards
Baleful Mutation: seen in 2 out of 538 wizards
Summon Spares: seen in 2 out of 538 wizards
Poly-Morph: seen in 2 out of 538 wizards
Lay Egg: seen in 2 out of 538 wizards
Feint: seen in 3 out of 538 wizards
Lesser potion bundle: seen in 3 out of 538 wizards
Summon Snowmobile: seen in 3 out of 538 wizards
Butt-Bot's Legacy: seen in 4 out of 538 wizards
Mental Focus: seen in 4 out of 538 wizards
The Elf Curse: seen in 4 out of 538 wizards
Shoe Snatching Scourge: seen in 5 out of 538 wizards
Chain Lightning: seen in 5 out of 538 wizards
Brian Damage: seen in 5 out of 538 wizards
Curse of the Reindeer: seen in 6 out of 538 wizards
Ice Barrage: seen in 6 out of 538 wizards
Crystal Butterfly Knife: seen in 7 out of 538 wizards
Fist: seen in 8 out of 538 wizards
Artificer: seen in 8 out of 538 wizards
Brian Damag: seen in 8 out of 538 wizards
Break Lightbulbs: seen in 9 out of 538 wizards
Lesser predicted potion bundle: seen in 9 out of 538 wizards
Cool object: seen in 12 out of 538 wizards
Spark: seen in 12 out of 538 wizards
Warm object: seen in 12 out of 538 wizards
Clean item: seen in 12 out of 538 wizards
Extinguish: seen in 12 out of 538 wizards
Bloody item: seen in 12 out of 538 wizards
Create mundane temporary trinket: seen in 12 out of 538 wizards
Brain Damage: seen in 15 out of 538 wizards
Flesh to Stone: seen in 18 out of 538 wizards
Soul Stone Bundle: seen in 20 out of 538 wizards
Smoke: seen in 20 out of 538 wizards
phylactery: seen in 20 out of 538 wizards
French Curse: seen in 23 out of 538 wizards
Summon Robes: seen in 23 out of 538 wizards
Shoe Snatching Charm: seen in 24 out of 538 wizards
Staff of Animation: seen in 24 out of 538 wizards
pass the pumpkin: seen in 24 out of 538 wizards
Grease: seen in 25 out of 538 wizards
Forge Arcane Golem: seen in 26 out of 538 wizards
Blind: seen in 27 out of 538 wizards
Projectile Pastry: seen in 30 out of 538 wizards
Forcewall: seen in 31 out of 538 wizards
Disorient: seen in 32 out of 538 wizards
Tone setter - darkness: seen in 33 out of 538 wizards
No Clothes: seen in 36 out of 538 wizards
Ring of Fire: seen in 36 out of 538 wizards
Curse of the Horseman: seen in 37 out of 538 wizards
Unbind: seen in 38 out of 538 wizards
Staff of Necromancy: seen in 38 out of 538 wizards
Pain Mirror: seen in 40 out of 538 wizards
Doppelganger: seen in 43 out of 538 wizards
Mind Transfer: seen in 44 out of 538 wizards
Lightning: seen in 44 out of 538 wizards
Disable Tech: seen in 44 out of 538 wizards
Become Snakes: seen in 46 out of 538 wizards
Bound Object: seen in 46 out of 538 wizards
Cloak of Cloaking: seen in 46 out of 538 wizards
Dimensional Push: seen in 47 out of 538 wizards
Mutate: seen in 47 out of 538 wizards
Scrying Orb: seen in 50 out of 538 wizards
Fire Breath: seen in 51 out of 538 wizards
Butt-Bot's Revenge: seen in 52 out of 538 wizards
Time Stop: seen in 56 out of 538 wizards
Staff of Change: seen in 63 out of 538 wizards
Chariot: seen in 65 out of 538 wizards
The Clown Curse: seen in 67 out of 538 wizards
Teleport: seen in 68 out of 538 wizards
Knock: seen in 77 out of 538 wizards
Spellbook Bundle: seen in 78 out of 538 wizards
Mastercrafted Armor Set: seen in 93 out of 538 wizards
Magic Missile: seen in 115 out of 538 wizards
Fireball: seen in 159 out of 538 wizards
Blink: seen in 201 out of 538 wizards
Ethereal Jaunt: seen in 203 out of 538 wizards

**Comment by Dacendeth** [comment]
what dummy bought glow orbs?
