### ISSUE TITLE
Only asteroid mobs can be pacified, which is intended but bizarre.

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#22957]
That means pillowbugs pacify goliaths around you
But it also means you can bring a cage with 10 carp and 1 pillowbug to the bar, and the carp won't be pacified (but humans will so they can't attack the carp in retaliation)

Why was it specifically made to be like this?

**Comment by Kurfursten** [comment]
Probably to prevent cheesing space vaults and away missions.

**Comment by FudgePucker** [comment]
Using a pillow bug to cheese is innovative though. You act as if simple mobs can be dealt with without cheeze

**Comment by Blithering** [comment]
Pillowbug cheese strat is best against players, bringing one on station during ops was hilarious.
