### ISSUE TITLE
Idea that I will code: Smart caltrops

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#22983]
I'm gonna code this myself but it's worth getting feedback first rather than later

Tator uplink item worth 3 (?) TC, comes with 5 (?) caltrop bundles
Caltrops work like super glass shards, deal 15 damage and stun even through shoes
The caltrops will activate (with sweet red overlays and all) for 5 seconds when someone goes near them. Can't be pulled or picked up while active, don't hurt while inactive.
They will not activate for the person that threw them first. So, the tator is free to backtrack as much as he wants.
Each bundle, when thrown, spreads out into 5 caltrop items in a + pattern, so you can cover a 3-wide hallway easily. You get 25 caltrop items "total", then.

Thoughts?

**Comment by boy2mantwicethefam** [comment]
Neat

**Comment by Irradiation** [comment]
Can you deactivate them if you're the guy who placed them?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Everything is up for discussion but the idea was that they are deactivated by default and only activate for 5 seconds when someone other than the owner gets near them. So if you're the owner they just won't activate for you.

**Comment by Kitfox88** [comment]
So if you wait out the 5 seconds you can pick them up and clear them out?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yeah. I mean you can crawl over lube in less than 5 seconds so it seems fair.

**Comment by Irradiation** [comment]
When active, how are you going to "minesweep" as a non-caltrop-thrower? Pacid? Shooting?

**Comment by DDihanov** [comment]
Can you wash them away somehow or do they stick to the floor?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
They're items, so just move up to it, wait 5 seconds, and pick it up. Unless someone has a better idea

**Comment by GoodG1448** [comment]
I take they can be invis sprayed like any item in the game. How large are the sprites going to be?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Small so I can get away with my total coder art

**Comment by Lunstra** [comment]
This is neat, I like this.

**Comment by yclatious** [comment]
Make them able to be poisonable somehow, maybe via stuff like beaker dipping, and youl get a full support from me.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
If you want to instantly kill someone with cyanide for stepping on a tiny sprite then go do your 30 minutes of xenobotany

**Comment by Kurfursten** [comment]
Bauds... he didn't code it

**Comment by jwhitak** [comment]
Any day now we'll have smart caltrops...

**Comment by west3436** [comment]
(he did not code it)
