### ISSUE TITLE
The Away Mission Depopulation Crisis & Can Something Even Be Done About It?

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#22995]
As part of the observer metaclub, I have noticed an infallible pattern.
When an away mission is loaded by an admin, WITHOUT FAIL 100% OF THE TIME all of Sec + Cap + HoP will immediately fuck off to the away mission (plus half-ish of the rest of the station).
This leaves the main station with the population and radio activity of late 2018 euro hours. But even worse, because it also has an entirely sec-less crew composition AND dynamic will still spawn antags based on the away mission's sec count. So now the station is not only dead as fuck, but also gets easily wiped out by 1 dude and then he calls the shuttle and everyone in the away mission whines because WTF WE AREN'T DONE WITH SNOWPLANET. Rock cooks and everyone is unhappy.
I've seen this happen too many times and it's the exact same thing every time.
Can something even be done about it? Code-wise?

**Comment by Kurfursten** [comment]
It would be trivial to make update_playercounts() count players on an away mission as not alive, sort of like how assassinate objectives consider someone on an away mission dead iirc

Of course since away missions are pure adminbus you could also tell admemes to properly adjust threat and shit when they start planning to lead an event

**Comment by Lokiamis** [comment]
Weird that people want to participate in rare events that happen once every thousand games

**Comment by Kharkov72** [comment]
He's not saying people going through gateways is a bad thing, he's saying it's a bad thing that the round doesn't account that the population is now pretty much evenly split.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Making dynamic account for the split pop would be great (honestly, forcing it to be extended if an away mission is loaded would be best)
But there's also the separate issue that Sec and Command are disproportionately eager to go on away missions compared to other departments, so the remaining crew has a weird and gunky crew/job composition (again, I can't really think of anything to help here other than forcing it to be extended)

**Comment by FudgePucker** [comment]
The best solution would to be to have an away mission available every round.
Sounds insane right? But goon has their much more in depth and massive telescience adventure areas, with super duper great loot in some of them (the biosphere one has a good projectile weapon, and the traitor device scanner in it) and nobody does them every single round, because they have already done them or don't care to do them.

Eventually once the few shitty rounds of everyone storming the gateway happen, then nobody will go to the gateway. If a head or security member blow off their job you can punish them for it, because it isn't a onetime admin bus event, its a common occurrence.

**Comment by Caboozles** [comment]
There was a point in time when a certain coder planned to have the gateway open every round to a random locale.

Is the dream going to finally happen?

**Comment by Kurfursten** [comment]
I could be mistaken, but you're probably thinking of Probe's desire for the gateway to default to the very small snowy cottage mission every shift automatically.

*Most* away missions are totally empty, and the ones that aren't (Wild West, Hive, and Tomb) are quite long and tend to be shift killers, particularly without some centcomm guidance.

**Comment by SonixApache** [comment]
I once loaded an away mission after two or so hours when the crew wanted to leave, and it worked out really well.

We just need some more decent missions.

**Comment by DrSnips** [comment]
I'd say a button that forces extended being in the menu for away missions or a followup prompt after loading one is the best idea.

**Comment by Blithering** [comment]
The long away mission tend to kill the station population, but in a way that's the intended use, they're mini-holidays for when there's nothing left to do on the station. So long as it's implicit that loading an away mission of that type is gonna make it the main focus of the round, there shouldn't be too much of a problem, barring the mebday pile up.

**Comment by Demagogue-Dimension** [comment]
>when you get back from your staycation and singuloose happened
I'd say aye to reducing "player count" by the variable "player count on mission" so this shit doesn't happen.

**Comment by FudgePucker** [comment]
What if you require a fuck ton of power to the gateway for it to open? That way you need a engineering team to hot wire like ten deloreans to the grid to have adventures.

**Comment by Blithering** [comment]
That was already supposed to be a thing, but the designers way back when considered 15000 watts to be a fuck ton.

**Comment by DeityLink** [comment]
> Can something even be done about it? Code-wise?

Crutches can be made but honestly that sounds like more of an admin issue. Now with Extended back they can make use of those to enable away missions.
