### ISSUE TITLE
buttbots + telecomms = consistent server crash

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#23030]
buttbots will repeat any message they hear
including their own message that they just said, if it gets repeated back to them via a radio
literally the only thing preventing this from becoming a server-crashing infinite loop is that they will ignore messages that contain the word "butt" in them
however you can use telecomms to `$content = "honk"` or any sort of script that replaces the word "butt" to remove this single failsafe, and so bringing a buttbot to any intercom or radio will consistently crash the server from instantaneous buttbot feedback loop

**Comment by SonixApache** [comment]
i for one blame goonchat

**Comment by Exxion** [comment]
I guess you can do that if you want to be wrong

**Comment by robintime** [comment]
rest in piece to buttbots
