### ISSUE TITLE
You can abuse canceling the sacrifice target action as cult to create unending cult areas with atmos.

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#23049]
#### Description of issue
I too love the good old days of having ~~manifested ghost~~ space bases on the edge of Z1 that serves as a juggernaut/whatever construct manufacturing plant. See image.

![capture](https://user-images.githubusercontent.com/15248411/58387787-dedef180-7fe2-11e9-895b-cbd0e9097335.PNG)

#### Difference between expected and actual behavior
For the cult wall pocket to only spawn when the sacrifice process is COMPLETE.

#### Steps to reproduce
1 - Be a cultist
2 - Find the sacrifice target
3 - Build an altar in spess on Z1
4 - Drag the target onto the altar and start the sacrifice dance.
5 - As soon as the cult walls & floors spawn, stop the dance.
6 - Build a new altar and repeat step 4-5.
7 - Enjoy having free space bases with atmos.

#### Length of time in which bug has been known to occur

Since cult 3 has existed, according to Deity himself.

[powercreep][balance][gamemode]

**Comment by iFlashYou** [comment]
Silence him

**Comment by Kitfox88** [comment]
cultshitters btfo, nerfs incoming

**Comment by Killette2** [comment]
Looks like a feature to me, ignore this

**Comment by Kharkov72** [comment]
delete this
