### ISSUE TITLE
remove diety you are the worst french

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#23131]
![remove diety](https://user-images.githubusercontent.com/25067478/58838707-c1073180-865f-11e9-9ef3-b527208ca4a3.png)

**Comment by iFlashYou** [comment]
silence him

**Comment by Kurfursten** [comment]
Related to https://github.com/vgstation-coders/vgstation13/issues/23048

**Comment by Cockswain** [comment]
feature
