### ISSUE TITLE
very ugly barricade lighting

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#23232]
![dreamseeker_2019-06-12_14-43-27](https://user-images.githubusercontent.com/40967382/59373641-7b61fd00-8d20-11e9-8343-2e95bda9e3a9.png)

**Comment by Exxion** [comment]
You mean the visibility? That can only be "fixed" through shitty hacks like how one-way windows do it, and cannot be *properly* fixed at all

**Comment by Killette2** [comment]
use your RP and think how you can only barely see through the cracks of the barricades. I love how barricades block light in general and will hate you if you take this away from me

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It's more that "see through the cracks" means one abrupt tile of zero darkness
If you could only see a dimly lit square that blended into the rest of the darkness that'd be perfect

**Comment by Blithering** [comment]
That particular instance could be fixed by putting the barricades on the windows
