### ISSUE TITLE
Novelty idea: Swap gateway room and abandoned office

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#23234]
![firefox_2019-06-12_15-28-55](https://user-images.githubusercontent.com/40967382/59376632-da2a7500-8d26-11e9-8305-1171518c45a7.png)
Abandoned office was once cultbase supreme but it was instead changed to be a "public construction area" with a transparent airlock and more access and all that
However it failed completely at it since it's so out of the way. Other areas like the ex-mechanicoffice and secondary tool storage were much more successful at this since they're more visible and thus desirable.
The gateway room takes up a lot of valuable real estate being something nobody fucking ever uses so it'd make more sense to swap the two around

**Comment by Kharkov72** [comment]
🤔 an interesting idea

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Also noteworthy that in that position and without rwalls to cuck you, abandonedofficeV2 would have room for comfy expansion into Maint for large projects

**Comment by DrSnips** [comment]
That's not EVA. That's the gateway.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I had a brainfart

**Comment by utilitas-** [comment]
It literally was that way already.
Seems to me like you just want oldbox.

**Comment by ancientpower** [comment]
Gateway is very rarely used, abandoned office in that space would be cool for making stuff like a newsroom or mini-departments.

**Comment by Kharkov72** [comment]
@utilitas- nothing wrong with that

**Comment by Kitfox88** [comment]
move the gateway to somewhere near science and escape and have TWO places to build

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
but people would rather build in escape than arrivals

**Comment by FudgePucker** [comment]
Gateway is so unused, why is it even on the station? Why not have a shuttle sent from Centcom that has the gateway on it that admins can send when they have an away mission loaded? It can use the dock that ERT uses, if an ERT is called the gateway shuttle goes back and the ERT shuttle goes in.

Even better idea, but would require more effort; there is no gateway, you use the science/mining/hand built shuttle to go to the away mission, when an away mission is loaded, a destination disk is spawned on the bridge.
