### ISSUE TITLE
Cult sacrifice target should once again be limited to implanted personnel

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#23367]
Just make it be like Cult 2.0 instead of having to sac some fucking random assistant no one will miss

**Comment by ShiftyRail** [comment]
My idea was to switch spray blood and sacrifice with sacrifice being during the bloodstone phase.

I didn't code it because I wasn't sure if it would gather enough support.

**Comment by DeityLink** [comment]
I'm all for sacrifice being weighted toward "important" personnel, but simply having it pick among unconvertable personnel doesn't remove the chance of it just being the IAA or the Chaplain.

**Comment by Blithering** [comment]
Well chaplains can be a risky target due to incense, and IAAs tend to loiter around sec or the bridge, both could be interesting targets in theory

**Comment by Diavill** [comment]
That's fine, I just don't think it's a good objective since saccing an assistant is nowhere near as easy as saccing an officer, the offchance that it's an IAA/Chappy/Clown is gucci
