### ISSUE TITLE
Catbeasts shouldnt have round ending viruses

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#23517]
catbeasts exist so that they can be killed and be something the crew can unite and look forward to beat the shit out off to blow off steam or some shit
now you get giga aids, thanks d*ety
also in general virus shit needs to be toned down because I dont think viruloose is fun or engaging for the crew and only causes malicious anger towards medbay during rounds

**Comment by boy2mantwicethefam** [comment]
hahaha how are diseases real just wear internals hahaha wear gloves

**Comment by Irradiation** [comment]
>Have to wear internals, latex gloves and preferably a hardsuit all round to evade nu-viro memes.

Truly the fashy future.

**Comment by ShiftyRail** [comment]
Catbeast diseases should only be inconviences
Keep in mind this role do not exist to be a threat in itself

**Comment by DeityLink** [comment]
Alright. I'll tone it down.

**Comment by DeityLink** [comment]
For now I'll halve it, we'll see how this pans out #23532 

Also reminder that #23522 is still awaiting merge

**Comment by tuypo1** [comment]
Better idea, make them just take a long time to become contagious so unless the crew drags their feet they won't get sick
Maybe not make them really bad diseases though

**Comment by DeityLink** [comment]
@tuypo1 The entire point was to have the crew equip with sterile gear BEFORE hunting the catbeast but I guess I expected too much of our blood crazed validhunters.

**Comment by tuypo1** [comment]
>The entire point was to have the crew equip with sterile gear BEFORE hunting the catbeast
That's just shitty design
Disease should be a punishment for not killing it not something you have to deal with while killing it.

**Comment by DeityLink** [comment]
Like I said even if you kill them unprotected you have at least 20 minutes to get vaccinated before stage 4 kicks in.
