### ISSUE TITLE
Repeated ghost messages are not combined, can lead to spamming

### ISSUE THREAD

**Issue by RaccoonBro** [vgstation-coders/vgstation13#23792]
![image](https://user-images.githubusercontent.com/31599083/62663765-e443ab00-b946-11e9-9aac-1ae3c1ece413.png)

These messages _do_ get combined if they're a mouse, since the message comes up as "squeaks" instead of the assortment ghosts normally get.

**Comment by Kharkov72** [comment]
that's because of the various groans/spooks/whines/etc

**Comment by DamianX** [comment]
The obvious solution is to not spam macros in deadchat

**Comment by SonixApache** [comment]
this is why dedchet bans exist

**Comment by Probe1** [comment]
To be honest, ahelp it.
