### ISSUE TITLE
Roid bar "wood" tiles and materials

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#24018]
![image](https://user-images.githubusercontent.com/25067478/63882090-93692480-c9d1-11e9-9d90-76bf0f28c93a.png)
The "wood" tiles here are covered by the gold outline. When attempting to screwdriver the wood it doesn't work, when crowbarring it pries off the outline. Now you cannot pry off the actual wood, and instead it functions as if it were plating. You can place any other tile on it but when prying off the new tile the plating still remains as wood. This is a crime to aesthetics.
Also the bar backroom on roid doesn't have a stack of metal and glass, it has exactly 1 (one) glass and metal sheet.

**Comment by Diavill** [comment]
The simplest solution to me looks to just map that shit out

**Comment by RaccoonBro** [comment]
Having the gold stripes as decals for painter sounds nifty tbh

**Comment by Exxion** [comment]
Placing two floors on top of each other in a map file causes BYOND to add one of them as an underlay to the other. This is presumably an obscure feature to make mapping "easier" but in SS13 it only causes grief
