### ISSUE TITLE
The emergency shuttle docking causes a brazilian and chinese alliance DDOS attack

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#24200]
tianenmen square

**Comment by MadmanMartian** [comment]
Can I get more details on that, please?

**Comment by Dacendeth** [comment]
he means the server always lags when the emergency shuttle docks I think.

**Comment by Exxion** [comment]
This was presumably fixed by 61369fa5abffcdb5e27d56acbdc3ba177957b83c
