### ISSUE TITLE
VOX announcements still not announcing in order

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#24491]
As an aside, the text announcement does not look good and I don't like it

**Comment by N3X15** [comment]
Are the words in the text announcement in correct order?

**Comment by Diavill** [comment]
Yes

**Comment by SonixApache** [comment]
the obvious solution is to just `spawn( vox(WORD) ) sleep(0.1) spawn( vox(WORD) ) sleep(0.1)` etc

**Comment by N3X15** [comment]
Yeah, that's basically what I'm trying next.

**Comment by N3X15** [comment]
OK, that caused the sounds not to arrive at all.  I'm not sure I *can* fix it without Lummox's help, at this point.

https://github.com/vgstation-coders/vgstation13/compare/Bleeding-Edge...N3X15:vox-asset-cache?expand=1#diff-7b7c838a45e1624822f53b9c08ba6ae2L310

**Comment by PJB3005** [comment]
Is this fixed now?

**Comment by SonixApache** [comment]
i still heard the same issue with the biohazard warning

**Comment by Zth--** [comment]
_Is this fixed now?_
