### ISSUE TITLE
Relish & Mustard appear to have no recipes that use them, cannot be made

### ISSUE THREAD

**Issue by RaccoonBro** [vgstation-coders/vgstation13#25493]
Relish and Mustard look to have no way to actually use them in a recipe, nor can you make them at all. Seems like a bit of waste, especially considering you can find them in the Exotic Garnishes crate instead of something useful.

**Comment by Kurfursten** [comment]
I warned of this
Stop adding condiment shit and then adding no recipes

**Comment by RaccoonBro** [comment]
Is it worth adding recipes for them? Neither of them really have much uses in making new dishes IRL, it would just be variants on existing recipes like hot dogs. It wouldn't solve the issue that they can't be made either, though adding cucumber wouldn't be a terrible idea (recipes with pickles and the like would be neat) but adding mustard plant seems silly.

**Comment by SGuivenne** [comment]
Chef main here, Mustard can be used in a fair deal of Deli dishes, Jewish Dishes, German Dishes, and Eastern European Dishes.  Relish is a tad more complicated and may not really work as more than a condiment, but honestly ketchup, mustard, and relish should probably get some kind of fast food looking condiment dispensers for placing in public so we can run the Space McDonalds of our dream.

**Comment by SonixApache** [comment]
they're just condiments

**Comment by RaccoonBro** [comment]
If we're gonna add recipes instead of the r-word, what would be good? Stuff like a loaded hot dog or a cuban sandwich would be nice. Adding dispensers like @SGuivenne mentioned would be neat, click on 'em with a burger or fries to add some nutriment

**Comment by FudgePucker** [comment]
I use mustard for BBQ. Slathering it onto your meat adds some spice and helps hold the dry rub. Pulled pork sounds like a good recipe.

Mustard seed would be an interesting plant. Mutation could be a "mustard gas" joke and contain chlorine or bleach.

**Comment by DeityLink** [comment]
mustard is used to make mayo, and all those condiments can now visibly be applied on food items. I deem this issue resolved.
