### ISSUE TITLE
Snaxi - You can use the CE's blueprints to remove the outdoor "room", making the area bright

### ISSUE THREAD

**Issue by RaccoonBro** [vgstation-coders/vgstation13#25498]
See title. Steps to reproduce:

1. Get the CE's blueprints on Snaxi
2. Go out in the snow
3. Use the blueprints to remove the "room" you are in
4. One lag spike later and suddenly the outside is bright as day since it's considered space now.

You can also edit the "room" using the blueprints. You can't build structures in the snow on Snaxi like you can in space on any other station, since it counts as a pre-existing room.

**Comment by Kharkov72** [comment]
feature
you're just turning on the sun

**Comment by deadharold** [comment]
dangerously based

**Comment by PrimeDSS13** [comment]
bro don't tell the coders they'll remove it

**Comment by Kurfursten** [comment]
It was already on my radar, the axe was already coming - along with general reforms to how blueprints work when interacting with 'outside' and also fixing the problem of shuttles (most egregiously the trade shuttle) leaving behind Space Area when they leave.

**Comment by jknpj** [comment]
@Kurfursten how about a giant invisible light emiting object that travels from one side of the map to the other then deletes itself

**Comment by Kurfursten** [comment]
That was the first attempt, it turns out that doesn't work (our light distance caps somewhere around 20)

**Comment by jknpj** [comment]
how about multiple objects then?
