### ISSUE TITLE
The status displays in Cargo aren't set to show the cargo shuttle timer anymore

### ISSUE THREAD

**Issue by RaccoonBro** [vgstation-coders/vgstation13#26602]
[box]
Starts as blank unless you go in and change them manually, someone messed up.

**Comment by RaccoonBro** [comment]
Wasn't an issue a few months ago, but the last few months it hasn't worked

**Comment by SonixApache** [comment]
this is the case on Roid as well, probably safe to assume it's on every map

**Comment by CptWad** [comment]
Is this still an issue?

**Comment by SonixApache** [comment]
don't think so
