### ISSUE TITLE
The bhangmeter shows the Nuke Ops shuttle

### ISSUE THREAD

**Issue by RaccoonBro** [vgstation-coders/vgstation13#26603]
tbf if the nuke ops manage to blow themselves up on their own shuttle they deserve it
![image](https://user-images.githubusercontent.com/31599083/82844864-232ff680-9eb0-11ea-86a2-0029e215e9c1.png)

**Comment by Kharkov72** [comment]
feature

**Comment by SkowronX** [comment]
feature

**Comment by ancientpower** [comment]
not a bug

**Comment by RaccoonBro** [comment]
i've come to understand its important this is never fixed
