### ISSUE TITLE
Non-cultists can see the "Non-cultist" detection pulse generated by a concealed Reveal rune.

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#27083]
[gamemode][bugfix]
#### Description of issue
Like it says on the title. This only works if a Cultist is near the rune (generally in screen range). Note that the visible Cult Pulse effect isn't even near the Reveal rune. It seems to be off-set by where the nearest Cultist is located. **In addition, non-cultist won't see the revealed person, just the cult effect.**

#### Difference between expected and actual behavior
Non-cultist not being able to see that the cultists know that they're there.

#### Steps to reproduce
Conceal a Reveal rune.
Have a cultist nearby in screen range.
Have a non-cultist walk through the (invisible) rune.
Everybody nearby can see the huge red cult pulse through any walls.
Say ":s CULT IN SCIENCE MAINT"

#### Length of time in which bug has been known to occur

Probably ever since the feature was added.

**Comment by DeityLink** [comment]
Is that bug still a thing or is the feature just not used anymore? Considering commenting it out, at least until I rewrite it from scratch.
