### ISSUE TITLE
[Horizon] There are two (2) cameras in the server room

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#27695]
I guess it really NEEDS to be watched.
![Capture](https://user-images.githubusercontent.com/15248411/91671203-a20d7e80-eaf2-11ea-9ae2-7a037cde602f.PNG)

**Comment by 9percents** [comment]
based mapper against MALFs

**Comment by gurfan** [comment]
It's the same way on box

**Comment by DeityLink** [comment]
Pretty sure that's always been a thing.

**Comment by toomykins** [comment]
since cameras randomly fail on roundstart, having a lot of cameras there just reduces the risk of losing control over it. server rooms are pretty important for AI control assertion.
