### ISSUE TITLE
infrared emitter

### ISSUE THREAD

**Issue by AutismSpider** [vgstation-coders/vgstation13#2847]
They do nothing.

They don't work for bombs.(tank transfer  and grenade)

When use for grenades got screwdriver set them off.

**Comment by frangi** [comment]
They seem to not detected human movement, but they detect mommi movement. They still don't send any kind of signal tho.

**Comment by ConkerDev** [comment]
They dont even seem to be spawnable anymore.

**Comment by ConkerDev** [comment]
Pomf killed them. Unless its unintended, its not a bug

**Comment by PJB3005** [comment]
Pomf killed them because somebody (N3X15 or pomf) tried to move them to beams, but fucked up and they caused infinite loops.

**Comment by clusterfack** [comment]
Well all beams caused infinite loopies, but that was fixed though

**Comment by Kurfursten** [comment]
Probably can safely remove Bug from this one though, given that it's definitely just Feature Loss now that it's out of the game completely.

**Comment by PJB3005** [comment]
It was removed as an "OH FUCK" due to a bug, I'd say it's worth keeping the tag.

**Comment by clusterfack** [comment]
Its not out of the game uta just disabled, someone had ought to fix it

**Comment by FudgePucker** [comment]
We can't fix this bug because it would be a feature while we are in a feature freeze.
We can't get out of the feature freeze because of bugs like these.

Comment out infrared emitters and close this issue. Open a feature request.

**Comment by PJB3005** [comment]
They're already commented out.

**Comment by FudgePucker** [comment]
So then this isn't a bug its a feature request

**Comment by clusterfack** [comment]
Stop trying to declassify things as bugs

**Comment by ConkerDev** [comment]
The assembly system may have changed the working of emitters. Please recheck

**Comment by PJB3005** [comment]
@ConkerDev it had nothing to do with that, it was the beam that the emitters used that caused infinite loops.

**Comment by Cisrox** [comment]
These things need to be fixed, they're cool as shit.

**Comment by AutismSpider** [comment]
Good for making trap bombs when they did work just got wait see if they dont bug out the serb and crash it with runtime errors

**Comment by ConkerDev** [comment]
This has been one of the most whined about feature losses. They should be remade.

**Comment by AutismSpider** [comment]
They need to be remade with the new  emitter code

**Comment by PJB3005** [comment]
They were.

Pomf did it. Because he fucked up and didn't test them they were OH GOD PANIC removed instantly and never readded.

**Comment by Probe1** [comment]
fix it

**Comment by jknpj** [comment]
RIP IR emitters
