### ISSUE TITLE
Islandstation medbay issues

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#31335]
#### Description of issue
aux surgery table is far away from tools malding surgeons
puddle of water????? in patient room
CMO office missing many items like lights, fire alarm and cmo announcement console
Virology missing a log of shit, beakers, syringes gloves and the dishes and mutagen
cryo is not connected up properly
![image](https://user-images.githubusercontent.com/3959840/142497182-0828d7a1-0dc4-4750-9372-28dae14ec780.png)

#### Server revision
Game: 6789b69609d1c7787640ef3d2e97e4b469abd6a8 
Patches: 11fb283d23ba8368ca55fda744adbc14e5a418bb 

[island]
[mapping]
[bugfix]

**Comment by BurntDevil** [comment]
Dishes and mutagen are in the locker above the desk table labeled virus storage. Keeps your desk clear. Added the rest to there, cmo, aux surgery.

Puddle is a meme because theres no sink for that direction.

**Comment by CptWad** [comment]
![image](https://user-images.githubusercontent.com/3959840/142544609-b81accfc-41f2-4f95-9179-de4b94c255ac.png)
Checked myself and... no lockers had the dishes

**Comment by BurntDevil** [comment]
The wall lockers. The boxes with green squares above them.
