### ISSUE TITLE
AI holopads break forever when unpowered

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#32042]
#### Description of issue
the holopads stop working if they ever have the power turned off, despite it turning back on later

#### Difference between expected and actual behavior
  expected 
turn power off
holopad don't work
turn power back on
holopad work
  actual
power off
holopad don't work
power back on
holopad don't work

#### Steps to reproduce
be AI
turn off a room's eqpt power
turn it back on
try to interact with a holopad

**Comment by SonixApache** [comment]
oh, i ran into this bug a few days ago but i couldn't figure out the reason at the time

**Comment by pedr69** [comment]
a holopad's stat becomes 16777213 when unpowered, even it it goes back to being powered
i thought stat was supposed to have five bits, what the fuck is this shit

**Comment by pedr69** [comment]
hmm yes i see
![image](https://user-images.githubusercontent.com/18052467/167640974-e352d20c-87b8-4f5a-b901-794c93bf5ccf.png)
