### ISSUE TITLE
SCP-13261 and SCP-13262, "The Item Sorting Machine" and "The Wrapping Machine", Spacetime Anomaly, Object Classes: "Safe"

### ISSUE THREAD

**Issue by WindowsErrors** [vgstation-coders/vgstation13#32443]
#### Description of issue

![Screenshot (1706)](https://user-images.githubusercontent.com/58999300/164999628-cdf28041-898a-475a-881c-52857f82288a.png)

#### Difference between expected and actual behavior

the boards
they're everywhere
i can't stop it

#### Steps to reproduce

1. Acquire an Item Sorting Machine or Wrapping Machine Circuit Board
2. Construct the Item Sorting Machine or Wrapping Machine frame, filling it with parts
3. Screwdriver the machine frame to finish the frame and make a completed Item Sorting Machine or Wrapping Machine
4. 

> it drops a new board out of thin air when you perform step three

5. 

> t̶h̵i̷s̵ ̵d̵o̴e̵s̸ ̴t̵h̷i̶s̴ ̴e̸v̴e̸r̶y̴ ̷t̶i̴m̸e̷ ̷y̵o̶u̴ ̷s̶c̶r̸e̶w̸d̷r̴i̸v̶e̸r̴ ̴i̵t̶
> D̸̦̎O̶̩̎N̶͎̽'̶̹͒T̵̋͜ ̶͉̈́R̸̦̔I̵̗̾G̸̤͗Ḧ̵̯́T̷͓̄ ̶̻́C̸̜͛L̷̳͑I̴̡̅C̸̜̔Ḵ̴̔ ̵̥̋T̵͇̿Ḣ̴͉Ạ̵͝T̸͓͊'̸̮̆S̴͓̎ ̶͕͗H̶͙̔O̴̘͝W̴̤̐ ̶͌ͅǏ̴̹T̴̫̍ ̶̡͂Ğ̷͓E̶̹̚T̸̮͠S̵̳͘ ̷̜̉Y̷̗͘O̵̼̓U̴̧̓

#### Specific information for locating

Circuit Board (Item Sorting Machine)
Circuit Board (Wrapping Machine)

#### Length of time in which bug has been known to occur

#32384

**Comment by kane-f** [comment]
item appears to be manufacturing boards through a [REDACTED] in [DATA EXPUNGED]

**Comment by Jack7D1** [comment]
iT DOESN"T STOP

**Comment by Eneocho** [comment]
We ended up making an infinite glass machine.
