### ISSUE TITLE
power monitoring computer sometimes breaks

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#32531]
#### Description of issue
the computer will show power in percent instead of watts and not show any APCs
fixed by unscrewing and rescrewing the screen
happens about uhh 20% of the time? i think?

#### Difference between expected and actual behavior
expected 
![image](https://user-images.githubusercontent.com/18052467/166807096-8b4bee01-b6f2-46f2-8c66-21784db76c78.png)
got
![image](https://user-images.githubusercontent.com/18052467/166807474-d225ba12-fc30-460d-84e8-dbcb5ac365f6.png)
the pictures are not from the same round but i hope you get what i mean

#### Steps to reproduce
open power monitor
???
profit!

**Comment by pedr69** [comment]
this is packages/tgui/interfaces/PowerMonitor.js right?
what am i even looking at

**Comment by Eneocho** [comment]
>what am i even looking at

The death rattle cry of a coder that couldn't do anymore. Here be dragons.

**Comment by jellyveggie2** [comment]
Copypasting a reply from somewhere else:
> Seemed to happen a lot when modifying/merging tiny powernets while testing. My best guess so far is the variable pointing to whatever powernet the monitor is connected to isn't getting updated when modifying the powernet replaces it with a different powernet. No idea why it wouldn't be updating though, and I haven't actually looked into it so to reiterate, this is just a guess.
