### ISSUE TITLE
Chem dispenser UI's a pain to open

### ISSUE THREAD

**Issue by PJB3005** [vgstation-coders/vgstation13#3264]
During a (semi) recent round as a mechanic I found myself having trouble opening the chem dispenser UI, it wouldn't open, or atleast very infrequenctly

**Comment by TermedClepe** [comment]
Related to https://github.com/d3athrow/vgstation13/issues/3158

How to replicate: stand next to a chem dispenser, disconnect, reconnect, try to dispense chems.

**Comment by PJB3005** [comment]
could be, but when I was experiencing this after a relog I was able to open it once, right after relogging

**Comment by clusterfack** [comment]
What termedclepe describes is a known bug that byond has.

**Comment by ConkerDev** [comment]
UIs have changed since. Fixed?

**Comment by 9600bauds** [comment]
My bad, these don't use nano

**Comment by PJB3005** [comment]
Yes they do.

**Comment by 9600bauds** [comment]
Haha I'm stupid I mixed the chemdispenser up with the chemmaster

**Comment by uazuaz** [comment]
this happened to me multiple times, last time today. i was using the chem dispensers inside box's chemistry lab, after a while one of the dispensers turned unresponsive and clicking on it didn't have any effect; by the way i could put a beaker inside and eject it using alt+click. it fixed after about 10 minutes for no apparent reason.
i haven't logged out the entire time;
the other dispenser was working fine;
i don't know how to replicate the issue.
