### ISSUE TITLE
armor sometimes doesn't shield you from ranged damage

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#32778]
[bugfix]

#### Description of issue
armor doesn't armor you from bullets/lasers
lasers do it more often(bout 25% or so), bullets very rarely(<5%)

#### Difference between expected and actual behavior
expected: armor protect
actual: armor doesnt do shit

#### Steps to reproduce
get armor, lasergun and a willing participant
shoot lasergun at an armored individual

#### Specific information for locating

\code\modules\mob\living\living_defense.dm
more particularly the run_armor_check seems to not return the same thing when given the same args
![image](https://user-images.githubusercontent.com/18052467/173197038-f20af525-1dc0-4280-85a8-40740490c0be.png)

**Comment by ShiftyRail** [comment]
Barry......

**Comment by pedr69** [comment]
and now shit i havent even touched stops compiling
what is going on
![image](https://user-images.githubusercontent.com/18052467/173197222-678347ce-d857-419c-a938-00565d1b9296.png)

**Comment by ShiftyRail** [comment]
![image](https://user-images.githubusercontent.com/31417754/173197796-4b3fd10d-6fcf-4c62-a07b-e5c94babc11a.png)

Doesn't seem to be the case. I got a tarajan with a 50% energy protection armor and the laser hits are consistently giving out 15 damage instead of 30.

**Comment by Exxion** [comment]
I'm guessing you were testing helmets

**Comment by pedr69** [comment]
not it, the full damage gets applied to the head

**Comment by ShiftyRail** [comment]
![image](https://user-images.githubusercontent.com/31417754/173197991-a400c8a1-3fa6-4bab-86b2-53cfd184cd93.png)

Yeah, it looks like it's missing the head and running a check against the torso (?) but the damage is applied to the head.

**Comment by pedr69** [comment]
seems that getarmor() for humanoids, wherever it's defined, doesn't return the same thing consistently 
![image](https://user-images.githubusercontent.com/18052467/173198074-54fbc4b9-4af0-448c-9c16-3054b82be0db.png)

**Comment by Exxion** [comment]
OK, so it's *supposed* to have a chance of hitting the torso, but actually still hits the targeted area and just uses the torso's armor value.

>seems that getarmor() for humanoids, wherever it's defined, doesn't return the same thing consistently

Yeah that's what we're talking about

**Comment by pedr69** [comment]
i'll try giving him a vest too

**Comment by pedr69** [comment]
damn it really is the vest huh
how did i not notice that for so fucking long

**Comment by Exxion** [comment]
The random zone selection inside `getarmor()` is dumb and should be performed somewhere else. I can't think of any scenario in which you would ever want to run an armor check on a zone other than the one involved

**Comment by ShiftyRail** [comment]
Yeah we know what is happening
Fixing it appears to be incredibly involved for such a simple case to identify

**Comment by pedr69** [comment]
it still happens if he has a vest and you target the vest
a vector magdump into a bulletproof vest should do 20rnds*15damage/round*0.2(armor) = 60 damage yet the guy is taking 80+

**Comment by Exxion** [comment]
Yeah, and when you target the chest there's a small chance of it rolling on the armor of anything but the chest

It's quite simple to fix this, just not simple to add the feature back as intended

**Comment by ShiftyRail** [comment]
There doesn't appear to be any RNG in getarmor though. Am I looking at the wrong proc ?

**Comment by Exxion** [comment]
`ran_zone()`

**Comment by pedr69** [comment]
so, /mob/living/carbon/human/getarmor( is the one releasing nervegas?
shouldn't the zone randomisation be done when you pull the trigger instead of when it hits something?

**Comment by Exxion** [comment]
It would be fine either way. The problem is that it's randomizing the zone of the armor check, not the one actually hit.
