### ISSUE TITLE
tweak snaxi availability

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#32876]
[featurerequest]
some snow can be comfy every now and again
but having it available all of july(along with the 3 months of winter), i reckon the trend of highpop snaxi winning and halving the pop is gonna happen all month
perhaps have it roll when the average station temp is under 0C? 

revert #28981 when?

**Comment by Eneocho** [comment]
Just roll a prob(5) and if it rolls snaxi is available for that voting cycle. Would fix the snaxispam on the available months while still letting people play snaxi every now and then

**Comment by BomberBro** [comment]
Simply make voting for snaxi then not playing the next round ban you for a week

**Comment by Kurfursten** [comment]
Snaxispam seems like a "take your meds" moment. It has been voted twice in two days. In neither case did population halve - it dropped from 36 to 31 and then from 28 to 24. However, fluctuations of this number are very common for any map. For example, during the same period, Synergy was voted and pop dropped from 21 to 6. Ban Synergy, or just ban people from going to sleep around midnight American time?
After a Box round, a second round of Box led to population dropping 21 to 18. Ban double Box shifts?

**Comment by DorainGrey** [comment]
> Snaxispam seems like a "take your meds" moment. It has been voted twice in two days. In neither case did population halve - it dropped from 36 to 31 and then from 28 to 24. However, fluctuations of this number are very common for any map. For example, during the same period, Synergy was voted and pop dropped from 21 to 6. Ban Synergy, or just ban people from going to sleep around midnight American time? After a Box round, a second round of Box led to population dropping 21 to 18. Ban double Box shifts? At 1am, a vote of Box led to 0 players and 2 ghosts. Ban observers?

I'm not saying you are wrong but speaking from personal experience, I played both rounds since it was high pop and it's been a while since I played Snaxi. After the misery of both, primarily due to terrible engineering department and other map features.
I probably will just log off if Snaxi is voted in again this month, it's rarely enjoyable.
That's just an anecdote and my own opinion but it'd be interesting to look at the stats after a week or two, as opposed to the first 2 times a map is available, which probably aren't accurate representations.

**Comment by Eneocho** [comment]
>Snaxispam seems like a "take your meds" moment. 

Last year's snaxi "enthusiasm" it was awful though. I clearly remember like 3 out of every 10 rounds being snaxi.

**Comment by Kurfursten** [comment]
Counterpoint: There were zero Snaxi rounds today. Sounds like this thread is a lot of instant whining after seeing the map online one time. Imagine.

**Comment by pedr69** [comment]
i just don't want the winter trend of snaxi wins and cleaves the pop to repeat
as it is i'm still fine with snaxi, but a round or 2 a day for a month will make me fucking sick

**Comment by Kurfursten** [comment]
Looks like time proved me right on this one

**Comment by adacovsk** [comment]
time proved you wrong, old man

**Comment by Kurfursten** [comment]
The data is on my side. Again.
