### ISSUE TITLE
toggling darkness as ghost hides ghosts instead of just toggling darkness

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33108]
and why is there a hide sprite spell but to hide other ghosts you need to look in the verbs

what does it all mean
![image](https://user-images.githubusercontent.com/18052467/185917340-d60adfe8-b4ef-4edc-bad1-99fdceb24064.png)

**Comment by Exxion** [comment]
#32212
#29623
#6671
Honorable mentions for #16720, #13229, and #9693

**Comment by pedr69** [comment]
>issue since 2015

really?
i coulda sworn it used to work, is my dementia kicking in

would a way to fix this be to set vision_override_dark instead of see_invisible?

**Comment by Eneocho** [comment]
>is my dementia kicking in

https://www.youtube.com/watch?v=Jvzgi15kRCI

**Comment by Exxion** [comment]
It would be relatively easy to fix with planes and `PLANE_MASTER`, but nobody's bothered
