### ISSUE TITLE
box AI upload windoor access

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33177]
[box]
"core modules" and "high risk modules" windoors aren't set to AI upload access
the RD can get into the upload, turn off the turrets but can't open the windoors with the modules

**Comment by kernikov** [comment]
Windoor access is apparently "20", which is captain.
It makes sense that the high risk modules (robocop, paladin, corporate, core free form, asimov, antimov, teleporter offline, onehuman and toxic oxygen) require the captain's access (or permission) to access.

Not a mapping issue?

**Comment by nervere** [comment]
I checked out a bunch of other maps (roid, meta, synergy) and the high-risk modules windoors all require captain access.
Gonna go ahead and close this as it doesn't seem to be an issue with Box, more of a universal design choice.
