### ISSUE TITLE
discount dan sauce packet

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33241]
[bugfix]
![image](https://user-images.githubusercontent.com/18052467/188637970-17c32fb9-3dd3-4ef0-8db8-d9f0ffde8d94.png)
why is the discount sauce packet a child of drinks, not condiments

**Comment by jwhitak** [comment]
Condiments were added long after discount dan sauce packets were added. Deity would've converted them but Deity is gone now...

And I've been too lazy.
