### ISSUE TITLE
particle accelerator sprites breaking

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33285]
[sprites]
![image](https://user-images.githubusercontent.com/18052467/190282882-fc46b153-23fd-42fe-8d0c-2113c3047c45.png)

the containment fields get flipped when the PA is set to 2 or 3(but not off, 0 or 1) - the sprites don't even update, they just flip
the acceleration chamber gets funky when you set it from 2 to 3, and the PA is facing up

possibly more issues, i didn't test this a lot

**Comment by adacovsk** [comment]
PA code is absolute shit and needs to be redone. The console also sometimes breaks if you use the multitool/cut a wire

**Comment by pedr69** [comment]
>console breaks
never happened to me
when you're hacking it, you need to use a multitool to open the menu, keep it open, then switch to wirecutters to cut the wire
wirecutting the unscrewed computer will start deconstructing it

**Comment by Kurfursten** [comment]
If you see this happen again please ahelp and ask them to VV and report the _reference_ and _icon_state_ values for the inverted emitters
