### ISSUE TITLE
gamer compliance

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33325]
the google doc says github doesn't like [redacted], [redacted], and this in our code:
>[redacted]

how do we replace these words in the code without actually replacing them?
i tried #define but the deathsquaddie name is a problem, since it's in a plaintext file

**Comment by Theophrastus1** [comment]
the day this gets removed is the day we truly have lost the mandate of heaven

**Comment by pedr69** [comment]
i like saying nigger as much as any other spaceman, but logging into shithub every time is a fucking pain in the ass

**Comment by WindowsErrors** [comment]
you will coomply

**Comment by ebakai** [comment]
Hex escapes? E.g. `"This idea is \x72\x65\x74\x61\x72\x64\x65\x64."`

**Comment by SECBATON-GRIFFON** [comment]
#define CANDY_ASS "gamerword"
#define ROODY_POO "gamerword"
in some secret repo file should do it, if staying on github is really that important

**Comment by pedr69** [comment]
i tried to do this by making some config variables instead of #defines but the chaplain religions stop compiling
the defines should work, but how to make them in such a way that won't need pomf to change the files every time the server recompiles?
i have no idea how the secret repo works what with it being secret and all
