### ISSUE TITLE
frankenline isn't on the voting list (in october)

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33429]
stupid fucking retard #33150
instead of reverting the primetime PR you made it not even work
![image](https://user-images.githubusercontent.com/18052467/193487073-488763a0-0566-4512-a8d4-18f7e8879570.png)

**Comment by DorainGrey** [comment]
I'm pretty sure the intention was to remove it from the voting pool altogether. There was a separate PR for removing prime-time for a reason. Not really a bug.

**Comment by PrimeDSS13** [comment]
not a bug that was clearly the point of the PR

**Comment by gurfan** [comment]
What the fuck do you think "Removes Line Station from the voting pool" means?
