### ISSUE TITLE
clown invisispray shitcode

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33482]
[bugfix]
making items sprayed on the ground(sharts) vanish from the right and alt click menu might be intentional
but this applies to normal items too, say you spray the captain's spare ID invisible
it will vanish from the rightclick and altclick menu, and you won't be able to pick it up
a T-ray scanner will make it briefly visible
>if you pick it up while the item is t-ray temporary visible, it will always remain visible
>if you right click while it's temporary visible, only to pick it up when it goes back to invisible, you'll have an item in your hand that you cannot right click, or remove from your pocket/backpack easily

**Comment by adacovsk** [comment]
Yes this was intentional so you can still find invisible items in your bag. The right-click is gone from items on the ground to prevent powergaymers from finding shit just by right-clicking

**Comment by adacovsk** [comment]
Also, the way tray scanners work is still shit, but I did improve it, it's not so simple. The reason this happens is because of `spawn()`  and things get out of order

**Comment by pedr69** [comment]
oddly enough i don't see the fact it's intentional mentioned in any of the invisibility related PR's....

**Comment by adacovsk** [comment]
my apologies, I'll try to make a PR for right-clicking stuff again. I can't remember anything regarding what I did, hopefully it's easy to fix.
