### ISSUE TITLE
frankenline not votable in october(yet again)

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33600]
i know people don't like it but come on now

**Comment by west3436** [comment]
feature

**Comment by nervere** [comment]
This probably has something to do with Pomf replacing the file with Lamprey. I don't know, really.

**Comment by d3athrow** [comment]
dab

**Comment by adacovsk** [comment]
>subverting community polls
Edgy and cool

**Comment by pedr69** [comment]
if a poll were made now i'm guessing "line sux" would win
probably because [redacted]s kept voting line and sneedrunning

however, there was no poll
i might make a PR that makes line require IC conditions, or perhaps we could return to persistent voting, which would make playing the same map twice much harder

**Comment by kernikov** [comment]
> > subverting community polls
> 
> Edgy and cool

ironic, lmao

**Comment by d3athrow** [comment]
> > subverting community polls
> 
> Edgy and cool

make the map not shit then
