### ISSUE TITLE
roid piping fucky wucky

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33684]
scrubber not connected
![image](https://user-images.githubusercontent.com/18052467/201454088-dc624799-590e-4ce3-b3b2-da7fc0fca818.png)

**Comment by nervere** [comment]
This might be the reason all the roid scrubbers immediately turn red. Good find.

**Comment by Kurfursten** [comment]
![image](https://user-images.githubusercontent.com/9782036/201454458-c31c0044-d291-4389-8511-a6d3d0e2ef0c.png)

**Comment by pedr69** [comment]
but whats the actual reason it breaks?
and why does it make the scrubbers go red despite the pipenet being under 5033kpa
