### ISSUE TITLE
Detective's noirglasses

### ISSUE THREAD

**Issue by Fizbun** [vgstation-coders/vgstation13#337]
Because the current detective office layout has no sunglasses, then they should spawn on the detectives pocket. The idea of it is that they function like normal HUDsunglasses, expect they filter all colour to black and white. If it would be possible, to make the colour red to stand out while wearing noirglasses, simply to add to the atmosphere that the detective actually was in a 1950's movie.

All for muh immulshun.

**Comment by ghost** [comment]
Guys. The dream is real. #8046

**Comment by Fizbun** [comment]
The sleeper has awakened

**Comment by ihadtoregisterforthis** [comment]
"Currently" was the proper word.

**Comment by Shadowmech88** [comment]
Amazing that even two-year-old feature requests are getting fulfilled.
