### ISSUE TITLE
cursed gas generation method

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33739]
[featureloss][bugfix]
opening an airlock that's built on top of the "x gas floor" will add 100k moles of x gas onto its turf

![image](https://user-images.githubusercontent.com/18052467/203865319-66b0d4be-78df-460c-9b79-6340ade0e851.png)

**Comment by Eneocho** [comment]
Tested it on the plasma chamber and couldn't replicate.

**Comment by pedr69** [comment]
funny you mention it because i made a 240GW engine last round using this

**Comment by Eneocho** [comment]
I built a couple airlocks on the aforementioned tiles and did what you described and couldn't replicate. More details (if any), please?

**Comment by Eneocho** [comment]
Unless you meant an airlock that was mapped in.

**Comment by pedr69** [comment]
the gas is put into the airlock
to get gas from the airlock, you can either:
open it to copy the gas into the turf and let it spread out before collecting(you can do this infinitely)
keep it closed and use a vent directly under the door, which will pump gas into(or out of) the door

**Comment by pedr69** [comment]
oh yeah i used the premapped one

**Comment by pedr69** [comment]
okay this actually works with all airlocks, anywhere
[loose]
is your room airless(but sealed)? just open the door repeatedly to conjure some air into existence

**Comment by pedr69** [comment]
each time the door is opened, the `airlock.turf.air` gets released and can spread around, but when the door is closed the current gas state isn't saved back into the `turf.air`

**Comment by Exxion** [comment]
I wonder how long this has been broken. As far as I can tell, it's been years, but I swear someone (most likely myself) should have noticed it.
Anyway, it's an easy fix.
