### ISSUE TITLE
HOS office windows/shutters opaque

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33831]
[box][mapping:box]

#### Description of issue
![image](https://user-images.githubusercontent.com/18052467/208174181-9d33fecb-ef09-48a9-8850-11ae9a2db53c.png)

#### Difference between expected and actual behavior
expected transparent
got opaque

**Comment by dinnerwoerror** [comment]
oh yea that's a thing when the shutters are closed

donno why though
