### ISSUE TITLE
mysterious air alarm on box

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#34214]
[box]
there are no vents or scrubbers in the room
there are no vents or scrubbers in the rest of maint
why's the door have a firelock
![image](https://user-images.githubusercontent.com/18052467/230701055-166cafd3-af2b-4cb0-98f7-84d971217fd6.png)

**Comment by Inorien** [comment]
looks like its just mislabeled

**Comment by SacredAtom** [comment]
This guys brain is small

**Comment by Squird5** [comment]
So that if toxins are detected in the room, it closes the firelock. The door is labeled as Ghetto Shelter, but the Area is Fore Port Maintenance, so the air alarm is named that. It is a ghetto plasma survival hovel in maints. Working as intended.

This can be closed
