### ISSUE TITLE
greytide plus loyalty implant

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#34256]
[inconsistency]

so how are the two supposed to interact if you're implanted with both?
greytide takes over? nanotrasen takes over? whichever was implanted first?
currently the greytide takes over, while giving everyone around the implantee the message that the implant was resisted

**Comment by gallywix4** [comment]
i believe resisting the greytide implant is broken right now, traitors are supposed to resist the implant however the last time i used it on a traitor everyone got the message that he resisted but kept the giant G on the side
