### ISSUE TITLE
deff supermatter room wiring

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#34260]
[deff][defficiency]
the right 3 rad collectors aren't actually connected to the wires
there's no wire knot
![image](https://user-images.githubusercontent.com/18052467/236654955-5ede1096-82aa-47be-afca-da184e89950b.png)

**Comment by DorainGrey** [comment]
This one is probably my bad, I'll fix it today kinda want to rejig the chamber a tiny bit anyway.
