### ISSUE TITLE
you can no longer crowbar APC's to replace the powercell

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#34308]
unlock APC and unlock the cover from its interface
crowbar does nothing, powercell is stuck forever(until you get a BRPED)
makes APC's unable to be deconstructed too, so if a bomb breaks the thing you're fucked

i'm guessing someone fucked with some `preattack` and borked it

**Comment by DorainGrey** [comment]
This has to be very very recent, I definitely replaced cells two weeks ago.

**Comment by pedr69** [comment]
i tried looking at the runtime logs and found some stuff
but there's also runtimes fucking everywhere else jesus christ

![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/5b1433a8-4292-4b9e-9e9d-134dd783f463)

**Comment by DorainGrey** [comment]
This PR caused it [34287] confirmed on local.

**Comment by pedr69** [comment]
lol hivemind

**Comment by Inorien** [comment]
this is related to recent reports of people being unable to remove broken APCs from the walls, i believe

although I think that was actually an older bug being concealed by some crowbar hack intended for mommis
