### ISSUE TITLE
deff overflow surgery mislabeled

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#34336]
[deff]
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/7a456c81-92b3-406a-93ba-8fbe03c66025)

APC says ghetto surgery instead of overflow
the doors are labeled right though

**Comment by Securitymain** [comment]
![grafik](https://github.com/vgstation-coders/vgstation13/assets/132118542/a110e37c-3996-4615-8cf1-1a86489d2ee3)
entire area is tagged ghetto surgery
not sure what the mapmaker thought here... are stations REQUIRED to have a ghetto surgery somewhere? the airlocks all require surgery access anyway

if nobody has an idea as to why changing this area into surgery would be bad, ill put up a pr tomorrow or so
