### ISSUE TITLE
box shitmappers?

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#34993]
[box][boxstation]
bug or feature? the fact it's not wired makes me wonder
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/1b8fd36d-50f0-47ad-bba4-b99ed9a5f274)
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/44554ff4-1e7d-4ff7-bba4-3c27193c04b8)

**Comment by Squird5** [comment]
It's a feature. Maints clutter.

This can be closed.

**Comment by pedr69** [comment]
a light fixture floating in midair?
