### ISSUE TITLE
APC shitcoders

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#35016]
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/6b96e4cd-617c-4460-8ce9-4d53e8770c6c)
APC missing, area unpowered

**Comment by SonixApache** [comment]
are you sure that isn't wizard fuckery because afaik those terminals only spawn under APCs

**Comment by pedr69** [comment]
[16:35:40]ADMIN: DYNAMIC MODE: Picking a  ruleset...<font size='3'>Vampires</font>!

**Comment by Dacendeth** [comment]
My expert opinion says there's a false wall there made by a vampire and the apc is hidden under it and just out of power.

**Comment by pedr69** [comment]
APC was not there, doors and lights were unpowered
this was also at station time 12:10 or so

**Comment by pedr69** [comment]
i can confirm the APC was there last round
[unable to reproduce]

**Comment by DorainGrey** [comment]
> APC was not there, doors and lights were unpowered this was also at station time 12:10 or so

I think you've stumbled across something, I've also noticed missing APC's with terminals on some rounds.
Different location every time, Viro maint, Viro Lobby, Gateway etc

I can't help but wonder if there's some bug here.

**Comment by west3436** [comment]
I have definitely seen this happen before as well; happened once in the Science hallways on Box. Probably not a mapping bug but something more insidious...

**Comment by Exxion** [comment]
https://game.ss13.moe/logs/2023/runtime/2023-09-16-runtime.log
`Second APC detected in area: Fore Port Maintenance 203, 285, 1. Deleting the second APC.`

I'm guessing the problem is people reusing station areas in vaults

**Comment by pedr69** [comment]
yeah it happened again on roid CMO office, looks like it's not map specific

**Comment by Exxion** [comment]
OK, it looks like *a lot* of objects are getting initialized before the subsystem tries to initialize them. For most types, this gets checked and the subsystem skips initializing the object and just sticks it in a list for debugging. But `machinery` doesn't supercall in `initialize()`, so the flag that says it's already been initialized never gets set, and it gets initialized again. In the case of an APC, this will always cause it to delete itself.
Does anyone know roughly when this started?

**Comment by Exxion** [comment]
Oh. OK the reason it started happening recently was #34608, because before that, the bug wouldn't have deleted the APCs

**Comment by Exxion** [comment]
The vast majority of the double-inits are objects in vaults. Those should still be fixed, but they don't explain on-station APCs getting double-initialized.
In the better part of an hour of testing, I was only able to locally reproduce the on-station APC double initialization twice, and I didn't get any useful debugging information either time. I love how BYOND sets a hard limit on the number of stack traces you can get in a given period of time.

**Comment by Kurfursten** [comment]
Thank you for your detective work
