### ISSUE TITLE
box HOS office shutters

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#35102]
[box][mapping:box]
the open shutters are airtight, somehow
they're constantly at 101.33kpa and the rest of the room is 101.1kpa instead of both being sucked into space
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/33e845ed-fcb4-433a-a885-d6a284062b64)

related to #33831

**Comment by toomykins** [comment]
these shutters are set wrong
density should be 0 if they start opened.
they dont have that.
