### ISSUE TITLE
frankenline not votable in october(yet again)(yet again) 

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#35108]
today i will remind them
@d3athrow 

https://ss13.moe/index.php/poll/236
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/cc6f95e6-593e-435e-9293-e6d67f5b95a3)

cont of #33600

**Comment by BomberBro** [comment]
[Heavy Voice] No!

**Comment by west3436** [comment]
Feature not a bug

**Comment by djkramer123** [comment]
working as intended

**Comment by wotisjanitor** [comment]
Oh no! Anyway

**Comment by falcon2346** [comment]
Maybe if the tubes worked. Unless someone wants to remap it to make frankenline actually functional that's a no from me

**Comment by NigglyWiggly** [comment]
It's a feature

**Comment by pedr69** [comment]
october's over
see you next year
