### ISSUE TITLE
(WEB REPORT BY: kurfurst REMOTE: 198.245.63.50:7777) NanoUI Issue - Central Atmos Computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#3591]
> Revision
> 1677601ddf8b13581893528f96afacf911ed1a8a
> 
> General description of the issue
> When viewing an air alarm from the central atmos computer, it doesn't update the meters automatically: you must click something to get it to refresh (e.g.: toggle panic siphon)

**Comment by Kurfursten** [comment]
This still happens, sadly.
