### ISSUE TITLE
Console construction lacks messages for starting each step

### ISSUE THREAD

**Issue by 9600bauds** [vgstation-coders/vgstation13#3669]
When you're building a console, each step will only display a message when it successfully finishes, unlike everything else which gives you messages such as "You begin adding cables to the frame... You add cables to the frame."
Some steps even play sounds, they simply lack a starting message.

To reproduce: Build a console frame from 5 metal sheets, do the thing, it no good

**Comment by dylanstrategie** [comment]
Console construction can most likely use a few tweaks, especially seeing how modular it is

**Comment by 9600bauds** [comment]
Wait a second
This is still an issue
