### ISSUE TITLE
Windows can be pulled out of anything except other windows and walls

### ISSUE THREAD

**Issue by Exxion** [vgstation-coders/vgstation13#4042]
As I found this out while testing a change of my own, I actually know exactly why this is the case code-wise, but I don't really want to fix it myself because there is a distinct possibility I would fuck everything over.
For some reason, Adjacent() calls ClickCross() with border_only=1. This means ClickCross() ignores everything except border objects. If border_only is 0, it only ignores objects that are not dense and/or do not have throwpass. My worry is that fixing it might have consequences in places that, for some reason or another, rely on the current behavior. Since Adjacent() is such an important proc, any such consequences could be bad.

**Comment by Exxion** [comment]
This also lets you break into areas with windows and only let one tile of air out as long as you have a screwdriver and crowbar
1. Remove the outer window
2. Break/disassemble the grille
3. Unfasten the inner window
4. Step onto the tile the grille was on
5. Ctrl+click the unfastened inner window
6. Click the tile behind you (the one outside the window)
7. Step one tile inward and let go of the window

**Comment by 9600bauds** [comment]
Couldn't you just rotate the window, too?

**Comment by Exxion** [comment]
That depends on whether or not air is blocked by the sides of windows, which it shouldn't be but I don't actually know

**Comment by 9600bauds** [comment]
Either this doesn't happen anymore or I can't understand the issue
![dreamseeker_2016-12-14_12-39-40](https://cloud.githubusercontent.com/assets/6526157/21188502/6485fd82-c1fa-11e6-8c03-e90f1494c671.png)
Was not able to drag the window through the table, tried creating the table in my tile and dragging the window into it with results seen in the picture

**Comment by Exxion** [comment]
Nah, still happens
Place a window on a grille, get on the opposite side, and pull it through

Windows can't be pulled ONTO the turf of another dense object, but they can be pulled OFF it regardless of direction

**Comment by 9600bauds** [comment]
Oh

Well yeah, that's how you take them out of a grille

You can pull ANYTHING out of a dense object, if you build a wall top of an office chair, that's how you get it out

**Comment by Exxion** [comment]
Yes, but border objects shouldn't do that
You shouldn't be able to pull (or, in some cases, push) a window through another object

I opened this so fucking long ago, I don't remember enough to know if it's true, but past me seems to think it could be fixed in one character, at the cost of fucking other things up
Fixing it without ruining everything would probably not be too hard

**Comment by Cyadox** [comment]
@Exxion Well, this does still happen. Working as intended or something we should try and fix? AFAIK it works this way so you can pull stuff out of walls, grilles, etc.

**Comment by Exxion** [comment]
At some point we need to completely rewrite how `ON_BORDER` objects work and I'm honestly not sure this is worth fixing before then

**Comment by Shadowmech88** [comment]
In any case, this is more of a feature request than a bug, because border windows are behaving exactly like every other object in the game.
This is just requesting that they don't, for the sake of immersion.
