### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Heist Vox done via create antagonist admin ability gives them no objectives

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#4047]
> Revision (Should be above if you're viewing this from ingame!)

f644dddb05942ea37dbd2c20817d8f580e41c139 

> General description of the issue

When creating heist antagonists using the Create Antagonist admin command, it does not give them any objectives.

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by gbasood** [comment]
Can anyone tell me if this is still relevant
