### ISSUE TITLE
Hair appearing when changing gender

### ISSUE THREAD

**Issue by ghost** [vgstation-coders/vgstation13#4052]
Races with no hair (e.g. Diona, Skelingtons) gain a full head of hair randomly selected when in the character customisation screen (the hair randomisation when you change gender does not account for race). This disappears when you spawn ingame but is still visible if you observe.
Still present as of 3400f39

**Comment by MercuryDoll** [comment]
Can we enable some human hair for skeletons?
![image](https://38.media.tumblr.com/ce7509864ba377220366a1741637521f/tumblr_inline_ne8qqs70fD1snxcwz.gif)
