### ISSUE TITLE
VTEC impossible to install in borg

### ISSUE THREAD

**Issue by Aurx** [vgstation-coders/vgstation13#4068]
Gives a "You can't equip this" error.  
Borg in question had undergone a module reset, unknown if happening with unreset borgs.

**Comment by ComicIronic** [comment]
It might be possible that the borg was required to select a module before upgrades could be applied.
Did it?

**Comment by AutismSpider** [comment]
You have to select a module before you can put in vtec etc

**Comment by Cyadox** [comment]
@Aurx Can't replicate it, seems to only happen when the borg is reset but hasn't chosen a module.
Also couldn't find that exact error message in the code, so either it was fixed ages ago or it's something unrelated to VTEC ¯\_(ツ)_/¯

@Shadowmech88 Can probably close this one too, seems to be user error.
