### ISSUE TITLE
Thunderdome Atmos Issue

### ISSUE THREAD

**Issue by clusterfack** [vgstation-coders/vgstation13#4305]
In the turfs in the thunderdome, and possibly elsewhere but I have yet to see it, the atmospherics differs from the air contents of the turf when VV-ed. The turf shows 55 kpa when using ghost analyze air and breathing causes suffocation.
![](http://puu.sh/hCsBb/5059f4420d.png)

**Comment by ComicIronic** [comment]
Are the turfs unsimulated?
What happens if you scan repeatedly? It may be an issue with return_air().

**Comment by clusterfack** [comment]
The turfs are actually simulated, they are the only ones simulated on centcomm. The unsimulated turfs are fine.

**Comment by ComicIronic** [comment]
You are checking the zone's values, right?

**Comment by clusterfack** [comment]
Ah whoops, guess not. Guess the issue is merely that it has about half the gases it needs for some reason

**Comment by ComicIronic** [comment]
I'd be interested to see what the starting gas values are for the tiles. Otherwise, it might be an issue with merging, but it'll be hard to pinpoint since the station turfs start fine.

What's the turf type?

**Comment by clusterfack** [comment]
Turf/simulated/floor, shouldn't be any different than any other simulated turfs I believe.

**Comment by clusterfack** [comment]
The only distinction that I believe could set this area apart is the fact it is bordered on all sides by unsimulated turfs, but I cant see how that would actually make any difference.

**Comment by FudgePucker** [comment]
simulated and unsimulated turfs by eachother is really fucking screwy. I don't know the full technical difference between them, but considering that the SME chamber still isn't fixed, this might just be the air leaking out of the thunderdome some how.

**Comment by Exxion** [comment]
I don't believe this is still an issue, but I'm not sure

**Comment by Exxion** [comment]
This is definitely not an issue anymore
