### ISSUE TITLE
(WEB REPORT BY: jakedb REMOTE: 198.245.63.50:7777) Internal armor plating on mechs

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#4353]
> Revision (Should be above if you're viewing this from ingame!)
> 4c0fe90ecafda384b8d6819c7ccab5b28d333d67 
> 
> General description of the issue
> sometimes it is impossible to put on the internal armor (5 metal). From my short testing I believe that it happens when you're using partial sheets like the ones you get from a fabricator.
> 
> What you expected to happen
> metal would be put on and I can finish it.
> 
> What actually happened
> nothing
> 
> Steps to reproduce if possible
> do all steps to make advanced mechs and take out some sheets that was used in a fabricator while still being above the treshhold.

**Comment by wwjnc** [comment]
Removing partial sheets shouldn't be the issue since they're rounded to an integer. Are you sure you had enough sheets?

**Comment by Cyadox** [comment]
This is no longer a bug, i can confirm it is impossible through the fabricator to eject 'half-sheets', even if you decon the machine.
Also mech armour is working fine, t. person who plays roboticist.

EDIT: @Shadowmech88 delet pls
