### ISSUE TITLE
Transferring DNA from disfigured makes unknown

### ISSUE THREAD

**Issue by ghost** [vgstation-coders/vgstation13#4387]
Transferring DNA from a disfigured / broken / unknown face corpse results in the DNA being attributed to unknown rather than who the DNA actually represents.

**Comment by clusterfack** [comment]
I think Unknown is being stored as the dna.real_name causing this issue

**Comment by ghost** [comment]
Also diona nymphs have wrong UI name regardless of their real name or status.

**Comment by 9600bauds** [comment]
yep, just tested, disfigured person's dna.real_name is being set to "unknown"
I guess only their regular name should be being set?

**Comment by ghost** [comment]
> Fear not my man, it's part of the feachur frees
