### ISSUE TITLE
(WEB REPORT BY: pseudonym REMOTE: 198.245.63.50:7777) Vampire can (sometimes) gain powers/disabilities after feeding

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#4601]
> Revision (Should be above if you're viewing this from ingame!)
> 8876203960787873ccec147c4fc850c9c52255ac
> 
> General description of the issue
> Fed on a braindead guy as a vampire. Became blind. Also gained project mind. Ryetalyn didn't fix it. Only thing that seemed to fix it was (somehow) being turned into a monkey and back.
> 
> What you expected to happen
> Feed on guy
> Get delicious blood
> 
> What actually happened
> Fed on guy
> Got blood
> Also became blind and got project mind.
> 
> Steps to reproduce if possible
> lolidk

**Comment by gbasood** [comment]
It's possible that trauma to the eyes that occured (and it did) only caused the blindness to show up after feeding started somehow.
Not sure about the powers bit.

**Comment by nuklearcellphoneg** [comment]
Sounds like radiation to me.

**Comment by Shadowmech88** [comment]
Are you sure you weren't feeding in a radstorm?

**Comment by ComicIronic** [comment]
Unless someone can do this more than once, I'm going to say it was probably coincidence.

**Comment by gbasood** [comment]
Fairly sure I wasn't feeding in a radstorm.

I figure this is going to be next to impossible to reproduce, but I thought I'd throw up an issue anyway in case someone else ever encounters this.

Would feeding off a radioactive person be related? I remember a rad storm from that round, but I think it was after this incident.

**Comment by Shadowmech88** [comment]
If the person had the radioactive mutation, then simply being near them would've irradiated you and could've given you the blindness+project mind.

**Comment by DamianX** [comment]
It was probably radiation. Either way:
