### ISSUE TITLE
Under JOBS_HAVE_MINIMAL_ACCESS config, Botanists don't have access to Hydroponics hallway airlocks

### ISSUE THREAD

**Issue by 9600bauds** [vgstation-coders/vgstation13#4654]
Minimal access too minimal
Happens in Box, untested in other maps

**Comment by DamianX** [comment]
mapping issue, the airlocks use `req_access_txt` set to `25;28;35`, which means the user needs to have hydro access AND kitchen access AND bar access to open it.

**Comment by Cyadox** [comment]
@DamianX  Should be relabeled to Mapping issue, no? Assuming you actually tested this of course.

**Comment by DamianX** [comment]
We should ask 5-months-ago me
