### ISSUE TITLE
Can't resist cuffs while on fire

### ISSUE THREAD

**Issue by ghost** [vgstation-coders/vgstation13#4681]
Wear atmos suit, get cuffed in fire, you are now forever cuffed.

**Comment by gbasood** [comment]
Still a bug.

The problem is that even if you ARE cuffed and on fire, you'd probably want to put yourself out in most situations before removing your cuffs. So the fact that these share the resist button means it's probably not going to change ever.

**Comment by gbasood** [comment]
okay maybe I'm abusing that tag

**Comment by PJB3005** [comment]
Very maybe.
