### ISSUE TITLE
Built exosuit fabricator broken

### ISSUE THREAD

**Issue by Manaony** [vgstation-coders/vgstation13#4684]
During the last round I tried building an exofab and couldn't get it to pop up. Round start exofabs worked normally.

**Comment by ComicIronic** [comment]
You mean that the machine completed, and the window wouldn't open?
Did you have access?

**Comment by Manaony** [comment]
Yes, I had the roboticist try it and he got nothing either.

**Comment by ComicIronic** [comment]
Did the machine have power?

**Comment by Manaony** [comment]
Yes, it was in R&D on taxi and everything has power

**Comment by ComicIronic** [comment]
Did you trying linking the machine to the RnD console?

**Comment by Manaony** [comment]
Both the RnD and a robotic console after an admin spawned a new machine that still didn't work for some reason

**Comment by ririchiyo** [comment]
If you have two monitors this is a different issue, if you used resend resources under preferences for NanoUI and it didn't work this would be an issue to look into.

**Comment by Manaony** [comment]
Tested it with Elim, spawned and built exofab don't work even after resend resources

**Comment by Manaony** [comment]
Tested it with Elim, spawned and built exofab don't work even after resend resources

**Comment by ComicIronic** [comment]
This is an issue with a runtime breaking attack_hand, and output not being set properly.

**Comment by 9600bauds** [comment]
Still an issue?

**Comment by gbasood** [comment]
guess we'll find out

**Comment by Cyadox** [comment]
@Shadowmech88 Not an issue, at least not on Box. May be Taxi specific but it's not like we have it on rotation anyways. Building a new exofab works anywhere with power, no console required.
