### ISSUE TITLE
Cargo crate contents glitch.

### ISSUE THREAD

**Issue by nuklearcellphoneg** [vgstation-coders/vgstation13#473]
When you send crates off through cargo, they leave behind their contents, most importantly, stamped manifests.

![cargo](https://f.cloud.github.com/assets/6540760/2036753/62c24e38-8954-11e3-8e8a-ec53fe75b595.png)

**Comment by nuklearcellphoneg** [comment]
The last time I checked this uh

Still happens.

**Comment by ihadtoregisterforthis** [comment]
Why would you stamp the manifest though

**Comment by nuklearcellphoneg** [comment]
We used to be on a cargo point system rather than cash.

I think stamps used to give you more points?

**Comment by ComicIronic** [comment]
An approved manifest gave you those tasty tasty points, unless it had an error in which case you got a CentComm beating.
