### ISSUE TITLE
Xeno HUD while unconscious

### ISSUE THREAD

**Issue by Ephx1** [vgstation-coders/vgstation13#4738]
Don't know what the fuck happened, during surgery I suddenly had a small bit of Xeno HUD while undergoing surgery. Only the fire indicator for some reason, like it was chopped off from the rest.
Little info:
Was a voxpox
Undergoing surgery
Broken Bones
Unconscious
Had xeno roles set to on
Retracted myself from Xeno sign-up before I was brought back to life and operated on

I had a picture, but like a retard I forgot to save it.

**Comment by Shadowmech88** [comment]
This has happened to me as well in the past, I believe it was when I went blind during a xeno round. I had the lower bit of that bar in the upper-right of the xenos' screen visible.

**Comment by CptWad** [comment]
Had this just happen. I got the xeno mode panel stuck in HARM down where the usual panel is.

**Comment by DamianX** [comment]
Hasn't happened in a long time.
