### ISSUE TITLE
Lubed shuttles remain lubed forever

### ISSUE THREAD

**Issue by wwjnc** [vgstation-coders/vgstation13#4765]
Happened on Taxi B at Taxistation. The entire floor was lubed and it didn't go away. Maybe has to do with them being unsimulated tiles or something.

**Comment by Gringonius** [comment]
@Kurfursten this is still very relevant regarding Bus. Some clowns lube both taxis ASAP.

**Comment by Kurfursten** [comment]
Needs more testing. Shuttle floors are identical to normal floors except different explosion resistance. They are not unsimmed.

Lube could really use a visual effect.
