### ISSUE TITLE
Can't get out of disposal bins (and potentially from other things) while gravity is off

### ISSUE THREAD

**Issue by ghost** [vgstation-coders/vgstation13#4769]
You can't move even if there's a wall next to the bin. Haven't tested lockers or other similar things.

~~Minor bug too but while you're inside a bin and you use a hardsuit helmet (subject = mob's name):~~

> ~~You cannot turn the light on while in this [subject].~~

~~_(which is pretty stupid IMO because you still have hands inside but that's not relevant to this issue)_~~

**Comment by ComicIronic** [comment]
The light on/off thing is deliberate, because it screws with luminosity updates if the atom changed isn't on a turf.

**Comment by PJB3005** [comment]
Well, that should be fixed with the bay lighting rewrite

**Comment by wwjnc** [comment]
(By the way, if it wasn't clear enough, the issue with the lights is that the message is wrong)

**Comment by gbasood** [comment]
This is still a bug but a minor one (pretty sure gravity loss only happens in space, where there shouldn't be disposal bins, and when admins bus it)

Hardsuit helmet lights work fine though

**Comment by PJB3005** [comment]
@gbasood that's because baylights isn't terrible at light source management, the lighting issue was from before baylights.
