### ISSUE TITLE
Voting post round end is broken sometimes.

### ISSUE THREAD

**Issue by PJB3005** [vgstation-coders/vgstation13#4770]
It's very common, too, and when it happens it seems to happen for most people at the same time.

**Comment by CptWad** [comment]
Yeah when I type "vote" or use the verb, I cant vote unless the vote was prompted to me, like the round end vote. But the round end vote only works when I get the first chance. If I accidentally close the window it wont let me vote.
Happens all the time. I dont know whats causing it but it happens consistently.

**Comment by SGuivenne** [comment]
I don't believe this is still an issue, or if it is it should be more widespread reported.
