### ISSUE TITLE
Mining hidden complexes/hidden nests etc can spawn directly inside the Vox outpost

### ISSUE THREAD

**Issue by 9600bauds** [vgstation-coders/vgstation13#4776]
So you have a room of facehugger eggs right in the middle of the Vox trading outpost atmos room.

**Comment by wwjnc** [comment]
it's a feature

**Comment by Exxion** [comment]
```DM
// /vg/: Stop spawning shit inside of the vox hideout
if(locate(/turf/simulated/wall) in surroundings && !ignore_walls)
	return 0
```
??????????????
Why didn't they just look for `/area/vox_trading_post` like they did for `/area/mine/explored`?

**Comment by ComicIronic** [comment]
Hardcode is terrible.

**Comment by Exxion** [comment]
OK so like
```DM
for(var/area in NO_COMPLEX_AREAS)
    if(locate(area) in surroundings)
        return 0
```
And somewhere else define NO_COMPLEX_AREAS as whichever areas you don't want it to occur in but it otherwise could

A whitelist might be easier, on second thought
But that's just an example

**Comment by CptWad** [comment]
I think to best midigate it would be to add some type of buffer zone between the vox outpost and the asteroid proper, like the research station. If theres no "space" for caves none will spawn near it.

**Comment by ihadtoregisterforthis** [comment]
Has this been dealt with at any point?

**Comment by Exxion** [comment]
Nope I just saw this issue _today_
