### ISSUE TITLE
Can't examine anything while on a mech

### ISSUE THREAD

**Issue by 9600bauds** [vgstation-coders/vgstation13#4829]
to reproduce
acquire mech
pilot mech
attempt to examine
fail to examine
make issue on github

**Comment by PJB3005** [comment]
It always happens if you're not on a turf, inside a locker, being flushed through disposals, or, in this case, in a mech.

**Comment by clusterfack** [comment]
Time for some liberal application of get_turf(src)?

**Comment by ComicIronic** [comment]
I believe it's deliberate behaviour, however.

**Comment by clusterfack** [comment]
Could be

**Comment by 9600bauds** [comment]
Deliberate why?

**Comment by ComicIronic** [comment]
Other than the fact that you're stuck inside a suit of metal and can't exactly move closer to take a look at something.

**Comment by 9600bauds** [comment]
Well I mean... you can examine people from 8 tiles away. You're not exactly moving closer when you examine them.

**Comment by 9600bauds** [comment]
Some more context on to why this is more of a big annoyance than anything:
There's a guy in a Sec hardsuit with an egun out. You can very clearly see what he's wearing and the gun in his hand. You can see his name by hovering your cursor over him. You try to shift+click him so you can read his name better and have it logged in your chatlog, but your examination fails because you're on a mech.
You are piloting your firefighter Ripley. You are right up against a firelock that is flashing red, so you shift+click it to see the temperature difference on the other side. Despite being one tile away from the airlock, you are incapable of examining it, so you have no way of getting the temperature on the other side short of ejecting.

**Comment by Allspice** [comment]
![mech examine](https://i.imgur.com/PrSrrjC.png)

**Comment by Pathid** [comment]
Shift-click works. I want to note that you still can't right-click examine while inside something like a mech or closet.
