### ISSUE TITLE
(WEB REPORT BY: grizdale REMOTE: 198.245.63.50:7777) cryokenesis not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#4830]
> cryokenesis not working when I have a lot of powers
> 
> I assume it's one power knocking it out but it appears on my magic bar just does nothing
> 
> I expected it to work
> 
> it didn't work
> 
> give yourself lots of genetic powers till cryokenesis doesn't work it looks to be easily replicable as this has happened a few times to me

**Comment by clusterfack** [comment]
Probably caused by the spell being out of bounds, there's a runtime with that currently in spell code.
