### ISSUE TITLE
Silicons that died don't show ckeys

### ISSUE THREAD

**Issue by Ephx1** [vgstation-coders/vgstation13#4864]
On the round-end report, the list that shows ckeys for silicons doesn't show them if the silicon in question died.
It's been like this forever, but hey, might as well report it now.

**Comment by Intigracy** [comment]
Recently I was seeing silicon ckeys, I don't know if it's still true if the body is destroyed though.

**Comment by SGuivenne** [comment]
Fairly sure that loggings been updated to make this no longer an issue since this.

**Comment by jknpj** [comment]
nah this still happens
