### ISSUE TITLE
(WEB REPORT BY: rodocks REMOTE: 198.245.63.50:7777) Air rushing is messed up

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#4867]
> Revision (Should be above if you're viewing this from ingame!)
> Revision: 3814709dbcf49a172a267b3d3cbc3f4d08c52738 
> 
> General description of the issue
> Air rushes you too easily
> 
> What you expected to happen
> not to get knocked down every 5 seconds
> 
> What actually happened
> THE SUDDEN RUSH OF AIR KNOCKS YOU DOWN
> 
> Steps to reproduce if possible
> open most airlocks or be near an air 
> or be in the same post code as the airlock

**Comment by Shadowmech88** [comment]
What was the ZAS set to that round?

**Comment by dylanstrategie** [comment]
ZAS hardcore mode has been broken for almost ever now, the coder's general lack of expertise with ZAS code doesn't help much either
