### ISSUE TITLE
Diona Nymphs can hug themselves

### ISSUE THREAD

**Issue by Ephx1** [vgstation-coders/vgstation13#4945]
I guess because they can't examine themselves for wounds or something.

**Comment by ComicIronic** [comment]
Well who else would hug them

**Comment by FudgePucker** [comment]
I wish I could hug myself. ;-;

**Comment by ihadtoregisterforthis** [comment]
I call this a feature.
What do monkeys do when they click themselves on help intent?

**Comment by ghost** [comment]
Diaonae are monkey subtypes and monkeys can hug themselves therefore a diona can.
