### ISSUE TITLE
Can't buckle in mobs anymore

### ISSUE THREAD

**Issue by Ephx1** [vgstation-coders/vgstation13#4979]
OH GOD WHY, I NEED TO ARRANGE MY ANIMALS EXACTLY!
PANIC
EDIT: By mobs I meant the simple ones like a cow, or Ian. Should've noted that.

**Comment by CptWad** [comment]
Reported this a while ago  #3227. This is better worded, but apparently its to prevent mice from hijacking janicarts

**Comment by Ephx1** [comment]
Oh sorry, I should've searched first. Still, it's a bit annoying that you can't set Ian down next to you as HoP. Or whatever pet you'd like.

**Comment by CptWad** [comment]
scool. Theres a whole bunch of old issues I always look forward to deleting so better to get a more current one that people will see.

**Comment by Shadowmech88** [comment]
>apparently its to prevent mice from hijacking janicarts

Wouldn't be possible to prevent buckling in for mice only?

**Comment by CptWad** [comment]
I did not code it, I dont know. I'd guess a yes.

**Comment by 9600bauds** [comment]
This got changed specifically with chickens I believe, though you still can't buckle Runtime or the like

**Comment by MadmanMartian** [comment]
is fixd
