### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) brain duplication

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#5064]
> brain duplication when being a mommi and having an destroyed dead/lost or what ever body
> 
> For example, my body is dead and spaced and I become a mommi, If my mommi body is destroyed then my original brain is left over with the same name I had before death while the original brain is either destroyed or spaced
> 
> If I died I was expecting to be have a posi brain left over
> 
> My original organic brain is left over instead
> 
> die and lose body > become a mommi > die as a mommi > a duplicate brain is left over > my original brain is still somewhere

**Comment by clusterfack** [comment]
This report leaves so much information out, did he become a posibrain or respawn as a mommi, both should give different results.

**Comment by Cyadox** [comment]
Respawning as a derelict MoMMI and dying leaves no brain or posibrain, you simply ghost again.
Attempting to re-enter your previous body returns the message that you have no body.

Dying as a station-made MoMMI works as expected - roundstart are randomname MMIs, roundmade are whatever brain they had, posi or MMI.
