### ISSUE TITLE
Can't reset R&D research, re-linking machinery to R&D console is fucky

### ISSUE THREAD

**Issue by 9600bauds** [vgstation-coders/vgstation13#5085]
- Used the "Reset R&D Database" setting: didn't do anything
- Turned off the APC main breaker, thus depowering the console: didn't do anything
- Unscrewdrivered the monitor and screwdrivered it back in: Research levels still the same, all devices unlinked. Couldn't link devices again, as they were not being detected by the console any more.
- Was only able to re-sync with machinery after screwdrivering their panel open and then close, at which point they would be detected by the R&D console again.
- Completely disassembled the R&D console. Re-built it in a different location of the same room. Research remained.
- Completely disassembled the R&D console. Re-built it in central hallway. Research remained. (!)
- Turned off power to R&D server room. Turned off power to Research and Development. Re-installed console in Research and Development, and returned power. Research remained.
- Detonated bomb in R&D server room. Turned off console. Turned on console. Research remained.
- Committed suicide with a wrench. Research remained.
- Returned to life, restored the world to normal, used the R&D server console to try to delete designs. Was finally able to reset research levels. Was unable to delete individual designs, however.

There were never any runtimes at any point of the exercise.

**Comment by 9600bauds** [comment]
Related issues:  #4057 #4710

**Comment by Shadowmech88** [comment]
Given the fact that the research levels are reset instantly when one does so from the server room, without needing to sync the console, I'm going to assume that they are pulled directly from the server, and so the console's "Reset Database" function is not meant to apply to research levels.
"Reset Database" works as expected once the research levels are reset, removing all designs from the protolathe that can no longer be produced given the new research levels.
