### ISSUE TITLE
(WEB REPORT BY: thewhargoul REMOTE: 198.245.63.50:7777) Ready Up Error

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#5317]
> Revision (Should be above if you're viewing this from ingame!)
> 
> Clicked "Ready", Game starts, Am not sent into game, click unready then was able to click "Join Game" DeadPoolJ claims to of had this same issue. 
> 
> To be sent into the game at round start
> 
> Received a fuck you and was told to late join. 
> 
> Unsure if it's due to chance, would have to ready up before every round and see if it happens again.

**Comment by BestName** [comment]
Are you sure this isn't turned on?
![sieppaa](https://cloud.githubusercontent.com/assets/3892856/8612744/25d1caf2-26de-11e5-8506-77a206a7e0c8.PNG)
