### ISSUE TITLE
Deconstructing a computer down to the frame deletes materials/fibers on said frame

### ISSUE THREAD

**Issue by Intigracy** [vgstation-coders/vgstation13#5338]
What it says on the tin.

I'd expect to be able to scan a deconned computer to find out who deconned it.

**Comment by Probe1** [comment]
It also deletes the fingerprints for admins.  They can't even tell who deconned it.

**Comment by ComicIronic** [comment]
It's because the frame is actually a different atom spawned by the machine in decon.
There needs to be a transfer proc for moving fingerprints and fibres, though.

**Comment by FudgePucker** [comment]
Wait so I could decon the cloners chem desps, and cyro and admins wouldn't know who?
