### ISSUE TITLE
(WEB REPORT BY: myroc REMOTE: 198.245.63.50:7777) Switching characters after roundstart doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#5340]
> Revision (Should be above if you're viewing this from ingame!)

dd0374060d3cd9c5d711078df9bfccee28f7b34a

> General description of the issue
> If you sit in the lobby before the round starts, but haven't readied up, you can't switch or modify your character after the round has started. This can be aggravating as you can't look at the crew manifest before deciding what character you'll use.
> 
> What you expected to happen
> Being able to switch my characters.
> 
> What actually happened
> I was locked into one character.
> 
> Steps to reproduce if possible
> 1. Join the lobby before the round starts.
> 2. Wait for the round to start.
> 3. After the round has started, hit Declare Ready to have the button replaced with View Crew Manifest and Join Game!.
> 4. Choose Setup Character and try to change it or load another character.

**Comment by Ephx1** [comment]
I think it has something to do with clicking declare ready.
By default that locks your character before the round starts.
