### ISSUE TITLE
PICKWEIGHT() DOESN'T WORK PROPERLY WITH DECIMAL NUMBERS OH MY

### ISSUE THREAD

**Issue by wwjnc** [vgstation-coders/vgstation13#5379]
Since it uses `rand(1, total)` to choose the item to pick and `rand(x, y)` only returns integer numbers between `x` and `y`, you can potentially miss some options using decimal weights.

Example:

| **item** | A | B | C |
| --- | --- | --- | --- |
| **weight** | 1 | 1 | 0.1 |

Since `total = rand(1, total)` with `total = 2.1`, you'll get either `total = 1` or `total = 2`, which would choose A or B, but **never** C. This is the reason why the balloon bundle never shows up on the syndie bundle.

I blame Dylan, oldcode and Lummox. Please log a warning when `total` is not an integer, crash the server or turn on the panic bunker. And add proper documentation so this doesn't happen mysteriously again.

P.S. ALSO DON'T BE THIS GUY

``` dm
//Pretends to pick an element based on its weight but really just seems to pick a random element.
/proc/pickweight(list/L)
    // ...
```

**Comment by Exxion** [comment]
magical

**Comment by wwjnc** [comment]
You'd need to code a proc to return random floating point numbers though. Not knowing how the random number generation in Byond works makes this not optimal since it doesn't provide a rand() that returns a value between 0 and 1.

>trusting byond with floating point

**Comment by PJB3005** [comment]
yeah that pick syntax is ....

I BLAME LUMMOX

**Comment by Exxion** [comment]
>BYOND doesn't provide a rand that provides a value between 0 and 1

Have you read the DM ref? Yes it does.
That's what rand() does if not provided any args

**Comment by clusterfack** [comment]
Make a feature request/bug report on byonds forums if there isn't one

**Comment by wwjnc** [comment]
>That's what rand() does if not provided any args
I swear it didn't show up until I refreshed the page.

Is this a byondspiracy? #byondgate #notyourfeature

**Comment by wwjnc** [comment]
I'd still use integers since it avoids floating point errors and more shenanigans. But if any nerd wants to do it, you should only need to replace the `total = rand(1, total)` for `total = rand()*total` and instead of `return null` at the end, `return (L && L.len > 0) ? L[L.len] : null` because IEEE 754.

Pray that it doesn't break because of Byond though.

**Comment by 9600bauds** [comment]
[WHY]
