### ISSUE TITLE
Farmbot is broken

### ISSUE THREAD

**Issue by ancientpower** [vgstation-coders/vgstation13#5494]
The farmbot seems to be broken, it doesn't weed when set to weed and just sort of sits wherever you put it.  Really want this to be fixed since it'd be an invaluable tool to botanists if it actually functioned properly.

**Comment by Ephx1** [comment]
Even worse it'll automatically just go into kill mode after some time, even though no other bot actually does that.

**Comment by ancientpower** [comment]
Humans can change its behaviour controls but I don't think it does much since the farmbot just sits there anyways.  I noticed the kill mode thing the first time I made one and it was late in the round so I didn't know if it was the AI's fault or what.

**Comment by Ephx1** [comment]
Well, I've tried before just to turn it off kill mode.
I don't think silicons have any way to set it to start murdering, it's just a thing that happens.
And it seems that according to #2737 that this is a direct issue with BYOND.

**Comment by Probe1** [comment]
players can still change controls even after it goes to killmode.

A* needs to be replaced.

**Comment by Ephx1** [comment]
Cleanbots sort of clean? After it's sat still for ten minutes. I've seen it happen, but they're incredibly slow to clean so why even bother.

**Comment by 9600bauds** [comment]
I believe this was partly caused by farmbots getting stuck trying to path to the sink in the back of Hydroponics backroom, which has since been removed. I haven't used a farmbot recently so I don't know if they still do the thing.

**Comment by 9600bauds** [comment]
[Needs Confirmation]

**Comment by Intigracy** [comment]
@clusterfack milestone

**Comment by Probe1** [comment]
@Intigracy Make sure you don't fix whatevers going on that makes them attack you after roughly 30 minutes.

**Comment by jknpj** [comment]
Works on my machine
