### ISSUE TITLE
(WEB REPORT BY: crnibombarder REMOTE: 198.245.63.50:7777) Job prefrence bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#5512]
> Revision fix the job prefrence.
> 
> General description of the issue
> game made me a sec officer even though it was set to never, i didn't have "random job if unavalible" on either
> 
> What you expected to happen
> become an assistant or something better then sec officer
> 
> What actually happened
> ended up as the shittiest job on the station
> 
> Steps to reproduce if possible
> set sec officer to never
> get sec officer anyway

**Comment by Cyadox** [comment]
The only way this could happen is if they had 'Be assistant if nothing available' was on, asisstant slots were full, and they readied up. **Maybe**. Otherwise impossible to reproduce without knowing their settings.
