### ISSUE TITLE
(WEB REPORT BY: pokeblue REMOTE: 198.245.63.50:7777) readied up but had to un ready and join game

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#5513]
I joined the lobby pretty early on and readied up right away then the game starts and says enjoy the game but nothing happens so i unready up and it makes me join the game thus making me miss out on the round antags

**Comment by Ephx1** [comment]
You sure you didn't have "Return to lobby if preferences unavailable" selected? I've confused myself the same way.

**Comment by BestName** [comment]
Duplicate of #5317

**Comment by Ephx1** [comment]
May actually be a bug, one player was complaining of the same thing while they had "Random job" as their preference.

**Comment by BestName** [comment]
Yeah I'm not denying that. Just saying that this is a duplicate.

**Comment by Ephx1** [comment]
Oh no, sorry, I didn't mean it like that. Just pointing out my earlier comment. I probably should have edited it.

**Comment by clusterfack** [comment]
If he has join round as assistant, and there are too many assistants to security, I think this happens

**Comment by Cyadox** [comment]
An issue hasn't been made for this for over two years, and if it was still happening we would've seen plenty of bitching. Duplicate of #5512 , #5317. If you close this, close them as well.
