### ISSUE TITLE
(WEB REPORT BY: maddoscientisto REMOTE: 198.245.63.50:7777) Can get stuck between the transport tubes at the science outpost

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#5532]
> General description of the issue
> On the northwest side of the science outpost, in space, there's a spon where the transport tubes make a turn and behind them there's a single tile with some girders. 
> It's possible to get stuck into that spot by walking south from north through the tube
> 
> What you expected to happen
> to not get stuck
> 
> What actually happened
> I got stuck
> 
> Steps to reproduce if possible
> walk from north to sout through the tube to get into that spot

**Comment by ihadtoregisterforthis** [comment]
Yep, happened to me before

The tubes at 45° allow to slip under in only one way.

![deathtrap for hunters](https://cloud.githubusercontent.com/assets/13305885/8921314/4a6878e6-34aa-11e5-9621-0dd67e03a6bd.png)

I didn't have any mining tools as there was a "vampire problem" in the roid, but any non miner could have the same fate.

**Comment by gbasood** [comment]
Highest quality disembodied head hiding spot
