### ISSUE TITLE
(WEB REPORT BY: nmsct699 REMOTE: 198.245.63.50:7777) Library scan/printing books cuts off text

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#5731]
> Revision (Should be above if you're viewing this from ingame!)
> 1c2eddfbdbb5b556e9d5b8eee8cc4b4cbb88d7ee
> 
> General description of the issue
> Writing a long book, uploading it, then printing a copy from the archive gives you a cut-off version of the book
> 
> What you expected to happen
> The book I print from the archive to be identical to the one I wrote
> 
> What actually happened
> Book copy is cut off after printing it from the archive after about 58k characters counting spaces (~48.3k without). Old book will still be fine if taken out of scanner for comparison. Writing it is not the issue right now
> 
> Steps to reproduce if possible
> "write" a longass book for no monetary compensation and bind (>~58,000 characters counting spaces)
> scan and upload book
> print new book copy from archive
> printed copy will be cut off for no raisin

**Comment by PJB3005** [comment]
I think it's cutting off characters intentionally, but the limit should be much higher.

**Comment by robintime** [comment]
this seems to only be an issue in the round the book was written and uploaded in
