### ISSUE TITLE
H/E pipes exchange 1/4th of the ENTIRE PIPELINE's mols of gas

### ISSUE THREAD

**Issue by clusterfack** [vgstation-coders/vgstation13#5754]
I haven't really done the math on whether that makes them better or worse or the same. But I find it very unlikely that it's intentional.

**Comment by PJB3005** [comment]
7 Kelvin or bust

**Comment by clusterfack** [comment]
It makes it harder to get to 7 kelvin when you are radiating with a higher heat capacity.

That's why you get the coldest temps with ultra low pressures.

So in that case it's actually worse @PJB3005

**Comment by PJB3005** [comment]
oh

**Comment by clusterfack** [comment]
The way it works is, it takes the combined energies of space particles and the gas, then divides them by the combined heat capacity. Space is taken to be 6.4 K.

So if your gas has a heat capacity of 100, space has a heat capacity of 100. It works like this
Final temp = 100 * temp + 100 * 6.4 / (200)

**Comment by FudgePucker** [comment]
Wouldn't it still be better for if you want to cool large amounts faster?
That would be a little balanced, thermal plates are better at super cooling but HE pipes are better at cooling large amounts.

**Comment by 9600bauds** [comment]
I don't understand what this means or why this is a problem but I wish I did

**Comment by clusterfack** [comment]
To get it you have to understand the difference between pipelines and pipenetworks

Pipenetworks are built from pipelines and pipe devices, each pipeline and device has its own gas contents, which all equalize each tick. 

Pipelines are built from regular pipes and only have one 'air' that they all share.

So each thermal plate is a pipe device that radiates into space with its 200L of gas with space each tick, and then equalizes each tick. (Also since they are all doing an identical process I optimized them so that they just use the same value between them)

However h/e pipes were created as simple pipes and part of a pipeline, so when they exchange gas with space **each one** is exchanging pipes*200L of gas, the amount of gas in the **whole pipeline**. So that entire pipeline is doing the entire radiate process as many time as there are h/e pipes in it, (which makes it so the optimization I made cant even work on them, which is annoying) and could give wildly different values from the gas exchange.

**Comment by FudgePucker** [comment]
Okay I think I am starting to understand.
How would you even fix this, it is a pipe not a device.
Only way I can think of is have it be a pipe, but also a device that stores and cools the gas. Have it be a double sided thermal plate and pipe at the same time. No idea if that would be even possible though.

**Comment by clusterfack** [comment]
I think this is relevant again due to threadposting. Someone uses like 3 h/e pipes to chill the entirety of distro.

This works insanely well because it cools literally EVERY mol of gas in distro at once.

**Comment by 9600bauds** [comment]
I still don't understand this sadly

**Comment by FudgePucker** [comment]
@9600bauds
Flow does not exist.
When a pipe is connected to another pipe, it increases the volume of the pipe network and becomes part of it.
Gas does not flow pipe to pipe, connected pipes act like one giant canister, the tempature, pressure, and content remain the same in the entire network.
Thermal plates are a device, not a pipe. They take in a few litters of gas and change the tempature, then extanges it back into the network it was attached to.
H/E pipes are pipes, not devices. It changes the entire networks tempature, not a few litters at a time.

**Comment by 9600bauds** [comment]
But if they account for the pipeline's volume, wouldn't there be no effective difference anyways?

**Comment by DrCelt** [comment]
This needs to be fixed.

**Comment by ihadtoregisterforthis** [comment]
This is not how autoclosing is done
