### ISSUE TITLE
(WEB REPORT BY: edwarus REMOTE: 198.245.63.50:7777) jukebox unmovable

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#5859]
> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Cant unwrench the jukebox
> 
> What you expected to happen
> the jukebox to move
> 
> What actually happened
> nothing
> 
> Steps to reproduce if possible
> I turned the jukebox to syndie mode then back so i could mess with settings not sure why its unwrenchable i might just be overlooking something but i dont think so

**Comment by Probe1** [comment]
overlooked the map, the location, whether it could possibly have been adminbus or anything else

**Comment by jknpj** [comment]
duplicated issue #14040 and #9747
