### ISSUE TITLE
List of the problems the crew monitor has

### ISSUE THREAD

**Issue by Ephx1** [vgstation-coders/vgstation13#5945]
- ~~Z-Level swapping is just screwed, trying it kills the monitor for you. Relog or wait some time for it to work again.~~ The menu to Z-level swap is fucking DISGUSTING, it takes several tries to even punch in the z-level, constantly unfocusing the window.
- Suffocation damage isn't blue on the map screen damage listings.
- People who are dead on the map screen are always listed as being alive when moused-over.
- Positronic Brains always look dead on the map screen.
- Text overlaps occasionally in a clusterfuck on the text screen. DOES actually happen, only with really long names usually Vox, they'll crossover to the health status and no amount of window resizing helps.
- ~~Sometimes while switching over maps between rounds, the previous map will display instead of the one you're currently on. This only happens if you do not disconnect and reconnect between map changes.~~
- Sometimes when switching Z-levels, the crew monitor mixes them up, showing say, the asteroid z-level while showing main station suit sensors.

**Comment by clusterfack** [comment]
>People who are dead on the map screen are always listed as being alive when moused-over.

When you say this were the people actually dead or alive

**Comment by clusterfack** [comment]
Also an image of the last one would be useful

**Comment by PJB3005** [comment]
@d3athrow

**Comment by Ephx1** [comment]
They were in-fact dead, this is most apparent when you see suicides, their 200 suffocation damage while still reading (Living). I'll try to get pictures in a bit.

**Comment by Ephx1** [comment]
Couldn't reproduce the text fuckery, but I'm assuming it has to do with a lot of suit sensors listed.

**Comment by Ephx1** [comment]
Lord almighty the list just gets bigger.

**Comment by Imagebard** [comment]
HAVE YOU TRIED JUST FIXING IT

**Comment by Ephx1** [comment]
no, who does that?

**Comment by Zth--** [comment]
Look at all those dupes. I think this needs a high priority tag

**Comment by 9600bauds** [comment]
@d3athrow please
I tried to fix this thing and it was fucking impossible, it's an impenetrable brick of caked shit and it's spread over 5 fucking files

**Comment by Ephx1** [comment]
At the very least you could change the z-level switching menu, right? That's the biggest complaint I had from it. Being unable to put in a number because of its constant unfocusing was bullshit, it just needs to be a 1-6 without 2 to pick a z-level, like a borg module selection menu.

**Comment by 9600bauds** [comment]
I literally couldn't because the button for the menu is hardcoded inside the .dm (have to recompile after every change) but it actually executes a JAVASCRIPT function which is defined in another file but is actually used in some fucking .js and the problem is that since it's javascript BYOND rejects it like cancer cells I don't even know dude this thing is a maze

**Comment by chatsonf** [comment]
BUMP

**Comment by Imagebard** [comment]
Whyyyyyy

**Comment by chatsonf** [comment]
Cause cluster has been working on it

**Comment by Imagebard** [comment]
I relaxed for a moment
Please smash that by telling me how cluster is "working on it". Is he rewriting it completely, fixing some choice parts, whatever the hell?

**Comment by chatsonf** [comment]
Uh ask him he just did some bugfixing on it, said that "the crew monitor is 100% bugfixed"

**Comment by Imagebard** [comment]
>Bugfixing

Henk

**Comment by Ephx1** [comment]
It's been a year, I need to check if these are still true.

**Comment by PJB3005** [comment]
They almost certainly are.

**Comment by kol1th** [comment]
It keeps happening

**Comment by PJB3005** [comment]
Add "it's not Nano" to the list.

**Comment by 9600bauds** [comment]
Didn't you say Nano "could" be OK for things that never updated contents like a preference menu

Isn't the crew monitor the polar opposite of that criteria

**Comment by Iamgoofball** [comment]
Nani's gimmick is autoupdates

**Comment by PJB3005** [comment]
@9600bauds where did I say that.

Nano isn't ideal for UIs like this no, but it at least fucking worked.

**Comment by Probe1** [comment]
N-nani?
