### ISSUE TITLE
Slime people don't have sprites for missing feet/arms

### ISSUE THREAD

**Issue by Zth--** [vgstation-coders/vgstation13#5946]
~~They are not immune to electricity like the wiki says~~ Fixed in #9722. Also I believe they don't have sprites for missing feet/arms
~~http://puu.sh/kxKJ5/3f52a9ea79.png~~

**Comment by Intigracy** [comment]
Hopefully an easy fix.

**Comment by ComicIronic** [comment]
Electricity issue got fixed, I believe.

**Comment by PJB3005** [comment]
Yep.

**Comment by ComicIronic** [comment]
What about the limb thing?

**Comment by PJB3005** [comment]
Oh, shit

**Comment by Zth--** [comment]
Edited OP

**Comment by jknpj** [comment]
Got fixed in the refactor
