### ISSUE TITLE
Ventcrawling Mapping Issue

### ISSUE THREAD

**Issue by clusterfack** [vgstation-coders/vgstation13#5949]
Current a large number of the maps have a fatal ventcrawling flaw, if you travel in a straight line along the main pipeline, you will end up flying out of a vent because occasionally the main pipeline will take a 90 degree turn and travel down one tile and continue while the path in a straight line leads straight into a vent.

This is terrible in a lot of ways for mommis and anything that is trying to travel through the pipes while being stealthy as unless you are going extremely slowly (while you travel very quickly in pipes) you will accidentally run out and screw yourself.

As far as I have seen this applies to all maps and both the waste/distro pipelines in a number of places almost at random.

**Comment by PJB3005** [comment]
Yep can confirm, now we have pipe layers we need to fix this.

**Comment by Probe1** [comment]
the only thing I could think of when I read this was http://puu.sh/ky32A/ea451e5735.ogg

I'll get right on remapping dozens or hundreds of pipes so people who aren't being stealthy and running pipes as fast as possible won't pay for it.

**Comment by clusterfack** [comment]
@Probe1 how is remapping the dozens or hundreds of pipes going?

**Comment by Ephx1** [comment]
What if you could have it set to alt+click out of a vent if you like? That way you can go as fast as you want without popping out, if you want it back to normal just toggle the setting to instantly pop out again.

**Comment by clusterfack** [comment]
Like the idea but runs up against players that dont know how to into hotkeys

**Comment by ihadtoregisterforthis** [comment]
I'd add to this the possibility of more pipe redundancy. Sometimes to get into a room ventcrawling there is the need of surrounding the entire general location. Meta is great in this matter. Box has a bunch of weird separations, like in the surgery or in the bar.

**Comment by PJB3005** [comment]
This is so fucking true for power cables too.

Did you know that the cable powering arrivals and **security** runs through *cargo*, of *all* departements?

**Comment by DrCelt** [comment]
@clusterfack only like 1% use the vent crawl command anymore.

**Comment by clusterfack** [comment]
Making people learn hotkeys for basic functionality with every object turns away any newcomers to the game Celt.

**Comment by dylanstrategie** [comment]
An alternative and somewhat easier solution to this is adding a small do_after interaction to getting out via a vent, with appropriate before and after messages

**Comment by jknpj** [comment]
Someone fixed this already.
