### ISSUE TITLE
Air alert staying after combination of breach and power loss.

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#5968]
(WEB REPORT BY: scribnibblers REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 3ebabfface561244ee32a539f90602955b567c52 
> 
> General description of the issue
> primary tool storage apc destroyed and when silicons repired the apc the air alarm would never go away on the atmos cconsole.  it does go away on the air aalarm itself but the computer always says its red on the map view and the detail list 
> 
> What you expected to happen
> not this
> 
> What actually happened
> red instead of green when the air alarm was cleared
> 
> Steps to reproduce if possible
> lolbombs next to the apc then fix it

**Comment by PJB3005** [comment]
Alarms really need to be handled on an area basis, and more robustly so.

**Comment by Shadowmech88** [comment]
Appears to no longer exist. I bombed the Primary Tool Storage APC, repaired it, and then patched the hole, and the alert on the alert computer disappeared after the air in the room returned to normal.
