### ISSUE TITLE
Wood Floors don't burn

### ISSUE THREAD

**Issue by ghost** [vgstation-coders/vgstation13#5985]
Self-explanatory. Apply fire to a room with wood floor, it won't burn

I know having the whole Bar engulfed in flames whenever someone dropped fuel in here is a bit hardcore, but that's kinda how wood works

**Comment by Exxion** [comment]
Call it flame-retardant spacewood
Problem solved

**Comment by AutismSpider** [comment]
but the wood made form god damn mushrooms

**Comment by clusterfack** [comment]
That's odd because it used to

**Comment by AutismSpider** [comment]
Thing is wooden floors would burn a hole into space some how.

**Comment by Kurfursten** [comment]
The wood is just tiling, there is still lower plating that prevents a breach

**Comment by AutismSpider** [comment]
the old burn code it had.

**Comment by PJB3005** [comment]
@AutismSpider definetly just shitcode.

If people say "balance because sigarette = bar fucked", make the fire spread *really* slowly, give people MORE than enough time to get an extinguisher.

**Comment by dylanstrategie** [comment]
Ideally, wood floors would take a long time to burn and release relatively low heat, so that crewmen inside the room have time to evacuate and fetch a fire extinguisher

**Comment by PJB3005** [comment]
Issue is, fires are dumb, and a fire always has the energy output of plasma.
