### ISSUE TITLE
speech can still be heard in space

### ISSUE THREAD

**Issue by Angelite191** [vgstation-coders/vgstation13#6124]
Before saycode changes, all dialogue in atmos less areas had to be done through comms. Now atmos has no effect on speech. Don't know if it's a feature or bug.

**Comment by Zth--** [comment]
I always could talk normally to miners or scientists on the asteroid... Which is shit because muh immulsions. Feature loss here

**Comment by Kurfursten** [comment]
In space, everyone nearby can hear you scream.
