### ISSUE TITLE
Alt + Click electrification isn't working for cyborgs

### ISSUE THREAD

**Issue by Hoshi-chan** [vgstation-coders/vgstation13#6189]
What it says on the tin.

**Comment by clusterfack** [comment]
Did pomf override it with alt clicking to see a tiles stuff?

**Comment by Hoshi-chan** [comment]
No. This is a recent development. Borgs can do both.

**Comment by clusterfack** [comment]
Same as the last issue I closed

**Comment by clusterfack** [comment]
Actually not apparently

**Comment by jknpj** [comment]
Seems like someone commented the code on purpose.
