### ISSUE TITLE
Sending away crates on the cargo shuttle no longer gives you money

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#6214]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b76413cea42dc2fb60beb438fcebd3774ea23b24 

No idea if this is intentional but it's been like this for a very, VERY long time. Seems like anything you send whether it be plasma or stamped supply sheets or crates gives you absolutely no money towards the computer's account.

**Comment by Probe1** [comment]
working as intended since the point system was removed

**Comment by kernikov** [comment]
Where's my recycling credit.

**Comment by dylanstrategie** [comment]
Not working as intended. This was broken because Rei couldn't bother to port old Cargo mechanics over to the new station account system

Sending crates, plasma sheets and stamped receipts should give money as it used to to help kickstart Cargo orders

**Comment by Probe1** [comment]
n3x15 was the one that removed the point system not rei, it was in a response to rei.

**Comment by PJB3005** [comment]
This is still working IIRC, it just gets sent to the cargo account, which doesn't get used...

**Comment by DeityLink** [comment]
Exporting goods for money from Centcom will be added as part of the Economy revamp.

Thus this issue is a feature request more than a bug report.

**Comment by Zth--** [comment]
Its actually a feature loss

**Comment by ghost** [comment]
Check if it still happens with the Economy rework Deity pushed, otherwise please fix it @DeityLink

**Comment by DamianX** [comment]
There's a whole new system to handle centcom orders now.
