### ISSUE TITLE
APC not charging even when there is power

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#6234]
(WEB REPORT BY: blarghargin123 REMOTE: 158.69.55.2:7777)
I maxed out all the SMES and some of the APCs dont charge, areas are losing power even though there is 600,000 watts of power in the grid. The APC says external power is good, but are not chargeing. Checking the Power Monitor it says the total power is 600 kilo watts, total load is 230000 watts and total demand is 16324 watts.

**Comment by Zth--** [comment]
I noticed the demand rises if you have tons of power on the grid, and lowers if you have only 600000W. The demand should increase if there's not enough power, not decrease...

**Comment by Kurfursten** [comment]
Powernet has been acting very strange lately - it has always been a bit mysterious, of course. I noticed one shift after upgrading all the SMES and outputting 1MW to the grid that some APC still weren't charging.

**Comment by clusterfack** [comment]
The issue with this iirc is that the SMES power draw isn't counted as part of the load. Thus everyone would believe that it uses less power than it actually does when it is trying to charge the smes as well.

**Comment by dylanstrategie** [comment]
Powernet is really fucky. Basically it charges whenever it wants to, and good luck if you don't have exactly enough power to overcharge the powernet

**Comment by DeityLink** [comment]
This can happen when an APC's power has been shorted, (such as when pulsing wires))

**Comment by Kurfursten** [comment]
While true, it would be really obvious if that was the case (everything in the area would be turned off, even doors and atmos)

**Comment by Kurfursten** [comment]
@Exxion This is definitely not a bug anymore
