### ISSUE TITLE
Catwalks are not seen as valid flooring for a variety of things.

### ISSUE THREAD

**Issue by PJB3005** [vgstation-coders/vgstation13#6243]
@dylanstrategie.

**Comment by dylanstrategie** [comment]
Catwalks aren't considered turfs IIRC, so it needs either a snowflake check or an OOP fix to whatever proc checks for turf status in this case

**Comment by PJB3005** [comment]
Really, what we need, is `/turf/proc/is_valid_floor()`, which checks for stuff like catwalks.

**Comment by DeityLink** [comment]
It's not really an oversight. The on_floor parameter exists so you cannot build girders, walls, etc on catwalks. I think the issue here is to force canisters to be built over floors. I'll remove that requirement.

**Comment by PJB3005** [comment]
@DeityLink if you do that, you'll make it possible to build them in space, for example.

The reason I made this report is because it USED to be possible to do, before @dylanstrategie ONCE AGAIN broke shit when he refactored catwalks.

**Comment by DeityLink** [comment]
@PJB3005 what's wrong with building a canisters in space though? They aren't anchored by default, and there's a bunch of objects that you already can build in space.

**Comment by PJB3005** [comment]
The actual issue here isn't technically fixed, the one I reported just got band-aided.

**Comment by dylanstrategie** [comment]
A ton of things have been "band-aided" to allow catwalks to become objects like lattices

For example, I had to make space intact to force cables to show over it and add a conditional so that you could lay cable on a space turf "with a catwalk on it", which is fucking terrible but at the time I really wasn't competent enough to fuck with cable code and general helper procs

**Comment by gbasood** [comment]
Wait why is this a bug
Why aren't we just handling this on a case-by-case basis
There's much less that we'd want to be able to construct in space than not

**Comment by PJB3005** [comment]
@gbasood thanks to dylan's age old catwalk rework catwalks aren't turfs anymore.

The issue is most things that check for valid flooring check if the turf isn't space which it now is...

**Comment by gbasood** [comment]
Catwalks as in the ones made of rods in space, right? On top of other rods in space?
I don't see how that's a problem.

**Comment by ghost** [comment]
Think about it this way : A ton of checks for flooring expect to use turfs, since the floor is 100 % made out of turfs

But due to the nature of catwalks, they fit better as objects, like lattices (for example, they show OVER space, which is a turf, and could show over any other turf in general)

We thus either need to create brand new checks for objects or generalize a ton of checks to the atom level

**Comment by gbasood** [comment]
No I understand exactly what the problem outlined is
But I don't see how it's actually a problem
The last thing this was a problem for was computer frames and I haven't seen anything since that needs to be secured to catwalks.

**Comment by PJB3005** [comment]
Singularity field generators.

And no I do not consider a band-aid for that a valid fix.

I will personally keep this issue open until it's actually fixed.

**Comment by gbasood** [comment]
Well then, the best way would be to fix base machinery anchoring to allow catwalks if it doesn't find a valid turf first.

Maybe an override var to only allow turfs? Not sure that we have machinery that needs that though

**Comment by Shadowmech88** [comment]
Are there things we want to be built over turfs, but *not* over catwalks? Or do we want everything able to be built over both catwalks and turfs?
If the latter, couldn't we just do
`if(on_floor && (istype(T, /turf/space)) && !(locate(/obj/whatever/catwalk in T)))`?
Or does this affect more than just stack construction, which would require the `locate()` to be copy-pasted to a bunch of places?

**Comment by DeityLink** [comment]
Make new tickets for specific catwalk-related bugs. Lets let this one rest.
