### ISSUE TITLE
Warning stripes and some other decals can still be cleaned right off with soap

### ISSUE THREAD

**Issue by dylanstrategie** [vgstation-coders/vgstation13#6287]
Come on now, Janitors don't have a tile painter handy

**Comment by kernikov** [comment]
They should, it's more of custodial duty than an engineer's.
Who even has access to one at round start?

**Comment by AutismSpider** [comment]
no one does not even the engineers they have to be made.

**Comment by Kurfursten** [comment]
On Box I believe the bartender has one
