### ISSUE TITLE
Bottom Chem Box Station

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#6309]
(WEB REPORT BY: publicenemymaipai REMOTE: 158.69.55.2:7777)
The Bottom Chem Dispensor on Box station buggs out every now and then and clicking on it wont open the machine unless i relog, and then it only works ocne before bugging out again.

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by ihadtoregisterforthis** [comment]
Is there a problem with the web reporter?

**Comment by PJB3005** [comment]
I've experienced this too, it's not related to that specific dispenser, it's some combination of shitcode + nanoUI if I had to guess.

**Comment by Probe1** [comment]
yeah the solution is to leave the room or restart your client.  it usually sorts it out.

**Comment by PJB3005** [comment]
@Probe1 wait, leaving the room fixes it?

This is... weird.

**Comment by Probe1** [comment]
What fixes it is fucking off for a while. Leaving the room (going away until whatever is shitting up stops shitting up) helps.

**Comment by 9600bauds** [comment]
I've always experienced this with precisely the bottom chemdispenser in Box, never with any other. It's weird and I hate it.

**Comment by Kurfursten** [comment]
@Exxion This is just a known NanoUI bug, we can't do anything to fix it, the only workaround is to leave for a few minutes and come back later and it will work again. Probably close.

**Comment by PJB3005** [comment]
That's not how issue trackers work.

You just give up and close issues because nobody's gonna fix it.

**Comment by Exxion** [comment]
Alright but this *is* fucking ancient
Also, why me?
