### ISSUE TITLE
Nano_UI breaks yet again, wont show cameras on security camera computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#6446]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 935d3b6798a346d3d08b491bc6e2a85e577a1322 
> Nano UI once again breaks. Tried restarting the process, regenerating nano ui maps, respawning the computer, nothing worked. Probably yet another one time thing that isn't consistent but still annoying and it seems we still can't narrow down as to why it happens.

**Comment by clusterfack** [comment]
Its not nano

**Comment by Rei1226** [comment]
The entire text page is blank and it's controlled by nano UI, how could it not be nano?

**Comment by clusterfack** [comment]
See you said it again, but read my post again, the computer is not nano

**Comment by PJB3005** [comment]
@Rei1226 pomf @d3athrow reworked the computer so it doesn't use nano (as it lagged a shitload).

What's your IE version.

**Comment by Probe1** [comment]
Probably less than E11, which is where the issue comes from sadly.

Also Rei may be mistaking the /N/ logo for Nano instead of NanoTrasen

**Comment by Rei1226** [comment]
I have the newest version of IE. This wasn't just a problem on my end, it was reported by someone else, and no one was able to use it at all.

And woops, I always assumed the new grey UI as opposed to the very old basic white one was all nano ui. At least, thats what all that stuff was labeled as when it first started getting introduced on the server years ago.

**Comment by Shadowmech88** [comment]
Due to its age and the difficulty in reliably testing something like this, I'll just go ahead and close this.
I'm sure there are numerous other reports to its effect littered throughout the repo anyway.
