### ISSUE TITLE
Cutting/Pulsing Fire Alarms Doesn't Do Anything Anymore

### ISSUE THREAD

**Issue by Kurfursten** [vgstation-coders/vgstation13#6497]
You can still completely remove the wiring or disable the sensing with the multitool, but if an atmos issue occurs, the firelocks still respond exactly as normal.

Feature loss.

**Comment by FudgePucker** [comment]
This is due to air alarms I think.

We should test emaging fire alarms in a room with no surrounding air alarms, so that means removing air alarms

**Comment by clusterfack** [comment]
Yeah fire alarms used to do what air alarms do now I believe

**Comment by PJB3005** [comment]
Fire alarms still respond to fire, the issue is that 99% of the time the heat increase from said fire will trigger the air alarm.

**Comment by FudgePucker** [comment]
Better idea, emags make the fire alarm always on until deconstructed, making the fire locks always down.

**Comment by PJB3005** [comment]
Jesus Christ seeing somebody emag EVERY airlock is bad enough, if we were to add that it'd be an apocalypse.

**Comment by FudgePucker** [comment]
@PJB3005 Exactly, instead of emaging fire locks being pointless and doing something that a screwdriver and wirecutters can do, it does something outrageous and worthy of being hunted down for.

**Comment by PJB3005** [comment]
@FudgePucker emagging every airlock isn't something everybody with a screwdriver and pair of wirecutters can do, to fix an emagged airlock you need to take the electronics out, repair the electronics, and put them in again.

**Comment by Kurfursten** [comment]
Just to be clear, my report has nothing at all to do with emags.

I'm talking about using the wirecutters or multitool on it to disable it.

**Comment by FudgePucker** [comment]
Ohhhhh, now that I reread it I see now. My bad.

I think there is only like one fire alarm with out a corresponding air alarm in the ghetto burn chamber south of cargo on box, and disabling that one wouldn't change much because no fire locks.
