### ISSUE TITLE
Can't splash water on a monkey cube from a beaker

### ISSUE THREAD

**Issue by Ephx1** [vgstation-coders/vgstation13#6575]
What the FUCK.
How am I supposed to xenobiology faster?
Injecting them with water from a syringe doesn't work either.

Also water looks white now, why is that?

**Comment by PJB3005** [comment]
FYI: monkey cube on sink = monkey.

**Comment by clusterfack** [comment]
Some fag made water white, it was probably dylan

**Comment by Ephx1** [comment]
Yes, I know Monkey on a sink = monkey, but I used to be able to splash water on cubes directly without having to do that bullshit, more of a Feature Loss than a request.

**Comment by Exxion** [comment]
Does putting a monkey cube on wet floor activate it? If not, it should. That would allow for assembly line efficiency xenobiology if you order a few showers and build a few conveyors.

**Comment by Kurfursten** [comment]
What ever happened to good old, hard-working, American xenobiologists that use a fire extinguisher to make 3 monkeys at once, like the rest of us honest joes?

**Comment by Ephx1** [comment]
See the thing about using a fire extinguisher for monkeys is that I like to keep everything nice and clean.
Too many monkeys and a slime might consider them a friend while eating another.
Not only that, but the fire extinguisher is limited, and if you're like me with juggling many slimes, I run out quickly. Then the water tank runs out. And either I have to trek out of my nice cozy cubbyhole to get another, or go through the annoying process of filling it up via sink with a wrench.
Also with the monkey cube splashing I could have a few in pocket, pop out a monkey and instantly disposal them into the pen.

**Comment by clusterfack** [comment]
Someone probably broke reagents again, maybe reagent containers this time, who knows. 

Anything to do with reagents is just bugs waiting to happen.

**Comment by ghost** [comment]
@dylanstrategie Did this get fixed in your reagent PR?

**Comment by ghost** [comment]
Might have been, needs a check

**Comment by Intigracy** [comment]
Well?

**Comment by Probe1** [comment]
The issue still exists.  Tested now.

**Comment by Probe1** [comment]
Dude I have no idea how the fuck this code works.

**Comment by clusterfack** [comment]
If I recall correctly the after attack of the reagent container on things like objects causes it to Splash the reagents onto the object which means either that code is messed up or the monkey cube doesn't have code for the reagent being applied on touch

**Comment by Exxion** [comment]
Well, showers and fire extinguishers do activate monkey cubes, but I wouldn't really be at all surprised if that's just snowflake code and has nothing to do with the reagent being applied on touch

**Comment by clusterfack** [comment]
Yeah it's hard to underestimate level of snowflake code
