### ISSUE TITLE
Constructs can't see who is a cultist

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#6679]
(WEB REPORT BY: wizardcrying REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 3bbf052ed0e3df72cb97a686f2414a4142bbf8289
> 
> General description of the issue

As a juggernaut, I could not see who else was a cultist, just whoever converted me.

> What you expected to happen

To see a cult HUD ion over all cultists as a construct

> What actually happened

I only saw the person who made me a construct as a cultist

> Steps to reproduce if possible
> 
> Have two or more cultists in a room, and have two non-cultists
> Kill one non-cult
> Have a cultist take a soulstone, stone the dead guy, and put them into any construct
> VV into the construct
> You now only see your convertee as a cultist

**Comment by Zth--** [comment]
Note: he was a dead cult

**Comment by Wizardcrying** [comment]
Yeah, I forgot to mention that.

**Comment by Shadowmech88** [comment]
I'm going to assume this no longer exists due to so much of antag code being replaced by antag datums.
