### ISSUE TITLE
When a nuke goes off, everybody is now stuck laying down

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#7527]
Regardless if its on board or off board, if a nuke goes off and you are alive, you will be stuck on the floor

**Comment by ihadtoregisterforthis** [comment]
Only affects post round griff since it ends anyways

**Comment by Skullyton** [comment]
Everybody gets buckled to a bed in nullspace for some reason apparently

**Comment by gbasood** [comment]
I actually don't think this matters at all, so I'll remove it from the milestone.

**Comment by CptWad** [comment]
I think it matters. I want my post round griff.
I guess replace [bug] with [feature loss]

**Comment by SGuivenne** [comment]
Did this ever get changed?

**Comment by jknpj** [comment]
nope

**Comment by jknpj** [comment]
actually, yes but everyone is still buckled to nullspace

**Comment by Exxion** [comment]
Now that the nuke actually explodes, it should probably just kill everyone immediately rather than buckling them down
(Assuming it still does this)

**Comment by Pathid** [comment]
It kills everyone on the z-level I think. However it leaves them standing up and ungibbed even if they're in the epicenter. Still buckles everybody.

**Comment by Exxion** [comment]
Alright that's not even a possibility I had considered
Does it make them invulnerable during the cutscene, too?
