### ISSUE TITLE
If you die and get cloned as a wizard and cast blink, you teleport near your old corpse

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#7814]
Title says it all

**Comment by FudgePucker** [comment]
How does a wizard get cloned anyways?
Like really, why the fuck would you clone a wizard? Someone went to all the trouble of killing them, and then some asshole decides to clone them.

Also maybe it is missing a check on what position the wizzyman is at, and instead uses the old corpse as the position.

**Comment by CptWad** [comment]
I am a very good bullshitter
They MMI'd me and I said I was mindswapped.

**Comment by Shadowmech88** [comment]
Apparently spells are no longer kept after cloning, so this should no longer be possible.
