### ISSUE TITLE
Changelings + robotic limbs dont play well

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#7838]
Horror form lings should also probably "Drop" Robotic limbs (not blow up or anything) because it leads to bad shit

**Comment by 9600bauds** [comment]
can you exemplify

**Comment by CptWad** [comment]
If I recall, robotic limbs could delete themselves when regenerating. Or maybe they exploded, I dont quite recall

**Comment by DamianX** [comment]
Tested, robotic limbs get replaced by regular limbs when you regen. Feature? Bug? Close?

**Comment by CptWad** [comment]
Its been a while. I guess its irrelivant enough now so long as the limbs dont explode
