### ISSUE TITLE
Doubletraitors can earn the same type of objective twice, leading to a clown who needed to steal the AI twice

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#7917]
Interestingly enough he stole one AI and got both instances of the objective successful

**Comment by gbasood** [comment]
that's because the logic check doesn't check for unique AIs

**Comment by Exxion** [comment]
You can also get both escape alive and die, which is hilarious.

**Comment by Exxion** [comment]
Doubletraitor was fixed by role datums
