### ISSUE TITLE
Round end report missing success/unsuccessful antags in some modes

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#7928]
So far from what I remember, Vox raiders and Nuke ops both do not show up. I think Blob stuff and others, but I dont remeber.
I know cult, wizard, vamp, ling and tators all show up. All else should be checked.

**Comment by ihadtoregisterforthis** [comment]
I'll close #7373 in favor of this

**Comment by Exxion** [comment]
The blobs show up but it doesn't mention whether or not they completed their objectives

**Comment by TermedClepe** [comment]
I think cult doesn't show objectives.

**Comment by Zth--** [comment]
Heist, cult, nuke don't show objectives. Rev and blob don't show completion

**Comment by Exxion** [comment]
And raiders don't show up at all, I think

**Comment by gbasood** [comment]
honestly scoreboard deserves a complete overhaul in terms of code structure
it went from well-formatted and extensible to "LETS THROW VIEW CODE IN WITH LOGIC CODE BECAUSE WE'RE LAZY"

**Comment by Imagebard** [comment]
Blob does show if the AI won. But only the AI, which is a secondary victory. No mention on if the crew or the blob won.

**Comment by Exxion** [comment]
Probably fixed by role datums, and if it wasn't, it's a completely different bug than this
