### ISSUE TITLE
Meteors act as low-grade bombs and not immovable rods.

### ISSUE THREAD

**Issue by AutismSpider** [vgstation-coders/vgstation13#8030]
Not saying we should buff all the meteors to act like rods.

The xbox huge meteor should act like immovable rod and after hitting X things or on a timer blow up into tiny meteors

**Comment by clusterfack** [comment]
I've already suggested to Dylan that he make a change somewhat like this

**Comment by Skullyton** [comment]
>Large meteor crashes into station
>Once it receives enough damage, it breaks into smaller meteors
>Smaller meteors eventually lose enough momentum that they scatter into sand, ores, and strange rocks(?)

**Comment by clusterfack** [comment]
Yeah making scattershells or something to that effect would be pretty easy with projectile code

**Comment by Skullyton** [comment]
Now, here's the thing

I suggested that a bit ago, and N3x15 shot it down with "but that would lag the server, meteors are supposed to be just kinetic bombs"

**Comment by clusterfack** [comment]
Nexis never used the profiler ingame, had little idea on what would or wouldn't lag
