### ISSUE TITLE
New player punishment: Cockroaches

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#8077]
Since I cant code yet but I will forget this before I ever do Ill write it here
Lets say catbeast don't cut it.
Turn the player into a controlled cockroach
They cant fight back and have to run from the crew as a worthless mob that can't even open doors on its own
Also being a unlucky roll on the cursed die would be cool too

Tested somewhat in game, cant transform and have to assign keys to cockroach by hand. Also cockroach has no animation beyond directional when player controlled. Its all the fun of hunting catbeasts but in a small package

**Comment by 9600bauds** [comment]
Glaring flaw: Killing a cockroach is not as fun as killing a catbeast

**Comment by CptWad** [comment]
When it runs as fast as I was going as a cockroach I think they found it satisfying once I was finally squashed

**Comment by Arthurdentist** [comment]
its funnier to turn them into a catbeast with no arms

**Comment by ComicIronic** [comment]
But you can already make your character a Turk
