### ISSUE TITLE
Fucked up shit happened with plasma doors

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#8217]
Because of clown, some newbie set fire to some plasma doors
thats not as important, the issue was that the ensuing plasmafire blew fueltanks leading the plasma to get spaced, what happened was that whenever atmos techs/mommi managed to syhpon the air out suddenly plasma would return, eventually making its way out of the robotics lab and through the station
somethings fucky with them plasma doors

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/12970979/37f773f6-d063-11e5-97f5-aff0e1822fd4.png)

**Comment by CptWad** [comment]
>it makes pure napalm

jesus christ

**Comment by clusterfack** [comment]
The person who originally made them didn't know how to into atmos

**Comment by DrCelt** [comment]
Does anyone?

**Comment by Probe1** [comment]
Yes but only good coders.

**Comment by Sprok0** [comment]
More then that, they add the napalm to turfs in range instead of view, and will put fire on the other side of solid walls

**Comment by Probe1** [comment]
That's just awful.

**Comment by PJB3005** [comment]
There's no reference to napalm anywhere except confusing variable naming for the gas mixture that gets used to add plasma to.
