### ISSUE TITLE
Master belt can spawn humanoid mobs

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#8294]
Though I am for the belt spawning hard core monsters, humanoids also drop weapons and traitor gear, the syndicate commando specifically has an esword and eshield which is insane because that makes any player near invulnerable to tasers and lasers making them a murderbone machine. Theres also the humanoids that spawn guns that you can reload on your own, but the commando is more shitty

**Comment by Shadowmech88** [comment]
Humanoids just need children that don't drop their items on death, so the belt can spawn those instead.

**Comment by CptWad** [comment]
id be cool with that.

**Comment by CptWad** [comment]
woops
