### ISSUE TITLE
Add sounds to Norris

### ISSUE THREAD

**Issue by AutismSpider** [vgstation-coders/vgstation13#8389]
Can we add hermit crab chirping sounds to him or what?

https://www.youtube.com/watch?v=qWgDGHUvPQ0

https://www.youtube.com/watch?v=vsiHUWPo9xI

**Comment by Shadowmech88** [comment]
You know Norris isn't actually a crab, right?

This is what Norris is based off of:
![image](https://cloud.githubusercontent.com/assets/3991927/13193744/85dc4a38-d743-11e5-8fa0-47ca9102f266.png)

**Comment by AutismSpider** [comment]
he missing the human head part when you look at his icon though

**Comment by Shadowmech88** [comment]
That doesn't mean he's a crab, though.

**Comment by NigglyWiggly** [comment]
His sprite is a human head with eyes and little legs though

**Comment by AutismSpider** [comment]
looks nothing like a head though add some hair to it or some thing

**Comment by Blithering** [comment]
When you examine Norris, it says he screams a lot, how about adding random screaming?
