### ISSUE TITLE
Animals, including mice and in my case giant spiders can be autotraitored

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#8446]
As bus I decided to take control of a spider and proceed to skitter about
I was autotraitored
there is also the one instance where a mouse was autotraitored so I guess this is a bit of a problem

**Comment by AutismSpider** [comment]
happens with borers even though it was fix it keeps happening.

**Comment by Shadowmech88** [comment]
Since pulling items counts as having them, a simple_animal would still be able to accomplish its objectives, right?
That being the case, I think this should be considered a feature.

**Comment by Exxion** [comment]
Mice can't pull though

Just make it so that when a mouse would be autotraitored, roll again for another actual autotraitor but also give the mouse an objective to eat a certain amount of cheese

**Comment by Probe1** [comment]
I've made space carp traitors before AND THEY SUCCEEDED.

**Comment by Ephx1** [comment]
Also happens to pAIs.

**Comment by AutismSpider** [comment]
@Probe1 Well carps do have the magic power to bash open any locker/crate open on top of moving fast on biting limbs off

**Comment by Exxion** [comment]
So do most, if not all, `simple_animal/hostile's

**Comment by AutismSpider** [comment]
@Exxion Carp have it easy they are the fastest simple but have low hp

**Comment by Shadowmech88** [comment]
I'm pretty sure autotraitoring simple_animals was fixed recently, wasn't it?

**Comment by clusterfack** [comment]
I dont think they were ever given an explicit exception in traitoring

**Comment by MadmanMartian** [comment]
Still an issue
