### ISSUE TITLE
Job preferences and such

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#8610]
Today I was bwoinked by a new player, who put assistant all the way up on their prefrences, and was chosen to be the HoP
This leads to my two main issues with roundstart job selecting
First: Very young players can access very dangerous jobs. There needs to be a lengthening on the probation periods so new people don't have the quick opportunity to be captain or some shit
Second: When someone selects assistant, have it so that if they dont get to be assistant they get randomly selected to simple jobs, such as miner, botonist, service and cargo. No implanted roles

discuss

**Comment by Shadowmech88** [comment]
What is the current waiting time on choosing head positions for new players?

Additionally, it might be better to simply add a "disabled" option in addition to never, low, medium, high, etc. Jobs with the disabled option would never ever ever be selected, even if they have "give random job if preferences unavailable" or some such option in effect.

**Comment by Ephx1** [comment]
I'm not even sure how the fucking job selection works.
Its priorities are all fucked, like why it would pick a borg over an AI if they're both on low and there's no damned AI.

**Comment by Kitfox88** [comment]
God knows I wish I could set both borg and AI to high with all the other stuff I also enjoy at medium, then the rest at low.

**Comment by ihadtoregisterforthis** [comment]
Miner is also high on the priorities, many rounds I've ended up as one of the three at roundstart when all my other choices were empty.

**Comment by Kurfursten** [comment]
> Second: When someone selects assistant, have it so that if they dont get to be assistant they get randomly selected to simple jobs, such as miner, botonist, service and cargo. No implanted roles

This is how assistant used to be, you either have it toggled on or off. I don't think people liked this. It just gives you less power in choosing your job.

> I'm not even sure how the fucking job selection works.

It works by first assigning the heads of staff in random order, then assigning the remaining jobs in random order.

>Miner is also high on the priorities

It's not, this is just coincidence. If you want an empty job, use the Get Empty Job preference.

**Comment by robintime** [comment]
head priority is fixed by #26080 and #9389. assistants who did not get an assistant slot being randomly assigned to other open jobs even without prefs is fixed in 014e6e3 by returning them to lobby.

**Comment by nervere** [comment]
No longer an issue. Testing done by @Inorien - thanks!
