### ISSUE TITLE
(Feature Request) Biting should transfer bloodborne base diseases

### ISSUE THREAD

**Issue by AutismSpider** [vgstation-coders/vgstation13#8625]
Got be bite on bear skin or some thing

**Comment by 9600bauds** [comment]
Bear race when?

**Comment by Arthurdentist** [comment]
then there would be no safe way to give some shithead prisoner a dangerous disease so that he can suffer with it in perma (not that i've ever actually seen anyone try this anyway)

**Comment by 9600bauds** [comment]
Knock their teeth out

**Comment by AutismSpider** [comment]
@Arthurdentist  can kick tool box etc peoples teeth out
