### ISSUE TITLE
How to insta-crit people as wizard

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#8740]
>Take mutate and lightning
>Walk up to poor sucker (if you test this, it wont work on centcomm z-level so get on the station/derelict)
>Cast mutate
>Cast lightning
>Click the fucker AS FAST AS YOU CAN
presto they are dead
The lightning makes the mutate's fire cooldown nothing allowing it to be fired as fast as you can click
[expliotable]
I meant to make this last night but it was past midnight and I passed out

**Comment by 9600bauds** [comment]
>Balance

This is a fucking bug
That said though, I haven't been able to reproduce. Neither the nocooldown nor the instahusk.

**Comment by 9600bauds** [comment]
lol butten

**Comment by CptWad** [comment]
I seriously did it yesterday lemme test it again

**Comment by CptWad** [comment]
Yeah I am reproducing it
I spawn myself in, give myself lightning and mutate, then click a mob really fast and as long as there is lightning on the screen the eyelasers come out as fast as I can click

**Comment by Exxion** [comment]
But lightning alone can instacrit anyway
Or at least insta-pain-crit, which is basically as bad because, while you do not die from it, you can't move out use items or anything

**Comment by Shadowmech88** [comment]
Just tested locally, could not reproduce.
Gave myself mutate and lightning, triggered mutate, then cast lightning and fired the lasers. The lasers seemed to have a normal delay regardless of whether I had the lightning spell or whether there was an actual lightning projectile on the screen.
