### ISSUE TITLE
simple mobs or something?

### ISSUE THREAD

**Issue by Boxe** [vgstation-coders/vgstation13#9047]
you can't buckle in mobs like chicken and cows, nor can you click-drag them into lockers or disposals

gonna take a guess and blame dylan/celt for this shit

fix this

**Comment by gbasood** [comment]
It's always been that way as far as I know?

**Comment by Boxe** [comment]
nuh uh, i used to be able to buckle in borers, chickens, cows, etc for ez chef fun

now i have to shove cows into lockers

that makes milking them more annoying

**Comment by Skullyton** [comment]
leashes when?

**Comment by Shadowmech88** [comment]
This still exists, but I *think* it might be intentional.
I don't remember for sure, though.

**Comment by clusterfack** [comment]
I think unid(?) Changed it to fix mice getting buckled into the janicart for example. I dont really agree with it personally.

**Comment by Shadowmech88** [comment]
Couldn't he have just exempted vehicles in particular?

**Comment by clusterfack** [comment]
Probably

**Comment by gbasood** [comment]
Why shouldn't mice be able to get buckled into the janicart anyway

**Comment by Shadowmech88** [comment]
My *guess* is that they're able to control it once buckled into it.

However given that they need a human to buckle them into it, I don't see much harm in it.

**Comment by Intigracy** [comment]
They can't control it without the key.

**Comment by Shadowmech88** [comment]
Oh, right.

Well what's even the problem then?

**Comment by MadmanMartian** [comment]
closed by #18324
