### ISSUE TITLE
I am going to choke someone, or reducing damage husks corpses

### ISSUE THREAD

**Issue by ShiggyPiggy** [vgstation-coders/vgstation13#9227]
#### Description of issue

If you apply an advanced trauma/burn kit to a patient with damage over 200 (say, 210), that is not husked, they will husk and lose all of their blood.
#### Difference between expected and actual behavior

Expected: bringing damage below the defib threshold
Actual: the corpse suddenly husked and lost all blood
#### Steps to reproduce
1. Get a dead guy with 200+ brute/burn (still below, say, 300 to prevent husking)
2. Apply an advanced kit to him
3. Watch him husk and lose all his blood
4. Scream
5. Repeat
#### Length of time in which bug has been known to occur

All the fucking time
#### Server revision

a7d74f8c381741e7e34b7fa0ddb4c8ac62d2c567
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Killette2** [comment]
How do they even get over 200 burn damage without husking? I'm pretty sure anything over 200 was an auto husk, from space being on fire, beating a dead body with a welder, and even eating too much chili peppers.

**Comment by ShiggyPiggy** [comment]
@Killette2 I've seen both cases happen, and burn husks start at 230, IIRC.

**Comment by Killette2** [comment]
So what happens if I beat a guy up with 200 brute damage, then apply a welder. Or for defibulation's sake, I choke the man to death for 200 oxy damage then apply the 15 with a welder? He won't husk until 200 burn damage right? Will the same bug occour with 200 oxy and 15 burn when an attempt to treat is made, or is it only the damage that cannot be immediately treated such as oxy?

**Comment by ShiggyPiggy** [comment]
I've seen it happen primarily with 100+ brute/burn each, low 200s of either, too.
