### ISSUE TITLE
revert cancer aka extreme butt pains

### ISSUE THREAD

**Issue by Boxe** [vgstation-coders/vgstation13#9293]
#### Description of issue

cancer exists
#### Difference between expected and actual behavior

cancer should not exist
at the very least the surgery should still exist to cure it
as of now you may as well catbeast someone if you're going to give them cancer so it just wastes medbays time
#### Steps to reproduce

login whilst dylanstrategie is active
#### Specific information for locating

adminwho
#### Length of time in which bug has been known to occur

since he cancer got merged
#### Server revision

555-555-5555
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)
- [x] Too lazy to read half this shit.

**Comment by Intigracy** [comment]
[9285]

**Comment by 9600bauds** [comment]
Brain damage was already shit desu

"Hey instead of bwoinking the guy or catbeasting him let's instead make it so that Medbay has to fix 
them"

This just makes it 20x harder than a pill and is not even funny to other players

**Comment by FudgePucker** [comment]
Hey guys, I have a great idea, lets merge a PR adding back in cancer made by dylan, I mean, WHAT COULD POSSIBLY GO WRONG?

**Comment by clusterfack** [comment]
I mean nothing really since its just an admin thing it being amended to prayers or whatnot should be changed though

**Comment by dylanstrategie** [comment]
We could always remove the quick button from prayers and centcomm messages if it's not proving to be popular

As for the Surgery, I couldn't get it working (it never worked, and the PR that "removed it" simply did so because I still couldn't get it to work and had to fix the much more urgent problem of amputations not removing cancer). If someone else wants to take a shot at it, they can. The files I modify don't become sanctified

**Comment by ihadtoregisterforthis** [comment]
It could be said that quite the opposite

**Comment by Manaony** [comment]
Remove cancer, AKA dylan

**Comment by SangriaMonkey** [comment]
>literally giving yourself a griff button

:alien:

**Comment by 9600bauds** [comment]
The most spectacular thing is that he gave himself a griff button and someone else used it more than him

**Comment by dylanstrategie** [comment]
>He gave himself a griff button

Citation desperately needed

**Comment by Imagebard** [comment]
Go away Dylan, we know what you did.

**Comment by SangriaMonkey** [comment]
![ayy](http://i.imgur.com/SqHe2b9.png)
:hotsprings: :point_right: https://github.com/d3athrow/vgstation13/pull/9033 :eyes: :joy:  :ok_hand: :100: :fire: :fire: :fire: :fire:

**Comment by ihadtoregisterforthis** [comment]
![1720711-spider_mansickprm](https://cloud.githubusercontent.com/assets/13305885/14370028/56084070-fd2a-11e5-9086-9f4db5fdbff6.jpg)
![1720711-spider_mansickprm](https://cloud.githubusercontent.com/assets/13305885/14370052/9eb2ab1c-fd2a-11e5-9073-e237782456e1.jpg)

**Comment by Boxe** [comment]
>has +SPAWN
>doesn't have +FUN

#8559

**Comment by dylanstrategie** [comment]
Yeah, I made a flag that spawns clothing use +SPAWN instead of +FUN

It's not like I sneaked it past the post either, I had to get some sort of approval from the maintainers, you know

**Comment by Manaony** [comment]
Considering what get merged I highly doubt any maintainer thought before doing it.

**Comment by SangriaMonkey** [comment]
>my newfound crusade against the obvious lack of balance in the distribution of admin verbs relative to flags

http://ss13.moe/forum/viewtopic.php?f=29&t=2284
Looks to me like you got bored with the whole administration and bugfixing thing in the end. I don't know dude. I mean I get it, it's not a fun job, but you could have gone through the proper channels and gotten your flags without raising suspicion about your motives or integrity.

**Comment by dylanstrategie** [comment]
Do you have frankly any idea how many verbs are under +FUN ? If I actually wanted to powertrip, I wouldn't have made a PR that changes a single verb, an unimportant one at that (allows you to quickly dress a mob up) and with a proper, logical justification (it spawns clothing, so it should be under the same verb that allows you to spawn items)

**Comment by SangriaMonkey** [comment]
Still seems like powercreep on your part.

**Comment by Duny-** [comment]
This should probably be closed.
