### ISSUE TITLE
Traitor item: Stasis cigars

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#9406]
Works like stasis beakers only it activates once you smoke it
Could be a good chemist/bartender item
EXPLODING CIGARS
NAPALM CIGARS
EMP CIGARS
POLYACID SMOKE CIGARS
costs 3 or 4 or 5 crystals

**Comment by 9600bauds** [comment]
\>hey want a cigar
\>no
\>

**Comment by Probe1** [comment]
cool shit

**Comment by Killette2** [comment]
But exploding cigars are already a thing...

**Comment by CptWad** [comment]
yes but this would support more than just explosions
and you could control the damage of said explosions, or what it gives into a person, chloral polysmoke etc. Creativity inspiring items are great

**Comment by nuklearcellphoneg** [comment]
When you smoke a cigarette/cigar, does it dump all reagents into you at once? This would certainly certainly be pretty neato, though it's limited somewhat to explosion/smoke tricks(which is of course fitting for a cigar),

Probably the biggest factor to look at would be the size of the cigar itself. IIRC, cigars hold 30 and 15/15 water potass might be negligible(been awhile but I mostly dealt with 50/50 grenades, plus there's a cap on beaker based grenades, or grenades in general, I forget which).

Also directing the damage only to the head would be nice.

**Comment by CptWad** [comment]
Well yeah size has yet to be discussed.
50-60-75 seems reasonable, once we get to 100 we start breaching the hull with water-potas
Unless thats totally fine
then again corn oil bombs can do l o d e s of damage if in high amounts and if its a bartender item then he is sure to focus on that
not that its entirely bad but lets not have a new form of early cubanpete

**Comment by Probe1** [comment]
@nuklearcellphoneg is right, for water potas 30 isn't enough to cause damage.  I believe that 35 is the sweet spot for breaking open lockboxes and the strategy is to hold the beaker in your freaking hand and pour it into the other beaker that's on the same tile as the lockbox.

**Comment by 9600bauds** [comment]
The sweet spot is 40 each

**Comment by nuklearcellphoneg** [comment]
>then again corn oil bombs can do l o d e s of damage if in high amounts

Unless it's changed in the mean time, that's not actually true.

Nitro bombs got an extreme nerf, mostly in order to avoid water/potass bombs being abused, unfortunately. Of course, this was before I was even an admin... I got a botanist to grow as much corn as he could(he went brain dead before I finished) but I made like a 300 ish nitro bomb(a miner had brought one of those neato beakers from the asteroid) and the resulting explosion was

well, the size of a max cap water potass bomb. I'd be happy to know if this has been fixed in nitro's favor in the interim, though.

**Comment by Shadowmech88** [comment]
I believe all explosions resulting from reagent reactions are capped at 1 dev.

**Comment by Killette2** [comment]
To test nitro bombs, you can always take the ez route if you can't varedit corn and use the corn oil naturally found in the deepfrier, just add more chems. However I'm sure you'll be disappointed by any nitro explosion.

**Comment by CptWad** [comment]
nitro bombs were nerfed?
aww

**Comment by Killette2** [comment]
@CptWad 

I made a nitro bomb in the kitchen using a deepfrier once, thinking it would kill everyone around me along with me (pic bellow, before the bomb. pic after wasn't even worth saving)

Caused a hull breach just where the deep frier was, and just minor damage else around, only harming me and the captain. All others suffered minor injuries not even breaking bones.

![deepfryathon](https://cloud.githubusercontent.com/assets/5169310/14503290/75ac054a-017d-11e6-85a3-b5e0fb5e31d5.png)

**Comment by 9600bauds** [comment]
Chemistry explosions are capped at (1, 3, 6)
That's 105 water + 105 potassium or 21 glycerol + 21 sacid + 21 pacid
In one hand, it's kinda shitty
On the other, I'm not sure if I want any chef/botanist/mechanic throwing around literal dozens of high-yield explosives that only require an autolathe for the assembly, at least TTVs are exclusive and limited

**Comment by Probe1** [comment]
yeah that was pretty much the thoughts when it was capped.

it can go up to idk 2 6 12 12 is pretty impressive for light damage.

**Comment by Killette2** [comment]
You also need to consider the effort put into the mass production of said grenades, and how it would usually be easy to detect who's mass producing said items unless they really go out of their way to hide it somehow.

**Comment by Hoshi-chan** [comment]
Cue three successive rounds of p.acid smoke cigars, followed by no one ever smoking again.

**Comment by nuklearcellphoneg** [comment]
I would continue smoking.

But I smoke the green packs. :^)

**Comment by MercuryDoll** [comment]
When i read the title i was thinking of the Big Boss' cigars. Which could be used like a reusable cigar, comes with three doses of healing stuff and can be refilled manually.
... now that i think about it: VAPE WHEN?

**Comment by Shadowmech88** [comment]
It turns out that cigarettes and cigars already do this.
